//! Chatbot route handlers.
//!
//! Provides endpoints for conversational AI:
//! - `POST /api/v1/chat` — send a message and receive a response.
//! - `POST /api/v1/chat/stream` — SSE streaming endpoint.

use axum::{
    extract::State,
    response::{
        sse::{Event, Sse},
        Json,
    },
};
use futures::stream::Stream;
use sensei_auth::middleware::AuthenticatedUser;
use sensei_core::error::Result;
use sensei_services::ai::chatbot::ChatSamplingParams;
use serde::Deserialize;
use std::convert::Infallible;
use std::pin::Pin;
use std::task::{Context, Poll};
use tokio::task::JoinHandle;
use tokio_stream::wrappers::BroadcastStream;
use tokio_stream::StreamExt;
use tracing::error;

use crate::state::AppState;

/// Request body for a chat message.
#[derive(Debug, Deserialize)]
pub struct ChatRequest {
    /// The user's message text.
    pub message: String,
    /// Optional conversation ID to continue an existing conversation.
    pub conversation_id: Option<String>,
    /// Maximum number of tokens to generate (optional).
    pub max_tokens: Option<usize>,
    /// Sampling temperature (optional, 0.0 = greedy).
    pub temperature: Option<f32>,
    /// Top-k sampling parameter (optional, 0 = disabled).
    pub top_k: Option<u32>,
    /// Top-p (nucleus) sampling parameter (optional).
    pub top_p: Option<f32>,
}

impl ChatRequest {
    /// The per-request sampling overrides, if any were provided.
    fn sampling_params(&self) -> Option<ChatSamplingParams> {
        if self.max_tokens.is_none()
            && self.temperature.is_none()
            && self.top_k.is_none()
            && self.top_p.is_none()
        {
            return None;
        }
        Some(ChatSamplingParams {
            max_tokens: self.max_tokens,
            temperature: self.temperature,
            top_k: self.top_k,
            top_p: self.top_p,
        })
    }
}

/// Response body for a chat message.
#[derive(Debug, serde::Serialize)]
pub struct ChatResponseBody {
    /// The assistant's response text.
    pub response: String,
    /// Unique conversation identifier.
    pub conversation_id: String,
    /// Whether this response was generated by fallback pattern matching.
    pub is_fallback: bool,
    /// The deterministic verification envelope: claims about live tenant
    /// data must carry evidence; this reports whether the response is
    /// decision-grade (the legacy assistant can no longer bypass the agent
    /// verification layer).
    #[serde(default)]
    pub verification: Option<serde_json::Value>,
}

/// Handle a single-turn chat message.
///
/// Returns a JSON response with the assistant's reply.
pub async fn chat(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<ChatRequest>,
) -> Result<Json<ChatResponseBody>> {
    user.require_permission("ai:inference")?;
    let response = state
        .chatbot_service
        .chat(
            user.tenant_id,
            user.user_id,
            &req.message,
            req.conversation_id.as_deref(),
            req.sampling_params(),
        )
        .await
        .map_err(|e| {
            error!(error = %e, "Chatbot chat failed");
            e
        })?;

    // Item 22: the legacy chat surface flows through the SAME agent
    // control plane as the tool surface — server-created context, the
    // effective (policy-filtered) toolset and the deterministic verifier.
    // The assistant can no longer answer with unverifiable tenant claims:
    // every response is checked against the caller's real permissions and
    // the tool contract.
    let ctx = crate::routes::agent::build_context(&user, &state).await;
    let policy = sensei_agent_core::tools::PolicyEngine::new(
        crate::services::agent::build_readonly_tools(),
        sensei_agent_core::tools::ToolRisk::ReadOnly,
    );
    let effective_tools = policy.effective_tools(&ctx);
    let verification = verify_chat_response(&response, &ctx, &policy, &effective_tools);
    Ok(Json(ChatResponseBody {
        response: response.message.content,
        conversation_id: response.conversation_id,
        is_fallback: response.is_fallback,
        verification: Some(verification),
    }))
}

/// Run the REAL claims/evidence verifier over the assistant's reply
/// (item 25): every sentence that states a FACT about live tenant data
/// must carry evidence. The previous loop inspected only the (already
/// permitted) effective toolset, which by construction always passed.
/// Now: factual-sounding statements become ObservedFact claims WITHOUT
/// evidence refs, and the deterministic verifier flags them — the same
/// contract the tool surface enforces.
fn verify_chat_response(
    response: &sensei_services::ai::chatbot::ChatResponse,
    ctx: &sensei_agent_core::context::AgentContext,
    _policy: &sensei_agent_core::tools::PolicyEngine,
    _effective_tools: &[&sensei_agent_core::tools::ToolSpec],
) -> serde_json::Value {
    let mut issues: Vec<String> = Vec::new();
    let content = response.message.content.clone();
    let lower = content.to_lowercase();

    // Factual-sounding statements: sentences that mention live tenant data
    // (quantities, counts, statuses, ids) in an assertive way. These are
    // ObservedFact claims and REQUIRE evidence — the assistant produced
    // none here, so they are violations.
    let factual_markers = [
        "is ",
        "are ",
        "stands at ",
        "currently ",
        "has ",
        "there are ",
        "total ",
        "count ",
        "units ",
        "inventory",
        "ncr",
        "capa",
        "andon",
        "work order",
        "production",
        "quality",
        "defect",
        "scrap",
    ];
    let mut claim_sentences: Vec<String> = Vec::new();
    for sentence in content.split(['.', ';', '\n']) {
        let s = sentence.trim();
        if s.len() < 12 {
            continue;
        }
        let has_number = s.chars().any(|c| c.is_ascii_digit());
        let mentions_data = factual_markers.iter().any(|m| lower.contains(m));
        if has_number && mentions_data {
            claim_sentences.push(s.to_string());
        }
    }

    if response.is_fallback {
        issues.push(
            "Fallback/general answer — not grounded in tenant evidence; \
             treat as guidance, not as a validated fact."
                .to_string(),
        );
    } else {
        for claim in &claim_sentences {
            issues.push(format!(
                "Unverified factual claim: '{claim}' — no EvidenceRef. \
                 Facts about live tenant data must be queried through the \
                 tool surface, stated as unavailable, or labeled a hypothesis."
            ));
        }
    }

    // The context is SERVER-CREATED: the caller's effective scope is
    // attached so the client can see WHERE the answer applies.
    let verdict = if issues.is_empty() {
        "pass"
    } else {
        "needs_evidence"
    };
    serde_json::json!({
        "verdict": verdict,
        "issues": issues,
        "claims_checked": claim_sentences.len(),
        "context": {
            "site_id": ctx.site_id,
            "value_stream_id": ctx.value_stream_id,
            "work_center_id": ctx.work_center_id,
            "shift_id": ctx.shift_id,
        },
    })
}

/// Stream wrapper that aborts a background task when the stream is dropped.
///
/// The chat generation task is aborted as soon as the client disconnects
/// (the HTTP response body — and therefore this stream — is dropped), so a
/// disconnected client never leaves a generation task running.
struct AbortOnDrop<S> {
    inner: S,
    task: Option<JoinHandle<()>>,
}

impl<S> Drop for AbortOnDrop<S> {
    fn drop(&mut self) {
        if let Some(task) = self.task.take() {
            task.abort();
        }
    }
}

impl<S: Stream + Unpin> Stream for AbortOnDrop<S> {
    type Item = S::Item;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Pin::new(&mut self.inner).poll_next(cx)
    }
}

/// Handle a streaming chat message via Server-Sent Events.
///
/// Returns an SSE stream where each event contains a token (or chunk) of the
/// response. The background generation task is aborted when the client
/// disconnects.
pub async fn chat_stream(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<ChatRequest>,
) -> Result<Sse<impl Stream<Item = std::result::Result<Event, Infallible>>>> {
    user.require_permission("ai:inference")?;
    let sse_manager = state.sse_manager.clone();
    let chatbot_service = state.chatbot_service.clone();

    // Item 26: the stream carries the SAME trust guarantee as the JSON
    // chat — the full response is buffered, verified, and only then
    // released with its verification envelope.
    let ctx = crate::routes::agent::build_context(&user, &state).await;

    // Generate a unique channel name for this streaming session
    let channel = format!("chat-{}", uuid::Uuid::new_v4());

    // Subscribe to the channel before spawning the background task
    let rx = sse_manager.subscribe(&channel).await;

    // Spawn a background task to run the streaming chat
    let channel_clone = channel.clone();
    let sampling = req.sampling_params();
    let task = tokio::spawn(async move {
        match chatbot_service
            .stream_chat(
                user.tenant_id,
                user.user_id,
                &req.message,
                req.conversation_id.as_deref(),
                sampling,
            )
            .await
        {
            Ok(mut token_rx) => {
                // BUFFER the full reply, then run the same claims/evidence
                // verification as the JSON chat (item 26) — the stream can
                // no longer bypass the trust contract.
                let mut buffered = String::new();
                let mut stream_error: Option<String> = None;
                while let Some(token_result) = token_rx.recv().await {
                    match token_result {
                        Ok(token) => buffered.push_str(&token),
                        Err(e) => {
                            stream_error = Some(e.to_string());
                            break;
                        }
                    }
                }
                if let Some(e) = stream_error {
                    sse_manager.publish(&channel_clone, "error", &e).await;
                    return;
                }
                // Verify the buffered reply as an ordinary ChatResponse.
                let chat_response = sensei_services::ai::chatbot::ChatResponse {
                    message: sensei_services::ai::chatbot::ChatMessage {
                        role: "assistant".to_string(),
                        content: buffered.clone(),
                        timestamp: chrono::Utc::now(),
                    },
                    conversation_id: req.conversation_id.clone().unwrap_or_default(),
                    is_fallback: buffered.is_empty(),
                };
                let policy = sensei_agent_core::tools::PolicyEngine::new(
                    crate::services::agent::build_readonly_tools(),
                    sensei_agent_core::tools::ToolRisk::ReadOnly,
                );
                let effective_tools = policy.effective_tools(&ctx);
                let verification =
                    verify_chat_response(&chat_response, &ctx, &policy, &effective_tools);
                // Release tokens only after verification completed.
                sse_manager
                    .publish(&channel_clone, "token", &buffered)
                    .await;
                sse_manager
                    .publish(
                        &channel_clone,
                        "verification",
                        &serde_json::to_string(&verification).unwrap_or_default(),
                    )
                    .await;
                sse_manager.publish(&channel_clone, "done", "").await;
            }
            Err(e) => {
                sse_manager
                    .publish(&channel_clone, "error", &format!("{e}"))
                    .await;
            }
        }
    });

    // Build an SSE stream from the broadcast receiver using BroadcastStream
    let broadcast_stream = BroadcastStream::new(rx);

    // Map each broadcast item into an SSE Event, filtering out lagged items
    let event_stream = broadcast_stream.filter_map(|result| {
        match result {
            Ok(msg) => Some(Ok(Event::default().data(msg))),
            Err(_) => None, // Skip lagged/dropped messages
        }
    });

    // Dropping this stream (client disconnect) aborts the generation task.
    let abort_on_drop = AbortOnDrop {
        inner: event_stream,
        task: Some(task),
    };

    Ok(Sse::new(abort_on_drop))
}
