//! Chatbot route handlers.
//!
//! Provides endpoints for conversational AI:
//! - `POST /api/v1/chat` — send a message and receive a response.
//! - `POST /api/v1/chat/stream` — SSE streaming endpoint.

use axum::{
    extract::State,
    response::{
        sse::{Event, Sse},
        Json,
    },
};
use futures::stream::Stream;
use serde::Deserialize;
use sensei_auth::middleware::AuthenticatedUser;
use sensei_core::error::Result;
use std::convert::Infallible;
use tokio_stream::wrappers::BroadcastStream;
use tokio_stream::StreamExt;
use tracing::error;

use crate::state::AppState;

/// Request body for a chat message.
#[derive(Debug, Deserialize)]
pub struct ChatRequest {
    /// The user's message text.
    pub message: String,
    /// Optional conversation ID to continue an existing conversation.
    pub conversation_id: Option<String>,
    /// Maximum number of tokens to generate (optional).
    pub max_tokens: Option<usize>,
    /// Sampling temperature (optional, 0.0 = greedy).
    pub temperature: Option<f32>,
    /// Top-k sampling parameter (optional, 0 = disabled).
    pub top_k: Option<u32>,
    /// Top-p (nucleus) sampling parameter (optional).
    pub top_p: Option<f32>,
}

/// Response body for a chat message.
#[derive(Debug, serde::Serialize)]
pub struct ChatResponseBody {
    /// The assistant's response text.
    pub response: String,
    /// Unique conversation identifier.
    pub conversation_id: String,
    /// Whether this response was generated by fallback pattern matching.
    pub is_fallback: bool,
}

/// Handle a single-turn chat message.
///
/// Returns a JSON response with the assistant's reply.
pub async fn chat(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<ChatRequest>,
) -> Result<Json<ChatResponseBody>> {
    let response = state
        .chatbot_service
        .chat(
            user.tenant_id,
            user.user_id,
            &req.message,
            req.conversation_id.as_deref(),
        )
        .await
        .map_err(|e| {
            error!(error = %e, "Chatbot chat failed");
            e
        })?;

    Ok(Json(ChatResponseBody {
        response: response.message.content,
        conversation_id: response.conversation_id,
        is_fallback: response.is_fallback,
    }))
}

/// Handle a streaming chat message via Server-Sent Events.
///
/// Returns an SSE stream where each event contains a token (or chunk) of the
/// response. The stream ends when the receiver is dropped.
pub async fn chat_stream(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<ChatRequest>,
) -> Result<Sse<impl Stream<Item = std::result::Result<Event, Infallible>>>> {
    let sse_manager = state.sse_manager.clone();
    let chatbot_service = state.chatbot_service.clone();

    // Generate a unique channel name for this streaming session
    let channel = format!("chat-{}", uuid::Uuid::new_v4());

    // Subscribe to the channel before spawning the background task
    let rx = sse_manager.subscribe(&channel).await;

    // Spawn a background task to run the streaming chat
    let channel_clone = channel.clone();
    tokio::spawn(async move {
        match chatbot_service
            .stream_chat(
                user.tenant_id,
                user.user_id,
                &req.message,
                req.conversation_id.as_deref(),
            )
            .await
        {
            Ok(mut token_rx) => {
                // Forward tokens from the chat service to the SSE channel
                while let Some(token_result) = token_rx.recv().await {
                    match token_result {
                        Ok(token) => {
                            sse_manager
                                .publish(&channel_clone, "token", &token)
                                .await;
                        }
                        Err(e) => {
                            sse_manager
                                .publish(&channel_clone, "error", &format!("{e}"))
                                .await;
                            break;
                        }
                    }
                }
                sse_manager.publish(&channel_clone, "done", "").await;
            }
            Err(e) => {
                sse_manager
                    .publish(&channel_clone, "error", &format!("{e}"))
                    .await;
            }
        }
    });

    // Build an SSE stream from the broadcast receiver using BroadcastStream
    let broadcast_stream = BroadcastStream::new(rx);

    // Map each broadcast item into an SSE Event, filtering out lagged items
    let event_stream = broadcast_stream.filter_map(|result| {
        match result {
            Ok(msg) => Some(Ok(Event::default().data(msg))),
            Err(_) => None, // Skip lagged/dropped messages
        }
    });

    Ok(Sse::new(event_stream))
}
