//! Chatbot route handlers.
//!
//! Provides endpoints for conversational AI:
//! - `POST /api/v1/chat` — send a message and receive a response.
//! - `POST /api/v1/chat/stream` — SSE streaming endpoint.

use axum::{
    extract::State,
    response::{
        sse::{Event, Sse},
        Json,
    },
};
use futures::stream::Stream;
use sensei_agent_core::context::Claim;
use sensei_auth::authz_snapshot::AuthzSnapshot;
use sensei_auth::middleware::AuthenticatedUser;
use sensei_core::error::Result;
use sensei_services::ai::chatbot::ChatSamplingParams;
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::convert::Infallible;
use std::pin::Pin;
use std::task::{Context, Poll};
use tokio::task::JoinHandle;
use tokio_stream::wrappers::BroadcastStream;
use tokio_stream::StreamExt;
use tracing::error;

use crate::state::AppState;

/// Request body for a chat message.
#[derive(Debug, Deserialize)]
pub struct ChatRequest {
    /// The user's message text.
    pub message: String,
    /// Optional conversation ID to continue an existing conversation.
    pub conversation_id: Option<String>,
    /// Maximum number of tokens to generate (optional).
    pub max_tokens: Option<usize>,
    /// Sampling temperature (optional, 0.0 = greedy).
    pub temperature: Option<f32>,
    /// Top-k sampling parameter (optional, 0 = disabled).
    pub top_k: Option<u32>,
    /// Top-p (nucleus) sampling parameter (optional).
    pub top_p: Option<f32>,
    /// Server-built authoritative context bundle (sixteenth audit 8/96):
    /// the Context Kernel runs BEFORE generation and this field reports
    /// the compact live context that was used. Clients may supply their
    /// own value, but the server ALWAYS overrides it with the plan-driven
    /// bundle — the model never invents the retrieval strategy.
    #[serde(default)]
    pub system_context: Option<String>,
}

impl ChatRequest {
    /// The per-request sampling overrides, if any were provided.
    fn sampling_params(&self) -> Option<ChatSamplingParams> {
        if self.max_tokens.is_none()
            && self.temperature.is_none()
            && self.top_k.is_none()
            && self.top_p.is_none()
        {
            return None;
        }
        Some(ChatSamplingParams {
            max_tokens: self.max_tokens,
            temperature: self.temperature,
            top_k: self.top_k,
            top_p: self.top_p,
        })
    }
}

/// Response body for a chat message.
#[derive(Debug, serde::Serialize)]
pub struct ChatResponseBody {
    /// The assistant's response text.
    pub response: String,
    /// Unique conversation identifier.
    pub conversation_id: String,
    /// Whether this response was generated by fallback pattern matching.
    pub is_fallback: bool,
    /// The deterministic context plan (fifteenth audit 74): the required
    /// context sections for the caller's task — the model never invents
    /// the retrieval strategy.
    #[serde(default)]
    pub context_plan: Option<sensei_agent_core::context::ContextPlan>,
    /// The deterministic verification envelope: claims about live tenant
    /// data must carry evidence; this reports whether the response is
    /// decision-grade (the legacy assistant can no longer bypass the agent
    /// verification layer).
    #[serde(default)]
    pub verification: Option<serde_json::Value>,
    /// The compact authoritative context bundle that was fed INTO
    /// generation (sixteenth audit 8/96) — what the plan required and the
    /// kernel fetched before the model saw the prompt.
    #[serde(default)]
    pub context_used: Option<Vec<String>>,
    /// Whether the request's authorization snapshot was still current at
    /// generation time (sixteenth audit 5/24): the TOCTOU guard re-checks
    /// the revision triple before the model call, so a response is only
    /// produced under the permission state it started in.
    #[serde(default)]
    pub snapshot_ok: bool,
}

/// The fully prepared inference pipeline for one chat request (eighteenth
/// audit P1-6): agent context → authorization snapshot → ContextRequest →
/// retrieval plan → compact context → typed ContextItems → kernel bundle →
/// system context. BOTH the JSON chat and the SSE stream run through this
/// SAME preparation, so the stream can no longer bypass the Context Kernel
/// or the authorization snapshot.
pub(crate) struct PreparedInference {
    /// The server-created agent context (caller scope + permissions).
    pub ctx: sensei_agent_core::context::AgentContext,
    /// The authorization snapshot captured once at request start.
    pub snapshot: Option<AuthzSnapshot>,
    /// The deterministic retrieval plan.
    pub context_plan: sensei_agent_core::context::ContextPlan,
    /// The compact authoritative context bundle — the texts fed INTO
    /// generation. The verifier matches evidence markers against these.
    pub context_used: Vec<String>,
    /// The prepared system context (the joined bundle), `None` when empty.
    pub system_context: Option<String>,
}

/// Build the FULL preparation pipeline shared by the JSON chat and the SSE
/// stream (eighteenth audit P1-6). Order: AUTHENTICATE → AUTHORIZATION
/// SNAPSHOT → TASK CLASSIFICATION → CONTEXT REQUEST → RETRIEVAL PLAN →
/// AUTHORIZED RETRIEVAL → CONTEXT BUNDLE.
///
/// The TOCTOU `is_still_current` re-check is deliberately NOT here: each
/// caller re-checks the snapshot AFTER preparation and as close to
/// generation as possible.
pub(crate) async fn prepare_inference(
    user: &AuthenticatedUser,
    state: &AppState,
    message: &str,
    conversation_id: Option<&str>,
) -> Result<PreparedInference> {
    // Context Kernel BEFORE generation (sixteenth audit 8/96): the
    // deterministic plan decides what live tenant state is retrieved —
    // the compact authoritative bundle is fed INTO the prompt, it is not
    // attached afterwards as metadata. Order: AUTHENTICATE →
    // AUTHORIZATION SNAPSHOT → TASK CLASSIFICATION → CONTEXT REQUEST →
    // RETRIEVAL PLAN → AUTHORIZED RETRIEVAL → CONTEXT BUNDLE →
    // GENERATION → CLAIM VERIFICATION → OUTPUT.
    let ctx = crate::routes::agent::build_context(user, state).await;

    // Authorization snapshot (sixteenth audit items 5/24): captured ONCE
    // at request start — the revision triple the whole request runs
    // under, salted with the caller's effective permissions. Retrieval,
    // generation and the verifier all run under THIS permission state;
    // the TOCTOU guard below re-checks it before the model call.
    let snapshot = match &state.db_pool {
        Some(pool) => {
            let revisions = sensei_services::tps::authorization_revisions::current_snapshot(
                pool,
                user.tenant_id,
            )
            .await?;
            // Deterministic digest of the sorted effective permissions
            // (same resolution as HTTP authorization and build_context):
            // any role change shifts the digest, so it cannot collide
            // across distinct permission sets.
            let rbac = sensei_auth::rbac::authorization_service();
            let mut perms: Vec<String> = user
                .roles
                .iter()
                .flat_map(|role| rbac.permissions_for_role_in_tenant(user.tenant_id, role))
                .collect();
            perms.sort();
            perms.dedup();
            let mut hasher = Sha256::new();
            for p in &perms {
                hasher.update(p.as_bytes());
            }
            Some(AuthzSnapshot {
                tenant: user.tenant_id,
                principal: user.user_id,
                roles: user.roles.clone(),
                policy_revision: revisions.policy_revision,
                relationship_revision: revisions.relationship_revision,
                principal_revision: revisions.principal_revision,
                scope_site: ctx.site_id,
                permission_digest: hasher.finalize().into(),
            })
        }
        None => None,
    };
    // Fifteenth audit (6-8/74): EVERY AI operation goes through the
    // Context Kernel — the deterministic plan (task decides the required
    // context sections BEFORE any retrieval). The model never invents the
    // retrieval strategy.
    let context_request = sensei_agent_core::context::ContextRequest {
        principal_id: user.user_id,
        roles: user.roles.clone(),
        site_id: ctx.site_id,
        value_stream_id: ctx.value_stream_id,
        work_center_id: ctx.work_center_id,
        task: classify_task(message),
        focal_objects: Vec::new(),
        max_tokens: 4096,
        sensitivity_ceiling: sensei_agent_core::context::DataClass::Internal,
        trace_id: conversation_id.unwrap_or_default().to_string(),
    };
    let context_plan = sensei_agent_core::context::plan_context(&context_request);
    // Seventeenth audit item 7: the live chat runs through the ACTUAL
    // Context Kernel. The section lines are wrapped in typed ContextItems
    // (provenance = the section source, authority = live transactional
    // state, sensitivity = Internal, epistemic = RecordedFact) and
    // build_context_bundle applies the REAL kernel semantics: FactAddress
    // contradiction handling, authority ordering, provenance-based
    // selection, sensitivity filtering and the normal-budget token
    // allocation with the reserved contradiction budget.
    let context_used = match &state.db_pool {
        Some(pool) => {
            sensei_services::tps::context_sections::build_compact_context(
                pool,
                user.tenant_id,
                ctx.site_id,
                ctx.work_center_id,
                &context_plan,
            )
            .await
        }
        None => Vec::new(),
    };
    let kernel_items: Vec<sensei_agent_core::context::ContextItem> = context_used
        .iter()
        .filter_map(|line| {
            let (section, content) = line.split_once(" [live]: ")?;
            Some(sensei_agent_core::context::ContextItem {
                payload: serde_json::json!({ "section": section, "text": content }),
                provenance: sensei_agent_core::context::Provenance {
                    source: format!("section:{section}"),
                    source_revision: None,
                    observed_at: Some(chrono::Utc::now()),
                    recorded_at: chrono::Utc::now(),
                    authority: sensei_agent_core::context::AuthorityRank::TransactionalState,
                },
                sensitivity: sensei_agent_core::context::DataClass::Internal,
                token_cost: (content.len() as u32 / 4).max(1),
                epistemic_status: sensei_agent_core::context::EpistemicStatus::RecordedFact,
            })
        })
        .collect();
    let kernel_bundle = sensei_agent_core::context_kernel::build_context_bundle(
        &context_request,
        kernel_items,
        sensei_agent_core::context::TokenBudget::default_for(4096),
    );
    let context_used: Vec<String> = kernel_bundle
        .sections
        .iter()
        .flat_map(|(_, items)| {
            items.iter().map(|item| {
                item.payload
                    .get("text")
                    .and_then(|t| t.as_str())
                    .unwrap_or("")
                    .to_string()
            })
        })
        .collect();
    let system_context = if context_used.is_empty() {
        None
    } else {
        Some(context_used.join("\n"))
    };

    Ok(PreparedInference {
        ctx,
        snapshot,
        context_plan,
        context_used,
        system_context,
    })
}

/// Handle a single-turn chat message.
///
/// Returns a JSON response with the assistant's reply.
pub async fn chat(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<ChatRequest>,
) -> Result<Json<ChatResponseBody>> {
    user.require_permission("ai:inference")?;

    // Eighteenth audit P1-6: the FULL Context Kernel preparation is shared
    // with the SSE stream — agent context → authorization snapshot →
    // ContextRequest → plan → compact context → typed ContextItems →
    // kernel bundle → prepared system context.
    let prepared =
        prepare_inference(&user, &state, &req.message, req.conversation_id.as_deref()).await?;

    // TOCTOU guard (sixteenth audit items 5/24): the permission state
    // must NOT have moved between snapshot capture and generation — if
    // any revision bumped (a revocation landed mid-request), the request
    // is refused and must be re-authorized, never executed under a stale
    // state. No snapshot (no DB pool) = fail closed: an unverifiable
    // request is not executed. The check stays HERE, after preparation
    // and immediately before the model call.
    let snapshot_ok = match (&state.db_pool, &prepared.snapshot) {
        (Some(pool), Some(snap)) => snap.is_still_current(pool).await,
        _ => false,
    };
    if !snapshot_ok {
        return Err(sensei_core::error::SenseiError::Forbidden(
            "authorization state changed during the request — re-authorized and retry".to_string(),
        ));
    }

    let response = state
        .chatbot_service
        .chat(
            user.tenant_id,
            user.user_id,
            &req.message,
            req.conversation_id.as_deref(),
            req.sampling_params(),
            prepared.system_context.as_deref(),
        )
        .await
        .map_err(|e| {
            error!(error = %e, "Chatbot chat failed");
            e
        })?;

    // Item 22: the legacy chat surface flows through the SAME agent
    // control plane as the tool surface — server-created context, the
    // effective (policy-filtered) toolset and the deterministic verifier.
    // The assistant can no longer answer with unverifiable tenant claims:
    // every response is checked against the caller's real permissions and
    // the tool contract.
    let policy = sensei_agent_core::tools::PolicyEngine::new(
        crate::services::agent::build_readonly_tools(),
        sensei_agent_core::tools::ToolRisk::ReadOnly,
    );
    let effective_tools = policy.effective_tools(&prepared.ctx);
    let verification = verify_chat_response(
        &response,
        &prepared.ctx,
        &policy,
        &effective_tools,
        &prepared.context_used,
    );
    // Seventeenth audit item 7 — verifier failure BLOCKS/REPAIRS output:
    // an unverifiable factual reply is never delivered as-is. The
    // content is REPAIRED into an honest answer that does not assert the
    // unverified claims (the client sees verdict 'repaired' with the
    // original issues).
    let (final_content, verdict_label) = if verification["verdict"].as_str() == Some("pass") {
        (response.message.content, "pass".to_string())
    } else {
        let issue_count = verification["issues"]
            .as_array()
            .map(|a| a.len())
            .unwrap_or(0);
        (repair_message(issue_count), "repaired".to_string())
    };
    let mut verification_out = verification;
    if verdict_label == "repaired" {
        verification_out["verdict"] = serde_json::json!("repaired");
    }
    Ok(Json(ChatResponseBody {
        response: final_content,
        conversation_id: response.conversation_id,
        is_fallback: response.is_fallback,
        verification: Some(verification_out),
        context_plan: Some(prepared.context_plan),
        context_used: Some(prepared.context_used),
        snapshot_ok: true,
    }))
}

/// The honest repair text released when verification fails (eighteenth
/// audit P1-6): the JSON chat and the SSE stream publish THE SAME repaired
/// answer — the raw buffered reply with unverified claims is never
/// delivered.
fn repair_message(issue_count: usize) -> String {
    format!(
        "I can only answer with claims verified against the plant systems.              The previous reply contained statements I could not verify against              live tenant data ({issue_count} issue(s)). Ask me to query a specific metric,              work order, quality record or andon through the tool surface."
    )
}

/// Deterministic task classification (seventeenth audit item 7): the
/// message selects the Context Kernel task instead of hardcoding
/// TaskKind::General — the plan (and therefore the retrieved sections)
/// follows the operational intent.
fn classify_task(message: &str) -> sensei_agent_core::context::TaskKind {
    use sensei_agent_core::context::TaskKind;
    let lower = message.to_lowercase();
    if lower.contains("andon")
        || lower.contains("escalat")
        || lower.contains("contain")
        || lower.contains("safety")
    {
        TaskKind::OperatorAssist
    } else if lower.contains("quality")
        || lower.contains("ncr")
        || lower.contains("capa")
        || lower.contains("defect")
        || lower.contains("inspection")
    {
        TaskKind::QualityInvestigation
    } else if lower.contains("schedule")
        || lower.contains("plan")
        || lower.contains("takt")
        || lower.contains("pitch")
        || lower.contains("demand")
    {
        TaskKind::PlannerDecision
    } else if lower.contains("executive")
        || lower.contains("summary")
        || lower.contains("trend")
        || lower.contains("dashboard")
        || lower.contains("kpi")
        || lower.contains("metric")
        || lower.contains("overview")
    {
        TaskKind::ExecutiveAnalysis
    } else if lower.contains("fix")
        || lower.contains("error")
        || lower.contains("why")
        || lower.contains("fault")
        || lower.contains("broken")
    {
        TaskKind::Troubleshoot
    } else {
        TaskKind::General
    }
}

/// Run the REAL claims/evidence verifier over the assistant's reply
/// (item 25): every sentence that states a FACT about live tenant data
/// must carry evidence. The previous loop inspected only the (already
/// permitted) effective toolset, which by construction always passed.
/// Now: factual-sounding statements become ObservedFact claims WITHOUT
/// evidence refs, and the deterministic verifier flags them — the same
/// contract the tool surface enforces.
///
/// Eighteenth audit P1-7: the output is STRUCTURED — every flagged
/// sentence becomes a [`Claim`] ("unverified" without evidence; "measured"
/// when an `[evidence: <source>]` marker matches a prepared context
/// source). The marker check runs against the CURRENT sentence, never the
/// whole response.
fn verify_chat_response(
    response: &sensei_services::ai::chatbot::ChatResponse,
    ctx: &sensei_agent_core::context::AgentContext,
    _policy: &sensei_agent_core::tools::PolicyEngine,
    _effective_tools: &[&sensei_agent_core::tools::ToolSpec],
    context_used: &[String],
) -> serde_json::Value {
    let mut issues: Vec<String> = Vec::new();
    let mut claims: Vec<Claim> = Vec::new();
    let content = response.message.content.clone();

    // Factual-sounding statements: sentences that mention live tenant data
    // (quantities, counts, statuses, ids) in an assertive way. These are
    // ObservedFact claims and REQUIRE evidence — the assistant produced
    // none here, so they are violations.
    let factual_markers = [
        "is ",
        "are ",
        "stands at ",
        "currently ",
        "has ",
        "there are ",
        "total ",
        "count ",
        "units ",
        "inventory",
        "ncr",
        "capa",
        "andon",
        "work order",
        "production",
        "quality",
        "defect",
        "scrap",
    ];
    for sentence in split_sentences(&content) {
        let s = sentence.trim();
        if s.len() < 12 {
            continue;
        }
        // Eighteenth audit P1-7: the marker check runs against the CURRENT
        // sentence's lowercased text — the previous implementation checked
        // the WHOLE response, so one marker in a single sentence flagged
        // every numeric sentence in the reply.
        let sentence_lower = s.to_lowercase();
        let has_number = s.chars().any(|c| c.is_ascii_digit());
        let mentions_data = factual_markers.iter().any(|m| sentence_lower.contains(m));
        if !(has_number && mentions_data) {
            continue;
        }

        // Evidence markers: "[evidence: <source>]" — when the referenced
        // source appears in the prepared context bundle, the sentence is a
        // MEASURED claim and is NOT flagged; otherwise it stays unverified.
        let evidence_refs = evidence_refs_in(s);
        let matched_refs: Vec<String> = evidence_refs
            .iter()
            .filter(|r| context_used.iter().any(|line| line.contains(r.as_str())))
            .cloned()
            .collect();
        if !matched_refs.is_empty() {
            claims.push(Claim {
                statement: s.to_string(),
                epistemic_status: "measured".to_string(),
                fact_addresses: Vec::new(),
                evidence_refs: matched_refs,
                confidence: None,
                valid_at: None,
            });
            continue;
        }
        claims.push(Claim {
            statement: s.to_string(),
            epistemic_status: "unverified".to_string(),
            fact_addresses: Vec::new(),
            evidence_refs: Vec::new(),
            confidence: None,
            valid_at: None,
        });
        if !response.is_fallback {
            issues.push(format!(
                "Unverified factual claim: '{s}' — no EvidenceRef. \
                 Facts about live tenant data must be queried through the \
                 tool surface, stated as unavailable, or labeled a hypothesis."
            ));
        }
    }

    if response.is_fallback {
        issues.push(
            "Fallback/general answer — not grounded in tenant evidence; \
             treat as guidance, not as a validated fact."
                .to_string(),
        );
    }

    // The context is SERVER-CREATED: the caller's effective scope is
    // attached so the client can see WHERE the answer applies.
    let verdict = if issues.is_empty() {
        "pass"
    } else {
        "needs_evidence"
    };
    serde_json::json!({
        "verdict": verdict,
        "issues": issues,
        "claims": claims,
        "claims_checked": claims.len(),
        "context": {
            "site_id": ctx.site_id,
            "value_stream_id": ctx.value_stream_id,
            "work_center_id": ctx.work_center_id,
            "shift_id": ctx.shift_id,
        },
    })
}

/// Split a reply into sentences on `.` (only when followed by whitespace
/// or end of input), `;` and newlines. A dot inside an evidence ref such
/// as "[evidence: metric.process_yield_proxy@Bizerte]" is NOT a sentence
/// boundary — the ref must survive as one token (eighteenth audit P1-7).
fn split_sentences(content: &str) -> Vec<String> {
    let mut sentences = Vec::new();
    let bytes = content.as_bytes();
    let mut start = 0;
    for (i, b) in bytes.iter().enumerate() {
        let is_boundary = match b {
            b'.' => i + 1 >= bytes.len() || bytes[i + 1].is_ascii_whitespace(),
            b';' | b'\n' => true,
            _ => false,
        };
        if is_boundary {
            if i > start {
                sentences.push(content[start..i].to_string());
            }
            start = i + 1;
            while start < bytes.len() && bytes[start].is_ascii_whitespace() {
                start += 1;
            }
        }
    }
    if start < bytes.len() {
        sentences.push(content[start..].to_string());
    }
    sentences
}

/// Extract the evidence sources referenced by a sentence, e.g.
/// "[evidence: metric.process_yield_proxy@Bizerte]" →
/// "metric.process_yield_proxy@Bizerte". Deterministic and
/// order-preserving.
fn evidence_refs_in(sentence: &str) -> Vec<String> {
    let mut refs = Vec::new();
    let mut rest = sentence;
    while let Some(start) = rest.find("[evidence:") {
        let after = &rest[start + "[evidence:".len()..];
        let Some(end) = after.find(']') else { break };
        let inner = after[..end].trim();
        if !inner.is_empty() {
            refs.push(inner.to_string());
        }
        rest = &after[end + 1..];
    }
    refs
}

/// Stream wrapper that aborts a background task when the stream is dropped.
///
/// The chat generation task is aborted as soon as the client disconnects
/// (the HTTP response body — and therefore this stream — is dropped), so a
/// disconnected client never leaves a generation task running.
struct AbortOnDrop<S> {
    inner: S,
    task: Option<JoinHandle<()>>,
}

impl<S> Drop for AbortOnDrop<S> {
    fn drop(&mut self) {
        if let Some(task) = self.task.take() {
            task.abort();
        }
    }
}

impl<S: Stream + Unpin> Stream for AbortOnDrop<S> {
    type Item = S::Item;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Pin::new(&mut self.inner).poll_next(cx)
    }
}

/// Handle a streaming chat message via Server-Sent Events.
///
/// Returns an SSE stream where each event contains a token (or chunk) of the
/// response. The background generation task is aborted when the client
/// disconnects.
pub async fn chat_stream(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<ChatRequest>,
) -> Result<Sse<impl Stream<Item = std::result::Result<Event, Infallible>>>> {
    user.require_permission("ai:inference")?;
    let sse_manager = state.sse_manager.clone();
    let chatbot_service = state.chatbot_service.clone();

    // Eighteenth audit P1-6: the stream runs through the SAME Context
    // Kernel preparation as the JSON chat — agent context, authorization
    // snapshot, deterministic plan and the prepared context bundle. The
    // stream can no longer bypass the kernel or the snapshot.
    let prepared =
        prepare_inference(&user, &state, &req.message, req.conversation_id.as_deref()).await?;

    // TOCTOU guard (sixteenth audit items 5/24): the permission state must
    // NOT have moved between snapshot capture and streaming — checked
    // BEFORE the stream task starts. No snapshot (no DB pool) = fail
    // closed: an unverifiable stream is never started.
    let snapshot_ok = match (&state.db_pool, &prepared.snapshot) {
        (Some(pool), Some(snap)) => snap.is_still_current(pool).await,
        _ => false,
    };

    // Generate a unique channel name for this streaming session
    let channel = format!("chat-{}", uuid::Uuid::new_v4());

    // Subscribe to the channel before spawning the background task
    let rx = sse_manager.subscribe(&channel).await;

    // Spawn a background task to run the streaming chat
    let channel_clone = channel.clone();
    let sampling = req.sampling_params();
    let system_context = prepared.system_context.clone();
    let context_used = prepared.context_used.clone();
    let ctx = prepared.ctx.clone();
    let task = tokio::spawn(async move {
        // The snapshot gate decides whether streaming may START at all
        // (eighteenth audit P1-6): a stale snapshot publishes an error
        // event and returns — generation never starts.
        if !snapshot_ok {
            sse_manager
                .publish(
                    &channel_clone,
                    "error",
                    "authorization state changed during the request — re-authorized and retry",
                )
                .await;
            return;
        }
        // The PREPARED context travels with the stream: `stream_chat` has
        // no context parameter, so the authoritative bundle is published
        // as the first "context" event BEFORE any token, and logged. The
        // buffered reply is verified against the same bundle below.
        if let Some(sys) = system_context.as_deref() {
            tracing::info!(
                channel = %channel_clone,
                context = %sys,
                "SSE chat streaming with prepared Context Kernel bundle"
            );
            sse_manager.publish(&channel_clone, "context", sys).await;
        }
        // Item 26: the stream carries the SAME trust guarantee as the JSON
        // chat — the full response is buffered, verified, and only then
        // released with its verification envelope.
        match chatbot_service
            .stream_chat(
                user.tenant_id,
                user.user_id,
                &req.message,
                req.conversation_id.as_deref(),
                sampling,
            )
            .await
        {
            Ok(mut token_rx) => {
                // BUFFER the full reply, then run the same claims/evidence
                // verification as the JSON chat (item 26) — the stream can
                // no longer bypass the trust contract.
                let mut buffered = String::new();
                let mut stream_error: Option<String> = None;
                while let Some(token_result) = token_rx.recv().await {
                    match token_result {
                        Ok(token) => buffered.push_str(&token),
                        Err(e) => {
                            stream_error = Some(e.to_string());
                            break;
                        }
                    }
                }
                if let Some(e) = stream_error {
                    sse_manager.publish(&channel_clone, "error", &e).await;
                    return;
                }
                // Verify the buffered reply as an ordinary ChatResponse,
                // against the PREPARED context bundle.
                let chat_response = sensei_services::ai::chatbot::ChatResponse {
                    message: sensei_services::ai::chatbot::ChatMessage {
                        role: "assistant".to_string(),
                        content: buffered.clone(),
                        timestamp: chrono::Utc::now(),
                    },
                    conversation_id: req.conversation_id.clone().unwrap_or_default(),
                    is_fallback: buffered.is_empty(),
                };
                let policy = sensei_agent_core::tools::PolicyEngine::new(
                    crate::services::agent::build_readonly_tools(),
                    sensei_agent_core::tools::ToolRisk::ReadOnly,
                );
                let effective_tools = policy.effective_tools(&ctx);
                let mut verification = verify_chat_response(
                    &chat_response,
                    &ctx,
                    &policy,
                    &effective_tools,
                    &context_used,
                );
                // Seventeenth audit item 7 (extended by eighteenth audit
                // P1-6): the stream's buffered reply is REPAIRED when
                // verification fails — the stream releases THE SAME repair
                // message as the JSON path, never the raw buffered reply.
                let released = if verification["verdict"].as_str() == Some("pass") {
                    buffered.clone()
                } else {
                    let issue_count = verification["issues"]
                        .as_array()
                        .map(|a| a.len())
                        .unwrap_or(0);
                    verification["verdict"] = serde_json::json!("repaired");
                    repair_message(issue_count)
                };
                // Release tokens only after verification completed.
                sse_manager
                    .publish(&channel_clone, "token", &released)
                    .await;
                sse_manager
                    .publish(
                        &channel_clone,
                        "verification",
                        &serde_json::to_string(&verification).unwrap_or_default(),
                    )
                    .await;
                sse_manager.publish(&channel_clone, "done", "").await;
            }
            Err(e) => {
                sse_manager
                    .publish(&channel_clone, "error", &format!("{e}"))
                    .await;
            }
        }
    });

    // Build an SSE stream from the broadcast receiver using BroadcastStream
    let broadcast_stream = BroadcastStream::new(rx);

    // Map each broadcast item into an SSE Event, filtering out lagged items
    let event_stream = broadcast_stream.filter_map(|result| {
        match result {
            Ok(msg) => Some(Ok(Event::default().data(msg))),
            Err(_) => None, // Skip lagged/dropped messages
        }
    });

    // Dropping this stream (client disconnect) aborts the generation task.
    let abort_on_drop = AbortOnDrop {
        inner: event_stream,
        task: Some(task),
    };

    Ok(Sse::new(abort_on_drop))
}

#[cfg(test)]
mod tests {
    use super::*;
    use sensei_agent_core::context::AgentContext;

    fn test_ctx() -> AgentContext {
        AgentContext {
            tenant_id: uuid::Uuid::new_v4(),
            user_id: uuid::Uuid::new_v4(),
            session_id: None,
            site_id: None,
            value_stream_id: None,
            work_center_id: None,
            shift_id: None,
            roles: vec![],
            permissions: std::collections::HashSet::new(),
            locale: "en".to_string(),
            timezone: "UTC".to_string(),
            request_id: uuid::Uuid::new_v4(),
            conversation_id: None,
        }
    }

    fn response_with(content: &str) -> sensei_services::ai::chatbot::ChatResponse {
        sensei_services::ai::chatbot::ChatResponse {
            message: sensei_services::ai::chatbot::ChatMessage::assistant(content.to_string()),
            conversation_id: "conv".to_string(),
            is_fallback: false,
        }
    }

    fn verify(content: &str, context_used: &[String]) -> serde_json::Value {
        let policy = sensei_agent_core::tools::PolicyEngine::new(
            crate::services::agent::build_readonly_tools(),
            sensei_agent_core::tools::ToolRisk::ReadOnly,
        );
        let tools = policy.effective_tools(&test_ctx());
        verify_chat_response(
            &response_with(content),
            &test_ctx(),
            &policy,
            &tools,
            context_used,
        )
    }

    #[test]
    fn verifier_flags_unverified_factual_claims() {
        let v = verify("Line 12 currently stands at 42 units of inventory.", &[]);
        assert_eq!(v["verdict"], "needs_evidence");
        let claims: Vec<Claim> = serde_json::from_value(v["claims"].clone()).unwrap();
        assert_eq!(claims.len(), 1);
        assert_eq!(claims[0].epistemic_status, "unverified");
        assert!(claims[0].evidence_refs.is_empty());
        assert_eq!(v["claims_checked"], 1);
    }

    #[test]
    fn verifier_marks_measured_claims_with_matching_context_evidence() {
        let context = vec!["metric.process_yield_proxy@Bizerte: 42".to_string()];
        let v = verify(
            "Line 12 currently stands at 42 units [evidence: metric.process_yield_proxy@Bizerte].",
            &context,
        );
        assert_eq!(v["verdict"], "pass");
        let claims: Vec<Claim> = serde_json::from_value(v["claims"].clone()).unwrap();
        assert_eq!(claims[0].epistemic_status, "measured");
        assert_eq!(
            claims[0].evidence_refs,
            vec!["metric.process_yield_proxy@Bizerte".to_string()]
        );
    }

    #[test]
    fn verifier_does_not_flag_sentences_without_markers() {
        // Regression (P1-7): the marker check must run against the CURRENT
        // sentence — "Production is running." (no digits) must not cause
        // "Delivery will arrive in 30 days." (digit, no marker) to be
        // flagged. The previous whole-response check flagged it.
        let v = verify(
            "Production is running. Delivery will arrive in 30 days.",
            &[],
        );
        assert_eq!(v["verdict"], "pass");
        let claims: Vec<Claim> = serde_json::from_value(v["claims"].clone()).unwrap();
        assert!(claims.is_empty());
    }

    #[test]
    fn verifier_flags_evidence_marker_not_in_context() {
        let v = verify(
            "Line 12 currently stands at 42 units [evidence: nope.missing@nowhere].",
            &["real source line".to_string()],
        );
        assert_eq!(v["verdict"], "needs_evidence");
        let claims: Vec<Claim> = serde_json::from_value(v["claims"].clone()).unwrap();
        assert_eq!(claims[0].epistemic_status, "unverified");
    }

    #[test]
    fn evidence_refs_in_extracts_markers() {
        assert_eq!(
            evidence_refs_in(
                "yield is 42 [evidence: metric.process_yield_proxy@Bizerte] [evidence: second.ref]."
            ),
            vec![
                "metric.process_yield_proxy@Bizerte".to_string(),
                "second.ref".to_string()
            ]
        );
        assert!(evidence_refs_in("no markers here").is_empty());
    }

    #[test]
    fn split_sentences_keeps_evidence_refs_intact() {
        assert_eq!(
            split_sentences(
                "Yield is 42 [evidence: metric.process_yield_proxy@Bizerte]. And it is rising."
            ),
            vec![
                "Yield is 42 [evidence: metric.process_yield_proxy@Bizerte]".to_string(),
                "And it is rising".to_string()
            ]
        );
        assert_eq!(
            split_sentences("a. b; c\nd"),
            vec![
                "a".to_string(),
                "b".to_string(),
                "c".to_string(),
                "d".to_string()
            ]
        );
    }

    #[test]
    fn repair_message_is_shared_between_json_and_stream() {
        let msg = repair_message(3);
        assert!(msg.contains("I can only answer with claims verified"));
        assert!(msg.contains("3 issue(s)"));
    }
}
