//! MRP (Material Requirements Planning) route handlers.
//!
//! Provides endpoints for managing demand entries, planned supply orders,
//! and running MRP calculations.

use axum::{Json, extract::{Path, Query, State}};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sensei_auth::middleware::AuthenticatedUser;
use sensei_core::error::{Result, SenseiError};
use sensei_core::pagination::PaginatedResponse;
use sensei_core::types::new_id;
use uuid::Uuid;

use crate::state::AppState;
use crate::stores::{DemandEntry, MrpRun, SupplyOrder};

// ── Query / Request DTOs ───────────────────────────────────────────────────

/// Query parameters for listing demand entries.
#[derive(Debug, Deserialize)]
pub struct ListDemandParams {
    pub product_id: Option<Uuid>,
    pub source_type: Option<String>,
    pub date_from: Option<String>,
    pub date_to: Option<String>,
    pub page: Option<usize>,
    pub per_page: Option<usize>,
}

/// Request body for creating a demand entry.
#[derive(Debug, Deserialize)]
pub struct CreateDemandRequest {
    pub product_id: Uuid,
    pub product_name: String,
    pub quantity: f64,
    pub due_date: String,
    pub source_type: String,
    pub source_id: Option<Uuid>,
    pub notes: String,
}

/// Query parameters for listing supply orders.
#[derive(Debug, Deserialize)]
pub struct ListSupplyParams {
    pub product_id: Option<Uuid>,
    pub status: Option<String>,
    pub page: Option<usize>,
    pub per_page: Option<usize>,
}

/// Request body for triggering an MRP run.
#[derive(Debug, Deserialize)]
pub struct RunMrpRequest {
    pub run_type: String,
}

/// A planned order generated by the MRP run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedOrder {
    pub product_id: Uuid,
    pub product_name: String,
    pub required_quantity: f64,
    pub on_hand: f64,
    pub net_requirement: f64,
    pub suggested_order_quantity: f64,
    pub suggested_order_date: String,
    pub expected_delivery: String,
}

/// MRP run detail including planned orders.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MrpRunDetail {
    pub run: MrpRun,
    pub planned_orders: Vec<PlannedOrder>,
}

// ── Demand Entries ─────────────────────────────────────────────────────────

/// List demand entries with optional filters.
pub async fn list_demand(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Query(params): Query<ListDemandParams>,
) -> Result<Json<PaginatedResponse<DemandEntry>>> {
    let tenant_id = user.tenant_id;
    let store = state.demand_entries.read().await;
    let mut entries: Vec<DemandEntry> = store
        .values()
        .filter(|d| d.tenant_id == tenant_id)
        .filter(|d| {
            if let Some(pid) = &params.product_id {
                d.product_id == *pid
            } else {
                true
            }
        })
        .filter(|d| {
            if let Some(ref st) = params.source_type {
                d.source_type == *st
            } else {
                true
            }
        })
        .cloned()
        .collect();
    entries.sort_by(|a, b| a.due_date.cmp(&b.due_date));
    let result = PaginatedResponse::new(entries, params.page, params.per_page);
    Ok(Json(result))
}

/// Create a new demand entry.
pub async fn create_demand(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<CreateDemandRequest>,
) -> Result<Json<DemandEntry>> {
    let tenant_id = user.tenant_id;
    let now = Utc::now();
    let due_date = DateTime::parse_from_rfc3339(&req.due_date)
        .map_err(|e| SenseiError::Validation(format!("Invalid due_date: {e}")))?
        .with_timezone(&Utc);

    let entry = DemandEntry {
        id: new_id(),
        tenant_id,
        product_id: req.product_id,
        product_name: req.product_name,
        quantity: req.quantity,
        due_date,
        source_type: req.source_type,
        source_id: req.source_id,
        notes: req.notes,
        created_by: user.user_id,
        created_at: now,
        updated_at: now,
    };
    let mut store = state.demand_entries.write().await;
    store.insert(entry.id, entry.clone());
    Ok(Json(entry))
}

// ── Supply Orders ──────────────────────────────────────────────────────────

/// List planned supply orders with optional filters.
pub async fn list_supply(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Query(params): Query<ListSupplyParams>,
) -> Result<Json<PaginatedResponse<SupplyOrder>>> {
    let tenant_id = user.tenant_id;
    let store = state.supply_orders.read().await;
    let mut orders: Vec<SupplyOrder> = store
        .values()
        .filter(|o| o.tenant_id == tenant_id)
        .filter(|o| {
            if let Some(pid) = &params.product_id {
                o.product_id == *pid
            } else {
                true
            }
        })
        .filter(|o| {
            if let Some(ref status) = params.status {
                o.status == *status
            } else {
                true
            }
        })
        .cloned()
        .collect();
    orders.sort_by(|a, b| a.order_date.cmp(&b.order_date));
    let result = PaginatedResponse::new(orders, params.page, params.per_page);
    Ok(Json(result))
}

// ── MRP Run ────────────────────────────────────────────────────────────────

/// Trigger an MRP run (net requirements calculation).
pub async fn run_mrp(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<RunMrpRequest>,
) -> Result<Json<MrpRunDetail>> {
    let tenant_id = user.tenant_id;
    let now = Utc::now();

    // Gather demand entries for this tenant
    let demand_store = state.demand_entries.read().await;
    let demands: Vec<&DemandEntry> = demand_store
        .values()
        .filter(|d| d.tenant_id == tenant_id)
        .collect();

    // Gather inventory on-hand for relevant products
    let inv_store = state.inventory_items.read().await;

    // Calculate planned orders
    let mut planned_orders: Vec<PlannedOrder> = Vec::new();
    for demand in &demands {
        let on_hand = inv_store
            .values()
            .find(|i| i.tenant_id == tenant_id && i.sku == demand.product_id.to_string())
            .map(|i| i.quantity_on_hand)
            .unwrap_or(0.0);

        let net_requirement = (demand.quantity - on_hand).max(0.0);
        let suggested_qty = if net_requirement > 0.0 {
            // Round up to nearest whole unit
            (net_requirement).ceil()
        } else {
            0.0
        };

        planned_orders.push(PlannedOrder {
            product_id: demand.product_id,
            product_name: demand.product_name.clone(),
            required_quantity: demand.quantity,
            on_hand,
            net_requirement,
            suggested_order_quantity: suggested_qty,
            suggested_order_date: now.to_rfc3339(),
            expected_delivery: demand.due_date.to_rfc3339(),
        });
    }

    let run_id = new_id();
    let mrp_run = MrpRun {
        id: run_id,
        tenant_id,
        run_type: req.run_type,
        status: "completed".to_string(),
        started_at: now,
        completed_at: Some(now),
        summary: serde_json::json!({
            "total_demand_entries": demands.len(),
            "total_planned_orders": planned_orders.len(),
            "total_net_requirement": planned_orders.iter().map(|p| p.net_requirement).sum::<f64>(),
        }),
        created_by: user.user_id,
    };

    let mut run_store = state.mrp_runs.write().await;
    run_store.insert(run_id, mrp_run.clone());

    // Create supply orders from planned orders
    let mut supply_store = state.supply_orders.write().await;
    for po in &planned_orders {
        if po.suggested_order_quantity > 0.0 {
            let order_date = now;
            let delivery_date = DateTime::parse_from_rfc3339(&po.expected_delivery)
                .unwrap_or_else(|_| now.into())
                .with_timezone(&Utc);

            let supply = SupplyOrder {
                id: new_id(),
                tenant_id,
                product_id: po.product_id,
                product_name: po.product_name.clone(),
                quantity: po.suggested_order_quantity,
                order_date,
                expected_delivery: delivery_date,
                status: "planned".to_string(),
                notes: format!("Generated by MRP run {}", run_id),
                created_by: user.user_id,
                created_at: now,
                updated_at: now,
            };
            supply_store.insert(supply.id, supply);
        }
    }

    let detail = MrpRunDetail {
        run: mrp_run,
        planned_orders,
    };
    Ok(Json(detail))
}

/// List MRP run history.
pub async fn list_mrp_runs(
    user: AuthenticatedUser,
    State(state): State<AppState>,
) -> Result<Json<Vec<MrpRun>>> {
    let tenant_id = user.tenant_id;
    let store = state.mrp_runs.read().await;
    let mut runs: Vec<MrpRun> = store
        .values()
        .filter(|r| r.tenant_id == tenant_id)
        .cloned()
        .collect();
    runs.sort_by(|a, b| b.started_at.cmp(&a.started_at));
    Ok(Json(runs))
}

/// Get MRP run detail with planned orders.
pub async fn get_mrp_run(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
) -> Result<Json<MrpRunDetail>> {
    let tenant_id = user.tenant_id;
    let store = state.mrp_runs.read().await;
    let run = store
        .values()
        .find(|r| r.id == id && r.tenant_id == tenant_id)
        .cloned()
        .ok_or_else(|| SenseiError::NotFound(format!("MRP run {id} not found")))?;

    // Gather planned orders from the supply orders store
    let supply_store = state.supply_orders.read().await;
    let planned_orders: Vec<PlannedOrder> = supply_store
        .values()
        .filter(|o| o.tenant_id == tenant_id && o.notes.contains(&id.to_string()))
        .map(|o| PlannedOrder {
            product_id: o.product_id,
            product_name: o.product_name.clone(),
            required_quantity: o.quantity,
            on_hand: 0.0,
            net_requirement: o.quantity,
            suggested_order_quantity: o.quantity,
            suggested_order_date: o.order_date.to_rfc3339(),
            expected_delivery: o.expected_delivery.to_rfc3339(),
        })
        .collect();

    let detail = MrpRunDetail {
        run,
        planned_orders,
    };
    Ok(Json(detail))
}
