//! MRP (Material Requirements Planning) route handlers.
//!
//! Provides endpoints for managing demand entries, planned supply orders,
//! and running MRP calculations.

use axum::{
    extract::{Path, Query, State},
    Json,
};
use chrono::{DateTime, Utc};
use sensei_auth::middleware::AuthenticatedUser;
use sensei_core::error::{Result, SenseiError};
use sensei_core::pagination::PaginatedResponse;
use sensei_core::types::new_id;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::state::AppState;
use crate::stores::{DemandEntry, MrpRun, SupplyOrder};

// ── Query / Request DTOs ───────────────────────────────────────────────────

/// Query parameters for listing demand entries.
#[derive(Debug, Deserialize)]
pub struct ListDemandParams {
    pub product_id: Option<Uuid>,
    pub source_type: Option<String>,
    pub date_from: Option<String>,
    pub date_to: Option<String>,
    pub page: Option<usize>,
    pub per_page: Option<usize>,
}

/// Request body for creating a demand entry.
#[derive(Debug, Deserialize)]
pub struct CreateDemandRequest {
    pub product_id: Uuid,
    pub product_name: String,
    pub quantity: f64,
    pub due_date: String,
    pub source_type: String,
    pub source_id: Option<Uuid>,
    pub notes: String,
}

/// Query parameters for listing supply orders.
#[derive(Debug, Deserialize)]
pub struct ListSupplyParams {
    pub product_id: Option<Uuid>,
    pub status: Option<String>,
    pub page: Option<usize>,
    pub per_page: Option<usize>,
}

/// Request body for triggering an MRP run.
#[derive(Debug, Deserialize)]
pub struct RunMrpRequest {
    pub run_type: String,
}

/// A planned order generated by the MRP run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedOrder {
    pub product_id: Uuid,
    pub product_name: String,
    pub required_quantity: f64,
    pub on_hand: f64,
    pub net_requirement: f64,
    pub suggested_order_quantity: f64,
    pub suggested_order_date: String,
    pub expected_delivery: String,
}

/// MRP run detail including planned orders.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MrpRunDetail {
    pub run: MrpRun,
    pub planned_orders: Vec<PlannedOrder>,
}

/// Parse an RFC 3339 date filter; invalid values are rejected with a 400
/// instead of silently disabling the filter.
fn parse_date_filter(name: &str, value: Option<&str>) -> Result<Option<DateTime<Utc>>> {
    match value {
        Some(raw) => DateTime::parse_from_rfc3339(raw)
            .map(|dt| Some(dt.with_timezone(&Utc)))
            .map_err(|e| {
                SenseiError::Validation(format!("Invalid {name} (expected RFC 3339): {e}"))
            }),
        None => Ok(None),
    }
}

/// Resolve the current on-hand quantity for a product.
///
/// The inventory store tracks items by SKU; the product is resolved through
/// the products service so the lookup matches on `product_id → sku` rather
/// than string-comparing the product UUID against arbitrary SKU values.
async fn on_hand_for_product(state: &AppState, tenant_id: Uuid, product_id: Uuid) -> f64 {
    let sku = match state
        .products_service
        .get_product(tenant_id, product_id)
        .await
    {
        Ok(product) => product.sku,
        Err(_) => return 0.0,
    };
    let inv_store = state.inventory_items.read(tenant_id).await;
    inv_store
        .values()
        .find(|i| i.tenant_id == tenant_id && i.sku == sku)
        .map(|i| i.quantity_on_hand)
        .unwrap_or(0.0)
}

// ── Demand Entries ─────────────────────────────────────────────────────────

/// List demand entries with optional filters.
pub async fn list_demand(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Query(params): Query<ListDemandParams>,
) -> Result<Json<PaginatedResponse<DemandEntry>>> {
    user.require_permission("tps:mrp:run")?;
    let tenant_id = user.tenant_id;
    let date_from = parse_date_filter("date_from", params.date_from.as_deref())?;
    let date_to = parse_date_filter("date_to", params.date_to.as_deref())?;

    let store = state.demand_entries.read(user.tenant_id).await;
    let mut entries: Vec<DemandEntry> = store
        .values()
        .filter(|d| d.tenant_id == tenant_id)
        .filter(|d| {
            if let Some(pid) = &params.product_id {
                d.product_id == *pid
            } else {
                true
            }
        })
        .filter(|d| {
            if let Some(ref st) = params.source_type {
                d.source_type == *st
            } else {
                true
            }
        })
        .filter(|d| date_from.is_none_or(|from| d.due_date >= from))
        .filter(|d| date_to.is_none_or(|to| d.due_date <= to))
        .cloned()
        .collect();
    entries.sort_by_key(|a| a.due_date);
    let result = PaginatedResponse::new(entries, params.page, params.per_page);
    Ok(Json(result))
}

/// Create a new demand entry.
pub async fn create_demand(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<CreateDemandRequest>,
) -> Result<Json<DemandEntry>> {
    let tenant_id = user.tenant_id;
    let now = Utc::now();
    let due_date = DateTime::parse_from_rfc3339(&req.due_date)
        .map_err(|e| SenseiError::Validation(format!("Invalid due_date: {e}")))?
        .with_timezone(&Utc);

    let entry = DemandEntry {
        id: new_id(),
        tenant_id,
        product_id: req.product_id,
        product_name: req.product_name,
        quantity: req.quantity,
        due_date,
        source_type: req.source_type,
        source_id: req.source_id,
        notes: req.notes,
        created_by: user.user_id,
        created_at: now,
        updated_at: now,
    };
    let mut store = state.demand_entries.write(user.tenant_id).await;
    store.insert(entry.id, entry.clone());
    store.persist().await?;
    Ok(Json(entry))
}

// ── Supply Orders ──────────────────────────────────────────────────────────

/// List planned supply orders with optional filters.
pub async fn list_supply(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Query(params): Query<ListSupplyParams>,
) -> Result<Json<PaginatedResponse<SupplyOrder>>> {
    user.require_permission("tps:mrp:run")?;
    let tenant_id = user.tenant_id;
    let store = state.supply_orders.read(user.tenant_id).await;
    let mut orders: Vec<SupplyOrder> = store
        .values()
        .filter(|o| o.tenant_id == tenant_id)
        .filter(|o| {
            if let Some(pid) = &params.product_id {
                o.product_id == *pid
            } else {
                true
            }
        })
        .filter(|o| {
            if let Some(ref status) = params.status {
                o.status == *status
            } else {
                true
            }
        })
        .cloned()
        .collect();
    orders.sort_by_key(|a| a.order_date);
    let result = PaginatedResponse::new(orders, params.page, params.per_page);
    Ok(Json(result))
}

// ── MRP Run ────────────────────────────────────────────────────────────────

/// Trigger an MRP run (net requirements calculation).
pub async fn run_mrp(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Json(req): Json<RunMrpRequest>,
) -> Result<Json<MrpRunDetail>> {
    user.require_permission("tps:mrp:run")?;
    let tenant_id = user.tenant_id;
    let now = Utc::now();

    // Gather demand entries for this tenant
    let demand_store = state.demand_entries.read(user.tenant_id).await;
    let demands: Vec<&DemandEntry> = demand_store
        .values()
        .filter(|d| d.tenant_id == tenant_id)
        .collect();

    // Net demands CUMULATIVELY against the same on-hand: each unit of
    // stock can satisfy exactly ONE demand. (stock=100, demands 80+80 must
    // yield a 60-unit shortage, never two "0 requirement" lines.)
    // Demands are processed in due-date order so earlier commitments
    // consume stock first.
    let mut demands_sorted = demands.clone();
    demands_sorted.sort_by_key(|d| d.due_date);

    let mut planned_orders: Vec<PlannedOrder> = Vec::new();
    // Resolve on-hand ONCE per product (via SKU, never by string comparing
    // UUIDs), then consume it cumulatively across that product's demands.
    let mut remaining: std::collections::HashMap<Uuid, f64> = std::collections::HashMap::new();
    for demand in &demands_sorted {
        let on_hand = if let Some(balance) = remaining.get(&demand.product_id) {
            *balance
        } else {
            let on_hand = on_hand_for_product(&state, tenant_id, demand.product_id).await;
            remaining.insert(demand.product_id, on_hand);
            on_hand
        };

        let net_requirement = (demand.quantity - on_hand).max(0.0);
        let suggested_qty = if net_requirement > 0.0 {
            // Round up to nearest whole unit
            (net_requirement).ceil()
        } else {
            0.0
        };

        // Consume the stock this demand was covered by (never below zero).
        let consumed = demand.quantity.min(on_hand);
        if let Some(balance) = remaining.get_mut(&demand.product_id) {
            *balance -= consumed;
        }

        planned_orders.push(PlannedOrder {
            product_id: demand.product_id,
            product_name: demand.product_name.clone(),
            required_quantity: demand.quantity,
            on_hand,
            net_requirement,
            suggested_order_quantity: suggested_qty,
            suggested_order_date: now.to_rfc3339(),
            expected_delivery: demand.due_date.to_rfc3339(),
        });
    }

    let run_id = new_id();
    let mrp_run = MrpRun {
        id: run_id,
        tenant_id,
        run_type: req.run_type,
        status: "completed".to_string(),
        started_at: now,
        completed_at: Some(now),
        summary: serde_json::json!({
            "total_demand_entries": demands.len(),
            "total_planned_orders": planned_orders.len(),
            "total_net_requirement": planned_orders.iter().map(|p| p.net_requirement).sum::<f64>(),
        }),
        created_by: user.user_id,
    };

    let mut run_store = state.mrp_runs.write(user.tenant_id).await;
    run_store.insert(run_id, mrp_run.clone());

    // Create supply orders from planned orders, tagging each with the
    // generating run's id so planned orders can be reconstructed exactly.
    let mut supply_store = state.supply_orders.write(user.tenant_id).await;
    for po in &planned_orders {
        if po.suggested_order_quantity > 0.0 {
            let order_date = now;
            let delivery_date = DateTime::parse_from_rfc3339(&po.expected_delivery)
                .unwrap_or_else(|_| now.into())
                .with_timezone(&Utc);

            let supply = SupplyOrder {
                id: new_id(),
                tenant_id,
                product_id: po.product_id,
                product_name: po.product_name.clone(),
                quantity: po.suggested_order_quantity,
                order_date,
                expected_delivery: delivery_date,
                status: "planned".to_string(),
                notes: format!("Generated by MRP run {}", run_id),
                run_id: Some(run_id),
                created_by: user.user_id,
                created_at: now,
                updated_at: now,
            };
            supply_store.insert(supply.id, supply);
        }
    }

    let detail = MrpRunDetail {
        run: mrp_run,
        planned_orders,
    };
    Ok(Json(detail))
}

/// List MRP run history.
pub async fn list_mrp_runs(
    user: AuthenticatedUser,
    State(state): State<AppState>,
) -> Result<Json<Vec<MrpRun>>> {
    user.require_permission("tps:mrp:run")?;
    let tenant_id = user.tenant_id;
    let store = state.mrp_runs.read(user.tenant_id).await;
    let mut runs: Vec<MrpRun> = store
        .values()
        .filter(|r| r.tenant_id == tenant_id)
        .cloned()
        .collect();
    runs.sort_by_key(|a| std::cmp::Reverse(a.started_at));
    Ok(Json(runs))
}

/// Get MRP run detail with planned orders.
///
/// Planned orders are reconstructed from the supply orders tagged with this
/// run's id (no notes-string matching), and on-hand values are computed
/// live from the inventory store (never hardcoded to 0).
pub async fn get_mrp_run(
    user: AuthenticatedUser,
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
) -> Result<Json<MrpRunDetail>> {
    user.require_permission("tps:mrp:run")?;
    let tenant_id = user.tenant_id;
    let store = state.mrp_runs.read(user.tenant_id).await;
    let run = store
        .values()
        .find(|r| r.id == id && r.tenant_id == tenant_id)
        .cloned()
        .ok_or_else(|| SenseiError::NotFound(format!("MRP run {id} not found")))?;

    // Gather planned orders from the supply orders tagged with this run.
    let supply_store = state.supply_orders.read(user.tenant_id).await;
    let mut planned_orders: Vec<PlannedOrder> = supply_store
        .values()
        .filter(|o| o.tenant_id == tenant_id && o.run_id == Some(id))
        .map(|o| PlannedOrder {
            product_id: o.product_id,
            product_name: o.product_name.clone(),
            required_quantity: o.quantity,
            on_hand: 0.0,
            net_requirement: o.quantity,
            suggested_order_quantity: o.quantity,
            suggested_order_date: o.order_date.to_rfc3339(),
            expected_delivery: o.expected_delivery.to_rfc3339(),
        })
        .collect();

    // Compute live on-hand per product instead of reporting a hardcoded 0.
    for order in &mut planned_orders {
        order.on_hand = on_hand_for_product(&state, tenant_id, order.product_id).await;
    }

    let detail = MrpRunDetail {
        run,
        planned_orders,
    };
    Ok(Json(detail))
}
