//! PDF worker — replaces Celery's `generate_a3_pdf` and `generate_quote_pdf`.
//!
//! Listens on two subjects:
//! - `sensei.tasks.pdf.a3` — A3 report generation
//! - `sensei.tasks.pdf.quote` — Quote PDF generation
//!
//! Generates real PDF documents from the task payload using the
//! [`PdfExportService`] (sensei-services), stores the bytes through the
//! configured [`FileStorageService`], and tracks progress in a NATS KV store.

use crate::error::{Result, WorkerError};
use crate::task::{TaskConsumer, TaskMetadata};
use async_nats::jetstream::kv::Store;
use async_nats::jetstream::Context;
use async_trait::async_trait;
use sensei_services::export::pdf::{A3Data, PdfExportService, QuoteData};
use sensei_services::storage::file_storage::{FileStorageService, InMemoryStorageService};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{error, info, warn};
use uuid::Uuid;

/// Which document the PDF task renders.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PdfKind {
    /// A3 problem-solving report.
    A3,
    /// Customer quotation.
    Quote,
}

/// Payload for PDF generation tasks.
///
/// `data` carries the document fields (see [`A3Data`] / [`QuoteData`]).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PdfTaskPayload {
    /// The kind of document to render.
    pub kind: PdfKind,
    /// Document data (A3 or quote fields).
    pub data: serde_json::Value,
}

/// Progress states for PDF generation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum PdfProgress {
    /// Task has been received but not yet started.
    Pending,
    /// PDF generation is in progress.
    Generating,
    /// PDF has been generated and stored.
    Completed {
        /// Storage key / URL of the generated PDF.
        storage_key: String,
    },
    /// PDF generation failed.
    Failed {
        /// Error message.
        error: String,
    },
}

/// Worker that handles PDF generation tasks.
///
/// Uses the sensei-services [`PdfExportService`] to render real PDFs from the
/// payload data, stores the bytes via a [`FileStorageService`] (in-memory by
/// default), and reports progress through a NATS KV bucket.
pub struct PdfWorker {
    /// NATS JetStream context for KV store access.
    js: Context,
    /// Handle to the KV store bucket (lazily initialised).
    kv: Arc<RwLock<Option<Store>>>,
    /// Name of the KV bucket to use.
    kv_bucket: String,
    /// Storage backend for the generated bytes.
    storage: Arc<dyn FileStorageService>,
    /// PDF rendering service.
    pdf: PdfExportService,
}

impl PdfWorker {
    /// Create a new [`PdfWorker`] with the default in-memory storage backend.
    pub fn new(js: Context) -> Self {
        Self {
            js,
            kv: Arc::new(RwLock::new(None)),
            kv_bucket: "sensei_pdf_progress".to_string(),
            storage: Arc::new(InMemoryStorageService::new()),
            pdf: PdfExportService::new(),
        }
    }

    /// Create a new [`PdfWorker`] with an explicit storage backend.
    pub fn with_storage(js: Context, storage: Arc<dyn FileStorageService>) -> Self {
        Self {
            js,
            kv: Arc::new(RwLock::new(None)),
            kv_bucket: "sensei_pdf_progress".to_string(),
            storage,
            pdf: PdfExportService::new(),
        }
    }

    /// Lazily initialise (or retrieve) the KV store bucket.
    async fn kv_store(&self) -> Result<Store> {
        let mut guard = self.kv.write().await;
        if let Some(ref store) = *guard {
            return Ok(store.clone());
        }

        // Try to create the bucket; if it already exists, open it instead.
        let store = self
            .js
            .create_key_value(async_nats::jetstream::kv::Config {
                bucket: self.kv_bucket.clone(),
                history: 5,
                max_value_size: 4096,
                ..Default::default()
            })
            .await;

        let store = match store {
            Ok(store) => store,
            Err(_) => {
                // Bucket might already exist — try to open it.
                self.js
                    .get_key_value(&self.kv_bucket)
                    .await
                    .map_err(|e| WorkerError::KvStore(e.to_string()))?
            }
        };

        *guard = Some(store.clone());
        Ok(store)
    }

    /// Update progress for a given task in the KV store.
    async fn update_progress(&self, task_id: &str, progress: &PdfProgress) -> Result<()> {
        let store = self.kv_store().await?;
        let key = format!("pdf.{}", task_id);
        let value = serde_json::to_vec(progress).map_err(WorkerError::Serialization)?;

        store
            .put(key, value.into())
            .await
            .map_err(|e| WorkerError::KvStore(e.to_string()))?;

        Ok(())
    }

    /// Generate a PDF from the task payload, store the bytes, and return the
    /// storage key.
    async fn generate_pdf(
        &self,
        payload: &PdfTaskPayload,
        task_id: &str,
        tenant_id: Option<Uuid>,
    ) -> Result<String> {
        self.update_progress(task_id, &PdfProgress::Generating)
            .await?;

        let kind = payload.kind;
        let data = payload.data.clone();
        let pdf = self.pdf.clone();

        // Rendering is CPU-bound; run it on a blocking thread.
        let pdf_bytes = tokio::task::spawn_blocking(move || match kind {
            PdfKind::A3 => {
                let a3: A3Data = serde_json::from_value(data)
                    .map_err(|e| format!("A3 PDF data is missing or malformed: {e}"))?;
                pdf.generate_a3_report(&a3).map_err(|e| e.to_string())
            }
            PdfKind::Quote => {
                let quote: QuoteData = serde_json::from_value(data)
                    .map_err(|e| format!("Quote PDF data is missing or malformed: {e}"))?;
                pdf.generate_quote(&quote).map_err(|e| e.to_string())
            }
        })
        .await
        .map_err(|e| WorkerError::Processing(format!("PDF generation task panicked: {e}")))?
        .map_err(WorkerError::Processing)?;

        if pdf_bytes.is_empty() {
            return Err(WorkerError::Processing(
                "PDF generation produced no bytes".to_string(),
            ));
        }

        // Store the bytes through the storage service and surface its key.
        let tenant = tenant_id.unwrap_or_else(Uuid::nil);
        let path = match kind {
            PdfKind::A3 => format!("a3/{task_id}.pdf"),
            PdfKind::Quote => format!("quotes/{task_id}.pdf"),
        };
        let storage_key = self
            .storage
            .store(tenant, &path, &pdf_bytes, "application/pdf")
            .await
            .map_err(|e| WorkerError::Processing(format!("Failed to store PDF bytes: {e}")))?;

        info!(
            task_id = %task_id,
            storage_key = %storage_key,
            size_bytes = pdf_bytes.len(),
            "PDF generated and stored successfully"
        );

        Ok(storage_key)
    }
}

#[async_trait]
impl TaskConsumer for PdfWorker {
    fn subject(&self) -> &'static str {
        "sensei.tasks.pdf.a3"
    }

    fn consumer_group(&self) -> &'static str {
        "sensei-workers-pdf"
    }

    async fn process(&self, payload: &[u8], metadata: &TaskMetadata) -> Result<()> {
        let pdf_payload: PdfTaskPayload = serde_json::from_slice(payload).map_err(|e| {
            error!(
                task_id = %metadata.task_id,
                error = %e,
                "Failed to deserialize PDF task payload"
            );
            WorkerError::Serialization(e)
        })?;

        let task_id_str = metadata.task_id.to_string();

        // Mark as pending.
        if let Err(e) = self
            .update_progress(&task_id_str, &PdfProgress::Pending)
            .await
        {
            warn!(error = %e, "Failed to update KV progress");
        }

        // The tenant may be carried in the payload metadata.
        let tenant_id = pdf_payload
            .data
            .get("tenant_id")
            .and_then(|v| v.as_str())
            .and_then(|s| Uuid::parse_str(s).ok());

        let result = self
            .generate_pdf(&pdf_payload, &task_id_str, tenant_id)
            .await;

        match result {
            Ok(storage_key) => {
                self.update_progress(&task_id_str, &PdfProgress::Completed { storage_key })
                    .await
                    .unwrap_or_else(|e| warn!(error = %e, "Failed to update KV progress"));

                info!(
                    task_id = %metadata.task_id,
                    kind = ?pdf_payload.kind,
                    "PDF task completed successfully"
                );
                Ok(())
            }
            Err(e) => {
                self.update_progress(
                    &task_id_str,
                    &PdfProgress::Failed {
                        error: e.to_string(),
                    },
                )
                .await
                .unwrap_or_else(|kv_err| warn!(error = %kv_err, "Failed to update KV progress"));

                error!(
                    task_id = %metadata.task_id,
                    kind = ?pdf_payload.kind,
                    error = %e,
                    "PDF task failed"
                );
                Err(e)
            }
        }
    }
}

/// Convenience constructor for an A3-specific PdfWorker wrapper.
///
/// Listens on `sensei.tasks.pdf.a3`.
pub struct A3PdfWorker {
    inner: PdfWorker,
}

impl A3PdfWorker {
    pub fn new(js: Context) -> Self {
        Self {
            inner: PdfWorker::new(js),
        }
    }
}

#[async_trait]
impl TaskConsumer for A3PdfWorker {
    fn subject(&self) -> &'static str {
        "sensei.tasks.pdf.a3"
    }

    fn consumer_group(&self) -> &'static str {
        "sensei-workers-pdf-a3"
    }

    async fn process(&self, payload: &[u8], metadata: &TaskMetadata) -> Result<()> {
        self.inner.process(payload, metadata).await
    }
}

/// Convenience constructor for a Quote-specific PdfWorker wrapper.
///
/// Listens on `sensei.tasks.pdf.quote`.
pub struct QuotePdfWorker {
    inner: PdfWorker,
}

impl QuotePdfWorker {
    pub fn new(js: Context) -> Self {
        Self {
            inner: PdfWorker::new(js),
        }
    }
}

#[async_trait]
impl TaskConsumer for QuotePdfWorker {
    fn subject(&self) -> &'static str {
        "sensei.tasks.pdf.quote"
    }

    fn consumer_group(&self) -> &'static str {
        "sensei-workers-pdf-quote"
    }

    async fn process(&self, payload: &[u8], metadata: &TaskMetadata) -> Result<()> {
        self.inner.process(payload, metadata).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn a3_payload() -> PdfTaskPayload {
        PdfTaskPayload {
            kind: PdfKind::A3,
            data: serde_json::json!({
                "id": "A3-20260824-0001",
                "title": "Defect rate too high",
                "problem_statement": "PPM rose from 500 to 4200",
                "current_state": "Current state description",
                "goal": "Reduce PPM below 1000",
                "root_cause_analysis": "Lack of calibration",
                "countermeasures": "Weekly calibration",
                "check_plan": "Weekly audit",
                "follow_up": "Review in 30 days",
                "owner": "Quality Manager",
                "status": "active",
                "created_at": "2026-08-24",
            }),
        }
    }

    #[test]
    fn test_a3_payload_deserializes_into_document_data() {
        let payload = a3_payload();
        let a3: A3Data = serde_json::from_value(payload.data).expect("valid A3 data");
        assert_eq!(a3.title, "Defect rate too high");
        assert_eq!(a3.id, "A3-20260824-0001");
    }

    #[test]
    fn test_missing_a3_data_fails_clearly() {
        let payload = PdfTaskPayload {
            kind: PdfKind::A3,
            data: serde_json::json!({"id": "only-id"}),
        };
        let err = serde_json::from_value::<A3Data>(payload.data).unwrap_err();
        assert!(err.to_string().contains("title"), "error: {err}");
    }

    #[test]
    fn test_pdf_export_service_generates_a3_bytes() {
        let a3: A3Data = serde_json::from_value(a3_payload().data).unwrap();
        let pdf = PdfExportService::new();
        let bytes = pdf.generate_a3_report(&a3).expect("A3 PDF generation");
        assert!(!bytes.is_empty());
        // PDF magic header.
        assert_eq!(&bytes[..5], b"%PDF-");
    }

    #[test]
    fn test_pdf_export_service_generates_quote_bytes() {
        let quote = QuoteData {
            id: "Q-1".into(),
            quote_number: "QTE-20260824-0001".into(),
            customer_name: "Acme Corp".into(),
            date: "2026-08-24".into(),
            valid_until: "2026-09-24".into(),
            currency: "USD".into(),
            line_items: vec![sensei_services::export::pdf::QuoteLineData {
                description: "CNC Housing".into(),
                quantity: "50".into(),
                unit_price: "45.00".into(),
                total: "2250.00".into(),
            }],
            subtotal: "2250.00".into(),
            tax: "450.00".into(),
            total: "2700.00".into(),
        };
        let pdf = PdfExportService::new();
        let bytes = pdf.generate_quote(&quote).expect("quote PDF generation");
        assert!(!bytes.is_empty());
        assert_eq!(&bytes[..5], b"%PDF-");
    }
}
