#!/usr/bin/env python3
"""
Fast vernacular translation updater - applies common translations.
"""

import json
from pathlib import Path

# Core translations for each language
TRANSLATIONS = {
    "fr": {
        "Save": "Enregistrer",
        "Cancel": "Annuler",
        "Delete": "Supprimer",
        "Edit": "Modifier",
        "Create": "Créer",
        "Update": "Mettre à jour",
        "Search": "Rechercher",
        "Filter": "Filtrer",
        "Clear": "Effacer",
        "Close": "Fermer",
        "Loading...": "Chargement...",
        "Error": "Erreur",
        "Success": "Succès",
        "Warning": "Avertissement",
        "Yes": "Oui",
        "No": "Non",
        "Confirm": "Confirmer",
        "Back": "Retour",
        "Next": "Suivant",
        "Submit": "Soumettre",
        "View": "Voir",
        "Add": "Ajouter",
        "Remove": "Retirer",
        "Refresh": "Actualiser",
        "Export": "Exporter",
        "Import": "Importer",
        "Download": "Télécharger",
        "Upload": "Téléverser",
        "Active": "Actif",
        "Inactive": "Inactif",
        "Pending": "En attente",
        "Approved": "Approuvé",
        "Rejected": "Rejeté",
        "Completed": "Terminé",
        "In Progress": "En cours",
        "Critical": "Critique",
        "High": "Haute",
        "Medium": "Moyenne",
        "Low": "Basse",
        "Urgent": "Urgente",
        "Dashboard": "Tableau de bord",
        "Settings": "Paramètres",
        "Profile": "Profil",
        "Account": "Compte",
        "Security": "Sécurité",
        "Notifications": "Notifications",
        "Help": "Aide",
        "Customer": "Client",
        "Customers": "Clients",
        "Order": "Commande",
        "Orders": "Commandes",
        "Product": "Produit",
        "Products": "Produits",
        "Project": "Projet",
        "Projects": "Projets",
        "Task": "Tâche",
        "Tasks": "Tâches",
        "Name": "Nom",
        "Description": "Description",
        "Title": "Titre",
        "Email": "E-mail",
        "Status": "Statut",
        "Date": "Date",
        "Actions": "Actions",
        "Total": "Total",
        "Today": "Aujourd'hui",
        "Currency": "Devise",
        "Display Currency": "Devise d'affichage",
        "Exchange Rates": "Taux de change",
        "Last updated": "Dernière mise à jour",
        "Never": "Jamais",
        "Production": "Production",
        "Quality": "Qualité",
        "Maintenance": "Maintenance",
        "Inventory": "Inventaire",
        "Warehouse": "Entrepôt",
        "Analytics": "Analytique",
        "Reports": "Rapports",
        "Required": "Obligatoire",
        "Optional": "Facultatif",
    },
    "de": {
        "Save": "Speichern",
        "Cancel": "Abbrechen",
        "Delete": "Löschen",
        "Edit": "Bearbeiten",
        "Create": "Erstellen",
        "Update": "Aktualisieren",
        "Search": "Suchen",
        "Filter": "Filtern",
        "Clear": "Löschen",
        "Close": "Schließen",
        "Loading...": "Wird geladen...",
        "Error": "Fehler",
        "Success": "Erfolgreich",
        "Warning": "Warnung",
        "Yes": "Ja",
        "No": "Nein",
        "Confirm": "Bestätigen",
        "Back": "Zurück",
        "Next": "Weiter",
        "Submit": "Absenden",
        "View": "Ansehen",
        "Add": "Hinzufügen",
        "Remove": "Entfernen",
        "Refresh": "Aktualisieren",
        "Export": "Exportieren",
        "Import": "Importieren",
        "Download": "Herunterladen",
        "Upload": "Hochladen",
        "Active": "Aktiv",
        "Inactive": "Inaktiv",
        "Pending": "Ausstehend",
        "Approved": "Genehmigt",
        "Rejected": "Abgelehnt",
        "Completed": "Abgeschlossen",
        "In Progress": "In Bearbeitung",
        "Critical": "Kritisch",
        "High": "Hoch",
        "Medium": "Mittel",
        "Low": "Niedrig",
        "Urgent": "Dringend",
        "Dashboard": "Dashboard",
        "Settings": "Einstellungen",
        "Profile": "Profil",
        "Account": "Konto",
        "Security": "Sicherheit",
        "Notifications": "Benachrichtigungen",
        "Help": "Hilfe",
        "Customer": "Kunde",
        "Customers": "Kunden",
        "Order": "Bestellung",
        "Orders": "Bestellungen",
        "Product": "Produkt",
        "Products": "Produkte",
        "Project": "Projekt",
        "Projects": "Projekte",
        "Task": "Aufgabe",
        "Tasks": "Aufgaben",
        "Name": "Name",
        "Description": "Beschreibung",
        "Title": "Titel",
        "Email": "E-Mail",
        "Status": "Status",
        "Date": "Datum",
        "Actions": "Aktionen",
        "Total": "Gesamt",
        "Today": "Heute",
        "Currency": "Währung",
        "Display Currency": "Anzeigewährung",
        "Exchange Rates": "Wechselkurse",
        "Last updated": "Zuletzt aktualisiert",
        "Never": "Nie",
        "Production": "Produktion",
        "Quality": "Qualität",
        "Maintenance": "Wartung",
        "Inventory": "Bestand",
        "Warehouse": "Lager",
        "Analytics": "Analytik",
        "Reports": "Berichte",
        "Required": "Erforderlich",
        "Optional": "Optional",
    },
    "es": {
        "Save": "Guardar",
        "Cancel": "Cancelar",
        "Delete": "Eliminar",
        "Edit": "Editar",
        "Create": "Crear",
        "Update": "Actualizar",
        "Search": "Buscar",
        "Filter": "Filtrar",
        "Clear": "Limpiar",
        "Close": "Cerrar",
        "Loading...": "Cargando...",
        "Error": "Error",
        "Success": "Éxito",
        "Warning": "Advertencia",
        "Yes": "Sí",
        "No": "No",
        "Confirm": "Confirmar",
        "Back": "Atrás",
        "Next": "Siguiente",
        "Submit": "Enviar",
        "View": "Ver",
        "Add": "Agregar",
        "Remove": "Quitar",
        "Refresh": "Actualizar",
        "Export": "Exportar",
        "Import": "Importar",
        "Download": "Descargar",
        "Upload": "Subir",
        "Active": "Activo",
        "Inactive": "Inactivo",
        "Pending": "Pendiente",
        "Approved": "Aprobado",
        "Rejected": "Rechazado",
        "Completed": "Completado",
        "In Progress": "En progreso",
        "Critical": "Crítico",
        "High": "Alta",
        "Medium": "Media",
        "Low": "Baja",
        "Urgent": "Urgente",
        "Dashboard": "Panel de control",
        "Settings": "Configuración",
        "Profile": "Perfil",
        "Account": "Cuenta",
        "Security": "Seguridad",
        "Notifications": "Notificaciones",
        "Help": "Ayuda",
        "Customer": "Cliente",
        "Customers": "Clientes",
        "Order": "Pedido",
        "Orders": "Pedidos",
        "Product": "Producto",
        "Products": "Productos",
        "Project": "Proyecto",
        "Projects": "Proyectos",
        "Task": "Tarea",
        "Tasks": "Tareas",
        "Name": "Nombre",
        "Description": "Descripción",
        "Title": "Título",
        "Email": "Correo electrónico",
        "Status": "Estado",
        "Date": "Fecha",
        "Actions": "Acciones",
        "Total": "Total",
        "Today": "Hoy",
        "Currency": "Moneda",
        "Display Currency": "Moneda de visualización",
        "Exchange Rates": "Tipos de cambio",
        "Last updated": "Última actualización",
        "Never": "Nunca",
        "Production": "Producción",
        "Quality": "Calidad",
        "Maintenance": "Mantenimiento",
        "Inventory": "Inventario",
        "Warehouse": "Almacén",
        "Analytics": "Análisis",
        "Reports": "Informes",
        "Required": "Obligatorio",
        "Optional": "Opcional",
    },
    "ar": {
        "Save": "حفظ",
        "Cancel": "إلغاء",
        "Delete": "حذف",
        "Edit": "تعديل",
        "Create": "إنشاء",
        "Update": "تحديث",
        "Search": "بحث",
        "Filter": "تصفية",
        "Clear": "مسح",
        "Close": "إغلاق",
        "Loading...": "جاري التحميل...",
        "Error": "خطأ",
        "Success": "نجاح",
        "Warning": "تحذير",
        "Yes": "نعم",
        "No": "لا",
        "Confirm": "تأكيد",
        "Back": "رجوع",
        "Next": "التالي",
        "Submit": "إرسال",
        "View": "عرض",
        "Add": "إضافة",
        "Remove": "إزالة",
        "Refresh": "تحديث",
        "Export": "تصدير",
        "Import": "استيراد",
        "Download": "تنزيل",
        "Upload": "رفع",
        "Active": "نشط",
        "Inactive": "غير نشط",
        "Pending": "قيد الانتظار",
        "Approved": "موافق عليه",
        "Rejected": "مرفوض",
        "Completed": "مكتمل",
        "In Progress": "قيد التنفيذ",
        "Critical": "حرج",
        "High": "عالية",
        "Medium": "متوسطة",
        "Low": "منخفضة",
        "Urgent": "عاجل",
        "Dashboard": "لوحة التحكم",
        "Settings": "الإعدادات",
        "Profile": "الملف الشخصي",
        "Account": "الحساب",
        "Security": "الأمان",
        "Notifications": "الإشعارات",
        "Help": "المساعدة",
        "Customer": "عميل",
        "Customers": "العملاء",
        "Order": "طلب",
        "Orders": "الطلبات",
        "Product": "منتج",
        "Products": "المنتجات",
        "Project": "مشروع",
        "Projects": "المشاريع",
        "Task": "مهمة",
        "Tasks": "المهام",
        "Name": "الاسم",
        "Description": "الوصف",
        "Title": "العنوان",
        "Email": "البريد الإلكتروني",
        "Status": "الحالة",
        "Date": "التاريخ",
        "Actions": "الإجراءات",
        "Total": "الإجمالي",
        "Today": "اليوم",
        "Currency": "العملة",
        "Display Currency": "عملة العرض",
        "Exchange Rates": "أسعار الصرف",
        "Last updated": "آخر تحديث",
        "Never": "أبداً",
        "Production": "الإنتاج",
        "Quality": "الجودة",
        "Maintenance": "الصيانة",
        "Inventory": "المخزون",
        "Warehouse": "المستودع",
        "Analytics": "التحليلات",
        "Reports": "التقارير",
        "Required": "مطلوب",
        "Optional": "اختياري",
    }
}


def update_json_recursive(obj, translations):
    """Recursively update JSON values with translations."""
    if isinstance(obj, dict):
        for key, value in obj.items():
            if isinstance(value, str) and value in translations:
                obj[key] = translations[value]
            elif isinstance(value, dict):
                update_json_recursive(value, translations)
    return obj


def main():
    locales_dir = Path(__file__).parent.parent / 'src' / 'locales'
    
    print("🌍 Applying vernacular translations (fast mode)...")
    
    for lang, translations in TRANSLATIONS.items():
        locale_path = locales_dir / f'{lang}.json'
        if not locale_path.exists():
            print(f"   ⚠️  {lang}.json not found")
            continue
        
        with open(locale_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        update_json_recursive(data, translations)
        
        with open(locale_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        
        print(f"   ✅ {lang}.json updated")
    
    print("\n✅ Vernacular translations applied!")


if __name__ == '__main__':
    main()
