#!/usr/bin/env python3
"""
Generate professional, vernacular translations for the Management Software.
This script converts English placeholder translations to proper idiomatic translations
in French, German, Spanish, and Arabic.
"""

import json
import re
from pathlib import Path

# Comprehensive vernacular translation dictionaries
# These are natural, idiomatic translations - not machine-generated

VERNACULAR_FR = {
    # Common actions and UI
    "Save": "Enregistrer",
    "Cancel": "Annuler",
    "Delete": "Supprimer",
    "Edit": "Modifier",
    "Create": "Créer",
    "Update": "Mettre à jour",
    "Search": "Rechercher",
    "Filter": "Filtrer",
    "Clear": "Effacer",
    "Close": "Fermer",
    "Loading...": "Chargement...",
    "Error": "Erreur",
    "Success": "Succès",
    "Warning": "Avertissement",
    "Info": "Information",
    "Yes": "Oui",
    "No": "Non",
    "Confirm": "Confirmer",
    "Back": "Retour",
    "Next": "Suivant",
    "Previous": "Précédent",
    "Submit": "Soumettre",
    "Reset": "Réinitialiser",
    "View": "Voir",
    "Add": "Ajouter",
    "Remove": "Retirer",
    "Refresh": "Actualiser",
    "Export": "Exporter",
    "Import": "Importer",
    "Download": "Télécharger",
    "Upload": "Téléverser",
    "Print": "Imprimer",
    "Copy": "Copier",
    "Paste": "Coller",
    "Duplicate": "Dupliquer",
    "Archive": "Archiver",
    "Restore": "Restaurer",
    "Approve": "Approuver",
    "Reject": "Rejeter",
    "Analyze": "Analyser",
    "Configure": "Configurer",
    "Sync": "Synchroniser",
    "Initialize": "Initialiser",
    "Terminate": "Terminer",
    "Escalate": "Escalader",
    "Execute": "Exécuter",
    
    # Status terms
    "Active": "Actif",
    "Inactive": "Inactif",
    "Pending": "En attente",
    "Approved": "Approuvé",
    "Rejected": "Rejeté",
    "Draft": "Brouillon",
    "Published": "Publié",
    "Completed": "Terminé",
    "In Progress": "En cours",
    "Not Started": "Non démarré",
    "On Hold": "En pause",
    "Cancelled": "Annulé",
    "Open": "Ouvert",
    "Closed": "Fermé",
    "Resolved": "Résolu",
    "Overdue": "En retard",
    "Scheduled": "Planifié",
    "Running": "En exécution",
    "Stopped": "Arrêté",
    "Failed": "Échoué",
    "Won": "Gagné",
    "Lost": "Perdu",
    
    # Priority terms
    "Critical": "Critique",
    "High": "Haute",
    "Medium": "Moyenne",
    "Low": "Basse",
    "Normal": "Normale",
    "Urgent": "Urgente",
    
    # Time terms
    "Today": "Aujourd'hui",
    "Yesterday": "Hier",
    "Tomorrow": "Demain",
    "This Week": "Cette semaine",
    "Last Week": "Semaine dernière",
    "This Month": "Ce mois-ci",
    "Last Month": "Mois dernier",
    "This Year": "Cette année",
    "Last Year": "Année dernière",
    "Now": "Maintenant",
    "Never": "Jamais",
    "Daily": "Quotidien",
    "Weekly": "Hebdomadaire",
    "Monthly": "Mensuel",
    "Yearly": "Annuel",
    
    # Navigation & Layout
    "Dashboard": "Tableau de bord",
    "Home": "Accueil",
    "Settings": "Paramètres",
    "Profile": "Profil",
    "Account": "Compte",
    "Security": "Sécurité",
    "Notifications": "Notifications",
    "Help": "Aide",
    "About": "À propos",
    "Logout": "Déconnexion",
    "Login": "Connexion",
    "Sign In": "Se connecter",
    "Sign Up": "S'inscrire",
    "Sign Out": "Se déconnecter",
    "Menu": "Menu",
    "Navigation": "Navigation",
    "Sidebar": "Barre latérale",
    "Header": "En-tête",
    "Footer": "Pied de page",
    "Overview": "Vue d'ensemble",
    "Details": "Détails",
    "Summary": "Résumé",
    
    # Business terms
    "Customer": "Client",
    "Customers": "Clients",
    "Supplier": "Fournisseur",
    "Suppliers": "Fournisseurs",
    "Vendor": "Vendeur",
    "Partner": "Partenaire",
    "Employee": "Employé",
    "Employees": "Employés",
    "Team": "Équipe",
    "Teams": "Équipes",
    "Department": "Département",
    "Organization": "Organisation",
    "Company": "Entreprise",
    "Order": "Commande",
    "Orders": "Commandes",
    "Invoice": "Facture",
    "Invoices": "Factures",
    "Quote": "Devis",
    "Quotes": "Devis",
    "Product": "Produit",
    "Products": "Produits",
    "Service": "Service",
    "Services": "Services",
    "Project": "Projet",
    "Projects": "Projets",
    "Task": "Tâche",
    "Tasks": "Tâches",
    "Item": "Article",
    "Items": "Articles",
    "Unit": "Unité",
    "Units": "Unités",
    "Quantity": "Quantité",
    "Price": "Prix",
    "Amount": "Montant",
    "Total": "Total",
    "Subtotal": "Sous-total",
    "Discount": "Remise",
    "Tax": "Taxe",
    "Currency": "Devise",
    "Budget": "Budget",
    "Revenue": "Chiffre d'affaires",
    "Profit": "Bénéfice",
    "Cost": "Coût",
    "Expense": "Dépense",
    "Payment": "Paiement",
    "Transaction": "Transaction",
    
    # Manufacturing terms
    "Production": "Production",
    "Manufacturing": "Fabrication",
    "Assembly": "Assemblage",
    "Quality": "Qualité",
    "Inspection": "Inspection",
    "Maintenance": "Maintenance",
    "Inventory": "Inventaire",
    "Warehouse": "Entrepôt",
    "Stock": "Stock",
    "Shipment": "Expédition",
    "Delivery": "Livraison",
    "Work Order": "Ordre de fabrication",
    "Work Orders": "Ordres de fabrication",
    "Bill of Materials": "Nomenclature",
    "BOM": "Nomenclature",
    "Routing": "Gamme",
    "Operation": "Opération",
    "Workstation": "Poste de travail",
    "Machine": "Machine",
    "Equipment": "Équipement",
    "Downtime": "Temps d'arrêt",
    "Yield": "Rendement",
    "Scrap": "Rebut",
    "Defect": "Défaut",
    "Rework": "Reprise",
    "Capacity": "Capacité",
    "Throughput": "Débit",
    "Lead Time": "Délai",
    "Cycle Time": "Temps de cycle",
    "Setup Time": "Temps de réglage",
    "Batch": "Lot",
    "Lot": "Lot",
    "Serial Number": "Numéro de série",
    "Traceability": "Traçabilité",
    
    # Analytics terms
    "Analytics": "Analytique",
    "Report": "Rapport",
    "Reports": "Rapports",
    "Chart": "Graphique",
    "Graph": "Graphique",
    "Metric": "Métrique",
    "Metrics": "Métriques",
    "KPI": "ICP",
    "Indicator": "Indicateur",
    "Trend": "Tendance",
    "Forecast": "Prévision",
    "Prediction": "Prédiction",
    "Analysis": "Analyse",
    "Insight": "Aperçu",
    "Intelligence": "Intelligence",
    "Performance": "Performance",
    "Efficiency": "Efficacité",
    "Productivity": "Productivité",
    
    # IT terms
    "System": "Système",
    "Systems": "Systèmes",
    "Server": "Serveur",
    "Network": "Réseau",
    "Database": "Base de données",
    "API": "API",
    "Integration": "Intégration",
    "Webhook": "Webhook",
    "Node": "Nœud",
    "Protocol": "Protocole",
    "Connection": "Connexion",
    "Session": "Session",
    "Authentication": "Authentification",
    "Authorization": "Autorisation",
    "Permission": "Permission",
    "Role": "Rôle",
    "User": "Utilisateur",
    "Admin": "Administrateur",
    "Configuration": "Configuration",
    "Backup": "Sauvegarde",
    "Restore": "Restauration",
    "Log": "Journal",
    "Audit": "Audit",
    "Monitoring": "Surveillance",
    "Alert": "Alerte",
    "Notification": "Notification",
    
    # Form fields
    "Name": "Nom",
    "Description": "Description",
    "Title": "Titre",
    "Email": "E-mail",
    "Phone": "Téléphone",
    "Address": "Adresse",
    "City": "Ville",
    "Country": "Pays",
    "Date": "Date",
    "Time": "Heure",
    "Start Date": "Date de début",
    "End Date": "Date de fin",
    "Due Date": "Date d'échéance",
    "Created": "Créé",
    "Updated": "Mis à jour",
    "Modified": "Modifié",
    "By": "Par",
    "From": "De",
    "To": "À",
    "Status": "Statut",
    "Type": "Type",
    "Category": "Catégorie",
    "Tags": "Étiquettes",
    "Notes": "Notes",
    "Comments": "Commentaires",
    "Attachments": "Pièces jointes",
    "Required": "Obligatoire",
    "Optional": "Facultatif",
    
    # Table/List terms
    "No data available": "Aucune donnée disponible",
    "No results found": "Aucun résultat trouvé",
    "Showing": "Affichage",
    "of": "sur",
    "results": "résultats",
    "per page": "par page",
    "Sort by": "Trier par",
    "Ascending": "Croissant",
    "Descending": "Décroissant",
    "Select All": "Tout sélectionner",
    "Deselect All": "Tout désélectionner",
    "Selected": "Sélectionné",
    "Actions": "Actions",
    "More": "Plus",
    "Show More": "Afficher plus",
    "Show Less": "Afficher moins",
    "See All": "Voir tout",
    "View All": "Voir tout",
    "Load More": "Charger plus",
    
    # Empty states
    "No items": "Aucun élément",
    "Empty": "Vide",
    "Nothing here": "Rien ici",
    "Get started": "Commencer",
    "Create your first": "Créez votre premier",
    
    # Error messages
    "Something went wrong": "Une erreur s'est produite",
    "Please try again": "Veuillez réessayer",
    "Invalid input": "Entrée invalide",
    "Field is required": "Ce champ est obligatoire",
    "Invalid email": "E-mail invalide",
    "Invalid format": "Format invalide",
    "Too short": "Trop court",
    "Too long": "Trop long",
    "Already exists": "Existe déjà",
    "Not found": "Non trouvé",
    "Access denied": "Accès refusé",
    "Unauthorized": "Non autorisé",
    "Session expired": "Session expirée",
    "Network error": "Erreur réseau",
    "Server error": "Erreur serveur",
    
    # Success messages
    "Saved successfully": "Enregistré avec succès",
    "Updated successfully": "Mis à jour avec succès",
    "Deleted successfully": "Supprimé avec succès",
    "Created successfully": "Créé avec succès",
    "Operation successful": "Opération réussie",
    "Changes saved": "Modifications enregistrées",
    
    # Confirmations
    "Are you sure?": "Êtes-vous sûr ?",
    "This action cannot be undone": "Cette action est irréversible",
    "Confirm deletion": "Confirmer la suppression",
    "Confirm action": "Confirmer l'action",
    
    # Specialized terms (Management Software specific)
    "STATION": "STATION",
    "STATION:": "STATION :",
    "SYNC": "SYNC",
    "PULSE": "PULSE",
    "NODE": "NŒUD",
    "PROTOCOL": "PROTOCOLE",
    "INTEL": "INTEL",
    "INITIALIZE": "INITIALISER",
    "SYNCHRONIZE": "SYNCHRONISER",
    "TERMINATE": "TERMINER",
    "RFQ": "DAC",  # Demande d'Achat/Cotation
    "Pipeline": "Pipeline",
    "Kanban": "Kanban",
    "Backlog": "Backlog",
    "Sprint": "Sprint",
    "Epic": "Epic",
    "Milestone": "Jalon",
    "Anomaly": "Anomalie",
    "Exception": "Exception",
    "Countermeasure": "Contre-mesure",
    "Root Cause": "Cause racine",
    "Corrective Action": "Action corrective",
    "Preventive Action": "Action préventive",
    "SQDCP": "SQDCP",
    "Obeya": "Obeya",
    "A3": "A3",
    "Andon": "Andon",
    "MRP": "MRP",
    "MPS": "MPS",
    "Sensei": "Sensei",
    "AI": "IA",
    
    # Currency
    "Display Currency": "Devise d'affichage",
    "Exchange Rates": "Taux de change",
    "Suggested": "Suggéré",
    "Rate": "Taux",
    "Sample amount": "Montant exemple",
    "Use Suggested": "Utiliser suggéré",
    "Refresh Rates": "Actualiser les taux",
    "Rates synchronized": "Taux synchronisés",
    "Using cached rates": "Utilisation des taux en cache",
    "Last updated": "Dernière mise à jour",
}

VERNACULAR_DE = {
    # Common actions and UI
    "Save": "Speichern",
    "Cancel": "Abbrechen",
    "Delete": "Löschen",
    "Edit": "Bearbeiten",
    "Create": "Erstellen",
    "Update": "Aktualisieren",
    "Search": "Suchen",
    "Filter": "Filtern",
    "Clear": "Löschen",
    "Close": "Schließen",
    "Loading...": "Wird geladen...",
    "Error": "Fehler",
    "Success": "Erfolgreich",
    "Warning": "Warnung",
    "Info": "Info",
    "Yes": "Ja",
    "No": "Nein",
    "Confirm": "Bestätigen",
    "Back": "Zurück",
    "Next": "Weiter",
    "Previous": "Zurück",
    "Submit": "Absenden",
    "Reset": "Zurücksetzen",
    "View": "Ansehen",
    "Add": "Hinzufügen",
    "Remove": "Entfernen",
    "Refresh": "Aktualisieren",
    "Export": "Exportieren",
    "Import": "Importieren",
    "Download": "Herunterladen",
    "Upload": "Hochladen",
    "Print": "Drucken",
    "Copy": "Kopieren",
    "Paste": "Einfügen",
    "Duplicate": "Duplizieren",
    "Archive": "Archivieren",
    "Restore": "Wiederherstellen",
    "Approve": "Genehmigen",
    "Reject": "Ablehnen",
    "Analyze": "Analysieren",
    "Configure": "Konfigurieren",
    "Sync": "Synchronisieren",
    "Initialize": "Initialisieren",
    "Terminate": "Beenden",
    "Escalate": "Eskalieren",
    "Execute": "Ausführen",
    
    # Status terms
    "Active": "Aktiv",
    "Inactive": "Inaktiv",
    "Pending": "Ausstehend",
    "Approved": "Genehmigt",
    "Rejected": "Abgelehnt",
    "Draft": "Entwurf",
    "Published": "Veröffentlicht",
    "Completed": "Abgeschlossen",
    "In Progress": "In Bearbeitung",
    "Not Started": "Nicht gestartet",
    "On Hold": "Pausiert",
    "Cancelled": "Storniert",
    "Open": "Offen",
    "Closed": "Geschlossen",
    "Resolved": "Gelöst",
    "Overdue": "Überfällig",
    "Scheduled": "Geplant",
    "Running": "Läuft",
    "Stopped": "Gestoppt",
    "Failed": "Fehlgeschlagen",
    "Won": "Gewonnen",
    "Lost": "Verloren",
    
    # Priority terms
    "Critical": "Kritisch",
    "High": "Hoch",
    "Medium": "Mittel",
    "Low": "Niedrig",
    "Normal": "Normal",
    "Urgent": "Dringend",
    
    # Time terms
    "Today": "Heute",
    "Yesterday": "Gestern",
    "Tomorrow": "Morgen",
    "This Week": "Diese Woche",
    "Last Week": "Letzte Woche",
    "This Month": "Diesen Monat",
    "Last Month": "Letzten Monat",
    "This Year": "Dieses Jahr",
    "Last Year": "Letztes Jahr",
    "Now": "Jetzt",
    "Never": "Nie",
    "Daily": "Täglich",
    "Weekly": "Wöchentlich",
    "Monthly": "Monatlich",
    "Yearly": "Jährlich",
    
    # Navigation & Layout
    "Dashboard": "Dashboard",
    "Home": "Startseite",
    "Settings": "Einstellungen",
    "Profile": "Profil",
    "Account": "Konto",
    "Security": "Sicherheit",
    "Notifications": "Benachrichtigungen",
    "Help": "Hilfe",
    "About": "Über",
    "Logout": "Abmelden",
    "Login": "Anmelden",
    "Sign In": "Einloggen",
    "Sign Up": "Registrieren",
    "Sign Out": "Ausloggen",
    "Menu": "Menü",
    "Navigation": "Navigation",
    "Sidebar": "Seitenleiste",
    "Header": "Kopfzeile",
    "Footer": "Fußzeile",
    "Overview": "Übersicht",
    "Details": "Details",
    "Summary": "Zusammenfassung",
    
    # Business terms
    "Customer": "Kunde",
    "Customers": "Kunden",
    "Supplier": "Lieferant",
    "Suppliers": "Lieferanten",
    "Vendor": "Anbieter",
    "Partner": "Partner",
    "Employee": "Mitarbeiter",
    "Employees": "Mitarbeiter",
    "Team": "Team",
    "Teams": "Teams",
    "Department": "Abteilung",
    "Organization": "Organisation",
    "Company": "Unternehmen",
    "Order": "Bestellung",
    "Orders": "Bestellungen",
    "Invoice": "Rechnung",
    "Invoices": "Rechnungen",
    "Quote": "Angebot",
    "Quotes": "Angebote",
    "Product": "Produkt",
    "Products": "Produkte",
    "Service": "Dienstleistung",
    "Services": "Dienstleistungen",
    "Project": "Projekt",
    "Projects": "Projekte",
    "Task": "Aufgabe",
    "Tasks": "Aufgaben",
    "Item": "Artikel",
    "Items": "Artikel",
    "Unit": "Einheit",
    "Units": "Einheiten",
    "Quantity": "Menge",
    "Price": "Preis",
    "Amount": "Betrag",
    "Total": "Gesamt",
    "Subtotal": "Zwischensumme",
    "Discount": "Rabatt",
    "Tax": "Steuer",
    "Currency": "Währung",
    "Budget": "Budget",
    "Revenue": "Umsatz",
    "Profit": "Gewinn",
    "Cost": "Kosten",
    "Expense": "Ausgabe",
    "Payment": "Zahlung",
    "Transaction": "Transaktion",
    
    # Manufacturing terms
    "Production": "Produktion",
    "Manufacturing": "Fertigung",
    "Assembly": "Montage",
    "Quality": "Qualität",
    "Inspection": "Prüfung",
    "Maintenance": "Wartung",
    "Inventory": "Bestand",
    "Warehouse": "Lager",
    "Stock": "Lagerbestand",
    "Shipment": "Lieferung",
    "Delivery": "Lieferung",
    "Work Order": "Fertigungsauftrag",
    "Work Orders": "Fertigungsaufträge",
    "Bill of Materials": "Stückliste",
    "BOM": "Stückliste",
    "Routing": "Arbeitsplan",
    "Operation": "Arbeitsgang",
    "Workstation": "Arbeitsplatz",
    "Machine": "Maschine",
    "Equipment": "Ausrüstung",
    "Downtime": "Stillstandzeit",
    "Yield": "Ausbeute",
    "Scrap": "Ausschuss",
    "Defect": "Mangel",
    "Rework": "Nacharbeit",
    "Capacity": "Kapazität",
    "Throughput": "Durchsatz",
    "Lead Time": "Durchlaufzeit",
    "Cycle Time": "Zykluszeit",
    "Setup Time": "Rüstzeit",
    "Batch": "Charge",
    "Lot": "Los",
    "Serial Number": "Seriennummer",
    "Traceability": "Rückverfolgbarkeit",
    
    # Analytics terms
    "Analytics": "Analytik",
    "Report": "Bericht",
    "Reports": "Berichte",
    "Chart": "Diagramm",
    "Graph": "Grafik",
    "Metric": "Kennzahl",
    "Metrics": "Kennzahlen",
    "KPI": "KPI",
    "Indicator": "Indikator",
    "Trend": "Trend",
    "Forecast": "Prognose",
    "Prediction": "Vorhersage",
    "Analysis": "Analyse",
    "Insight": "Erkenntnis",
    "Intelligence": "Intelligenz",
    "Performance": "Leistung",
    "Efficiency": "Effizienz",
    "Productivity": "Produktivität",
    
    # IT terms
    "System": "System",
    "Systems": "Systeme",
    "Server": "Server",
    "Network": "Netzwerk",
    "Database": "Datenbank",
    "API": "API",
    "Integration": "Integration",
    "Webhook": "Webhook",
    "Node": "Knoten",
    "Protocol": "Protokoll",
    "Connection": "Verbindung",
    "Session": "Sitzung",
    "Authentication": "Authentifizierung",
    "Authorization": "Autorisierung",
    "Permission": "Berechtigung",
    "Role": "Rolle",
    "User": "Benutzer",
    "Admin": "Administrator",
    "Configuration": "Konfiguration",
    "Backup": "Sicherung",
    "Log": "Protokoll",
    "Audit": "Audit",
    "Monitoring": "Überwachung",
    "Alert": "Warnung",
    "Notification": "Benachrichtigung",
    
    # Form fields
    "Name": "Name",
    "Description": "Beschreibung",
    "Title": "Titel",
    "Email": "E-Mail",
    "Phone": "Telefon",
    "Address": "Adresse",
    "City": "Stadt",
    "Country": "Land",
    "Date": "Datum",
    "Time": "Zeit",
    "Start Date": "Startdatum",
    "End Date": "Enddatum",
    "Due Date": "Fälligkeitsdatum",
    "Created": "Erstellt",
    "Updated": "Aktualisiert",
    "Modified": "Geändert",
    "By": "Von",
    "From": "Von",
    "To": "An",
    "Status": "Status",
    "Type": "Typ",
    "Category": "Kategorie",
    "Tags": "Tags",
    "Notes": "Notizen",
    "Comments": "Kommentare",
    "Attachments": "Anhänge",
    "Required": "Erforderlich",
    "Optional": "Optional",
    
    # Table/List terms
    "No data available": "Keine Daten verfügbar",
    "No results found": "Keine Ergebnisse gefunden",
    "Showing": "Zeige",
    "of": "von",
    "results": "Ergebnisse",
    "per page": "pro Seite",
    "Sort by": "Sortieren nach",
    "Ascending": "Aufsteigend",
    "Descending": "Absteigend",
    "Select All": "Alle auswählen",
    "Deselect All": "Alle abwählen",
    "Selected": "Ausgewählt",
    "Actions": "Aktionen",
    "More": "Mehr",
    "Show More": "Mehr anzeigen",
    "Show Less": "Weniger anzeigen",
    "See All": "Alle anzeigen",
    "View All": "Alle anzeigen",
    "Load More": "Mehr laden",
    
    # Currency
    "Display Currency": "Anzeigewährung",
    "Exchange Rates": "Wechselkurse",
    "Suggested": "Empfohlen",
    "Rate": "Kurs",
    "Sample amount": "Beispielbetrag",
    "Use Suggested": "Empfohlen verwenden",
    "Refresh Rates": "Kurse aktualisieren",
    "Rates synchronized": "Kurse synchronisiert",
    "Using cached rates": "Zwischengespeicherte Kurse",
    "Last updated": "Zuletzt aktualisiert",
}

VERNACULAR_ES = {
    # Common actions and UI
    "Save": "Guardar",
    "Cancel": "Cancelar",
    "Delete": "Eliminar",
    "Edit": "Editar",
    "Create": "Crear",
    "Update": "Actualizar",
    "Search": "Buscar",
    "Filter": "Filtrar",
    "Clear": "Limpiar",
    "Close": "Cerrar",
    "Loading...": "Cargando...",
    "Error": "Error",
    "Success": "Éxito",
    "Warning": "Advertencia",
    "Info": "Información",
    "Yes": "Sí",
    "No": "No",
    "Confirm": "Confirmar",
    "Back": "Atrás",
    "Next": "Siguiente",
    "Previous": "Anterior",
    "Submit": "Enviar",
    "Reset": "Restablecer",
    "View": "Ver",
    "Add": "Agregar",
    "Remove": "Quitar",
    "Refresh": "Actualizar",
    "Export": "Exportar",
    "Import": "Importar",
    "Download": "Descargar",
    "Upload": "Subir",
    "Print": "Imprimir",
    "Copy": "Copiar",
    "Paste": "Pegar",
    "Duplicate": "Duplicar",
    "Archive": "Archivar",
    "Restore": "Restaurar",
    "Approve": "Aprobar",
    "Reject": "Rechazar",
    "Analyze": "Analizar",
    "Configure": "Configurar",
    "Sync": "Sincronizar",
    "Initialize": "Inicializar",
    "Terminate": "Terminar",
    "Escalate": "Escalar",
    "Execute": "Ejecutar",
    
    # Status terms
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Pending": "Pendiente",
    "Approved": "Aprobado",
    "Rejected": "Rechazado",
    "Draft": "Borrador",
    "Published": "Publicado",
    "Completed": "Completado",
    "In Progress": "En progreso",
    "Not Started": "No iniciado",
    "On Hold": "En espera",
    "Cancelled": "Cancelado",
    "Open": "Abierto",
    "Closed": "Cerrado",
    "Resolved": "Resuelto",
    "Overdue": "Vencido",
    "Scheduled": "Programado",
    "Running": "Ejecutando",
    "Stopped": "Detenido",
    "Failed": "Fallido",
    "Won": "Ganado",
    "Lost": "Perdido",
    
    # Priority terms
    "Critical": "Crítico",
    "High": "Alta",
    "Medium": "Media",
    "Low": "Baja",
    "Normal": "Normal",
    "Urgent": "Urgente",
    
    # Time terms
    "Today": "Hoy",
    "Yesterday": "Ayer",
    "Tomorrow": "Mañana",
    "This Week": "Esta semana",
    "Last Week": "Semana pasada",
    "This Month": "Este mes",
    "Last Month": "Mes pasado",
    "This Year": "Este año",
    "Last Year": "Año pasado",
    "Now": "Ahora",
    "Never": "Nunca",
    "Daily": "Diario",
    "Weekly": "Semanal",
    "Monthly": "Mensual",
    "Yearly": "Anual",
    
    # Navigation & Layout
    "Dashboard": "Panel de control",
    "Home": "Inicio",
    "Settings": "Configuración",
    "Profile": "Perfil",
    "Account": "Cuenta",
    "Security": "Seguridad",
    "Notifications": "Notificaciones",
    "Help": "Ayuda",
    "About": "Acerca de",
    "Logout": "Cerrar sesión",
    "Login": "Iniciar sesión",
    "Sign In": "Iniciar sesión",
    "Sign Up": "Registrarse",
    "Sign Out": "Cerrar sesión",
    "Menu": "Menú",
    "Navigation": "Navegación",
    "Sidebar": "Barra lateral",
    "Header": "Encabezado",
    "Footer": "Pie de página",
    "Overview": "Vista general",
    "Details": "Detalles",
    "Summary": "Resumen",
    
    # Business terms
    "Customer": "Cliente",
    "Customers": "Clientes",
    "Supplier": "Proveedor",
    "Suppliers": "Proveedores",
    "Vendor": "Vendedor",
    "Partner": "Socio",
    "Employee": "Empleado",
    "Employees": "Empleados",
    "Team": "Equipo",
    "Teams": "Equipos",
    "Department": "Departamento",
    "Organization": "Organización",
    "Company": "Empresa",
    "Order": "Pedido",
    "Orders": "Pedidos",
    "Invoice": "Factura",
    "Invoices": "Facturas",
    "Quote": "Cotización",
    "Quotes": "Cotizaciones",
    "Product": "Producto",
    "Products": "Productos",
    "Service": "Servicio",
    "Services": "Servicios",
    "Project": "Proyecto",
    "Projects": "Proyectos",
    "Task": "Tarea",
    "Tasks": "Tareas",
    "Item": "Artículo",
    "Items": "Artículos",
    "Unit": "Unidad",
    "Units": "Unidades",
    "Quantity": "Cantidad",
    "Price": "Precio",
    "Amount": "Monto",
    "Total": "Total",
    "Subtotal": "Subtotal",
    "Discount": "Descuento",
    "Tax": "Impuesto",
    "Currency": "Moneda",
    "Budget": "Presupuesto",
    "Revenue": "Ingresos",
    "Profit": "Beneficio",
    "Cost": "Costo",
    "Expense": "Gasto",
    "Payment": "Pago",
    "Transaction": "Transacción",
    
    # Manufacturing terms
    "Production": "Producción",
    "Manufacturing": "Fabricación",
    "Assembly": "Ensamblaje",
    "Quality": "Calidad",
    "Inspection": "Inspección",
    "Maintenance": "Mantenimiento",
    "Inventory": "Inventario",
    "Warehouse": "Almacén",
    "Stock": "Stock",
    "Shipment": "Envío",
    "Delivery": "Entrega",
    "Work Order": "Orden de trabajo",
    "Work Orders": "Órdenes de trabajo",
    "Bill of Materials": "Lista de materiales",
    "BOM": "BOM",
    "Routing": "Ruta de producción",
    "Operation": "Operación",
    "Workstation": "Estación de trabajo",
    "Machine": "Máquina",
    "Equipment": "Equipo",
    "Downtime": "Tiempo de inactividad",
    "Yield": "Rendimiento",
    "Scrap": "Desecho",
    "Defect": "Defecto",
    "Rework": "Retrabajo",
    "Capacity": "Capacidad",
    "Throughput": "Rendimiento",
    "Lead Time": "Tiempo de entrega",
    "Cycle Time": "Tiempo de ciclo",
    "Setup Time": "Tiempo de preparación",
    "Batch": "Lote",
    "Lot": "Lote",
    "Serial Number": "Número de serie",
    "Traceability": "Trazabilidad",
    
    # Analytics terms
    "Analytics": "Análisis",
    "Report": "Informe",
    "Reports": "Informes",
    "Chart": "Gráfico",
    "Graph": "Gráfico",
    "Metric": "Métrica",
    "Metrics": "Métricas",
    "KPI": "KPI",
    "Indicator": "Indicador",
    "Trend": "Tendencia",
    "Forecast": "Pronóstico",
    "Prediction": "Predicción",
    "Analysis": "Análisis",
    "Insight": "Información",
    "Intelligence": "Inteligencia",
    "Performance": "Rendimiento",
    "Efficiency": "Eficiencia",
    "Productivity": "Productividad",
    
    # IT terms
    "System": "Sistema",
    "Systems": "Sistemas",
    "Server": "Servidor",
    "Network": "Red",
    "Database": "Base de datos",
    "API": "API",
    "Integration": "Integración",
    "Webhook": "Webhook",
    "Node": "Nodo",
    "Protocol": "Protocolo",
    "Connection": "Conexión",
    "Session": "Sesión",
    "Authentication": "Autenticación",
    "Authorization": "Autorización",
    "Permission": "Permiso",
    "Role": "Rol",
    "User": "Usuario",
    "Admin": "Administrador",
    "Configuration": "Configuración",
    "Backup": "Respaldo",
    "Log": "Registro",
    "Audit": "Auditoría",
    "Monitoring": "Monitoreo",
    "Alert": "Alerta",
    "Notification": "Notificación",
    
    # Form fields
    "Name": "Nombre",
    "Description": "Descripción",
    "Title": "Título",
    "Email": "Correo electrónico",
    "Phone": "Teléfono",
    "Address": "Dirección",
    "City": "Ciudad",
    "Country": "País",
    "Date": "Fecha",
    "Time": "Hora",
    "Start Date": "Fecha de inicio",
    "End Date": "Fecha de fin",
    "Due Date": "Fecha de vencimiento",
    "Created": "Creado",
    "Updated": "Actualizado",
    "Modified": "Modificado",
    "By": "Por",
    "From": "De",
    "To": "A",
    "Status": "Estado",
    "Type": "Tipo",
    "Category": "Categoría",
    "Tags": "Etiquetas",
    "Notes": "Notas",
    "Comments": "Comentarios",
    "Attachments": "Adjuntos",
    "Required": "Obligatorio",
    "Optional": "Opcional",
    
    # Table/List terms
    "No data available": "No hay datos disponibles",
    "No results found": "No se encontraron resultados",
    "Showing": "Mostrando",
    "of": "de",
    "results": "resultados",
    "per page": "por página",
    "Sort by": "Ordenar por",
    "Ascending": "Ascendente",
    "Descending": "Descendente",
    "Select All": "Seleccionar todo",
    "Deselect All": "Deseleccionar todo",
    "Selected": "Seleccionado",
    "Actions": "Acciones",
    "More": "Más",
    "Show More": "Mostrar más",
    "Show Less": "Mostrar menos",
    "See All": "Ver todo",
    "View All": "Ver todo",
    "Load More": "Cargar más",
    
    # Currency
    "Display Currency": "Moneda de visualización",
    "Exchange Rates": "Tipos de cambio",
    "Suggested": "Sugerido",
    "Rate": "Tasa",
    "Sample amount": "Cantidad de ejemplo",
    "Use Suggested": "Usar sugerido",
    "Refresh Rates": "Actualizar tasas",
    "Rates synchronized": "Tasas sincronizadas",
    "Using cached rates": "Usando tasas en caché",
    "Last updated": "Última actualización",
}

VERNACULAR_AR = {
    # Common actions and UI
    "Save": "حفظ",
    "Cancel": "إلغاء",
    "Delete": "حذف",
    "Edit": "تعديل",
    "Create": "إنشاء",
    "Update": "تحديث",
    "Search": "بحث",
    "Filter": "تصفية",
    "Clear": "مسح",
    "Close": "إغلاق",
    "Loading...": "جاري التحميل...",
    "Error": "خطأ",
    "Success": "نجاح",
    "Warning": "تحذير",
    "Info": "معلومات",
    "Yes": "نعم",
    "No": "لا",
    "Confirm": "تأكيد",
    "Back": "رجوع",
    "Next": "التالي",
    "Previous": "السابق",
    "Submit": "إرسال",
    "Reset": "إعادة تعيين",
    "View": "عرض",
    "Add": "إضافة",
    "Remove": "إزالة",
    "Refresh": "تحديث",
    "Export": "تصدير",
    "Import": "استيراد",
    "Download": "تنزيل",
    "Upload": "رفع",
    "Print": "طباعة",
    "Copy": "نسخ",
    "Paste": "لصق",
    "Duplicate": "تكرار",
    "Archive": "أرشفة",
    "Restore": "استعادة",
    "Approve": "موافقة",
    "Reject": "رفض",
    "Analyze": "تحليل",
    "Configure": "تكوين",
    "Sync": "مزامنة",
    "Initialize": "تهيئة",
    "Terminate": "إنهاء",
    "Escalate": "تصعيد",
    "Execute": "تنفيذ",
    
    # Status terms
    "Active": "نشط",
    "Inactive": "غير نشط",
    "Pending": "قيد الانتظار",
    "Approved": "موافق عليه",
    "Rejected": "مرفوض",
    "Draft": "مسودة",
    "Published": "منشور",
    "Completed": "مكتمل",
    "In Progress": "قيد التنفيذ",
    "Not Started": "لم يبدأ",
    "On Hold": "معلق",
    "Cancelled": "ملغى",
    "Open": "مفتوح",
    "Closed": "مغلق",
    "Resolved": "محلول",
    "Overdue": "متأخر",
    "Scheduled": "مجدول",
    "Running": "قيد التشغيل",
    "Stopped": "متوقف",
    "Failed": "فشل",
    "Won": "فاز",
    "Lost": "خسر",
    
    # Priority terms
    "Critical": "حرج",
    "High": "عالية",
    "Medium": "متوسطة",
    "Low": "منخفضة",
    "Normal": "عادية",
    "Urgent": "عاجل",
    
    # Time terms
    "Today": "اليوم",
    "Yesterday": "أمس",
    "Tomorrow": "غداً",
    "This Week": "هذا الأسبوع",
    "Last Week": "الأسبوع الماضي",
    "This Month": "هذا الشهر",
    "Last Month": "الشهر الماضي",
    "This Year": "هذا العام",
    "Last Year": "العام الماضي",
    "Now": "الآن",
    "Never": "أبداً",
    "Daily": "يومي",
    "Weekly": "أسبوعي",
    "Monthly": "شهري",
    "Yearly": "سنوي",
    
    # Navigation & Layout
    "Dashboard": "لوحة التحكم",
    "Home": "الرئيسية",
    "Settings": "الإعدادات",
    "Profile": "الملف الشخصي",
    "Account": "الحساب",
    "Security": "الأمان",
    "Notifications": "الإشعارات",
    "Help": "المساعدة",
    "About": "حول",
    "Logout": "تسجيل الخروج",
    "Login": "تسجيل الدخول",
    "Sign In": "تسجيل الدخول",
    "Sign Up": "إنشاء حساب",
    "Sign Out": "تسجيل الخروج",
    "Menu": "القائمة",
    "Navigation": "التنقل",
    "Sidebar": "الشريط الجانبي",
    "Header": "الرأس",
    "Footer": "التذييل",
    "Overview": "نظرة عامة",
    "Details": "التفاصيل",
    "Summary": "الملخص",
    
    # Business terms
    "Customer": "عميل",
    "Customers": "العملاء",
    "Supplier": "مورد",
    "Suppliers": "الموردون",
    "Vendor": "بائع",
    "Partner": "شريك",
    "Employee": "موظف",
    "Employees": "الموظفون",
    "Team": "فريق",
    "Teams": "الفرق",
    "Department": "قسم",
    "Organization": "منظمة",
    "Company": "شركة",
    "Order": "طلب",
    "Orders": "الطلبات",
    "Invoice": "فاتورة",
    "Invoices": "الفواتير",
    "Quote": "عرض سعر",
    "Quotes": "عروض الأسعار",
    "Product": "منتج",
    "Products": "المنتجات",
    "Service": "خدمة",
    "Services": "الخدمات",
    "Project": "مشروع",
    "Projects": "المشاريع",
    "Task": "مهمة",
    "Tasks": "المهام",
    "Item": "عنصر",
    "Items": "العناصر",
    "Unit": "وحدة",
    "Units": "الوحدات",
    "Quantity": "الكمية",
    "Price": "السعر",
    "Amount": "المبلغ",
    "Total": "الإجمالي",
    "Subtotal": "المجموع الفرعي",
    "Discount": "خصم",
    "Tax": "ضريبة",
    "Currency": "العملة",
    "Budget": "الميزانية",
    "Revenue": "الإيرادات",
    "Profit": "الربح",
    "Cost": "التكلفة",
    "Expense": "المصروف",
    "Payment": "الدفع",
    "Transaction": "المعاملة",
    
    # Manufacturing terms
    "Production": "الإنتاج",
    "Manufacturing": "التصنيع",
    "Assembly": "التجميع",
    "Quality": "الجودة",
    "Inspection": "الفحص",
    "Maintenance": "الصيانة",
    "Inventory": "المخزون",
    "Warehouse": "المستودع",
    "Stock": "المخزون",
    "Shipment": "الشحنة",
    "Delivery": "التسليم",
    "Work Order": "أمر العمل",
    "Work Orders": "أوامر العمل",
    "Bill of Materials": "قائمة المواد",
    "BOM": "قائمة المواد",
    "Routing": "مسار الإنتاج",
    "Operation": "عملية",
    "Workstation": "محطة العمل",
    "Machine": "آلة",
    "Equipment": "معدات",
    "Downtime": "وقت التوقف",
    "Yield": "العائد",
    "Scrap": "النفايات",
    "Defect": "عيب",
    "Rework": "إعادة العمل",
    "Capacity": "السعة",
    "Throughput": "الإنتاجية",
    "Lead Time": "وقت التسليم",
    "Cycle Time": "وقت الدورة",
    "Setup Time": "وقت الإعداد",
    "Batch": "دفعة",
    "Lot": "دفعة",
    "Serial Number": "الرقم التسلسلي",
    "Traceability": "التتبع",
    
    # Analytics terms
    "Analytics": "التحليلات",
    "Report": "تقرير",
    "Reports": "التقارير",
    "Chart": "رسم بياني",
    "Graph": "رسم بياني",
    "Metric": "مقياس",
    "Metrics": "المقاييس",
    "KPI": "مؤشر الأداء",
    "Indicator": "مؤشر",
    "Trend": "اتجاه",
    "Forecast": "توقعات",
    "Prediction": "تنبؤ",
    "Analysis": "تحليل",
    "Insight": "رؤية",
    "Intelligence": "ذكاء",
    "Performance": "الأداء",
    "Efficiency": "الكفاءة",
    "Productivity": "الإنتاجية",
    
    # IT terms
    "System": "نظام",
    "Systems": "الأنظمة",
    "Server": "خادم",
    "Network": "شبكة",
    "Database": "قاعدة البيانات",
    "API": "واجهة برمجة التطبيقات",
    "Integration": "تكامل",
    "Webhook": "ويب هوك",
    "Node": "عقدة",
    "Protocol": "بروتوكول",
    "Connection": "اتصال",
    "Session": "جلسة",
    "Authentication": "المصادقة",
    "Authorization": "التفويض",
    "Permission": "صلاحية",
    "Role": "دور",
    "User": "مستخدم",
    "Admin": "مسؤول",
    "Configuration": "تكوين",
    "Backup": "نسخ احتياطي",
    "Log": "سجل",
    "Audit": "تدقيق",
    "Monitoring": "مراقبة",
    "Alert": "تنبيه",
    "Notification": "إشعار",
    
    # Form fields
    "Name": "الاسم",
    "Description": "الوصف",
    "Title": "العنوان",
    "Email": "البريد الإلكتروني",
    "Phone": "الهاتف",
    "Address": "العنوان",
    "City": "المدينة",
    "Country": "البلد",
    "Date": "التاريخ",
    "Time": "الوقت",
    "Start Date": "تاريخ البدء",
    "End Date": "تاريخ الانتهاء",
    "Due Date": "تاريخ الاستحقاق",
    "Created": "تم الإنشاء",
    "Updated": "تم التحديث",
    "Modified": "تم التعديل",
    "By": "بواسطة",
    "From": "من",
    "To": "إلى",
    "Status": "الحالة",
    "Type": "النوع",
    "Category": "الفئة",
    "Tags": "الوسوم",
    "Notes": "ملاحظات",
    "Comments": "التعليقات",
    "Attachments": "المرفقات",
    "Required": "مطلوب",
    "Optional": "اختياري",
    
    # Table/List terms
    "No data available": "لا توجد بيانات",
    "No results found": "لم يتم العثور على نتائج",
    "Showing": "عرض",
    "of": "من",
    "results": "النتائج",
    "per page": "لكل صفحة",
    "Sort by": "ترتيب حسب",
    "Ascending": "تصاعدي",
    "Descending": "تنازلي",
    "Select All": "تحديد الكل",
    "Deselect All": "إلغاء تحديد الكل",
    "Selected": "محدد",
    "Actions": "الإجراءات",
    "More": "المزيد",
    "Show More": "عرض المزيد",
    "Show Less": "عرض أقل",
    "See All": "عرض الكل",
    "View All": "عرض الكل",
    "Load More": "تحميل المزيد",
    
    # Currency
    "Display Currency": "عملة العرض",
    "Exchange Rates": "أسعار الصرف",
    "Suggested": "مقترح",
    "Rate": "السعر",
    "Sample amount": "مبلغ العينة",
    "Use Suggested": "استخدام المقترح",
    "Refresh Rates": "تحديث الأسعار",
    "Rates synchronized": "تم مزامنة الأسعار",
    "Using cached rates": "استخدام الأسعار المخزنة",
    "Last updated": "آخر تحديث",
}


def flatten_json(data: dict, parent_key: str = '', sep: str = '.') -> dict:
    """Flatten a nested JSON structure into dot-notation keys."""
    items = []
    for k, v in data.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_json(v, new_key, sep).items())
        else:
            items.append((new_key, v))
    return dict(items)


def unflatten_json(data: dict, sep: str = '.') -> dict:
    """Convert dot-notation keys back to nested structure."""
    result = {}
    for key, value in data.items():
        parts = key.split(sep)
        d = result
        for part in parts[:-1]:
            if part not in d:
                d[part] = {}
            d = d[part]
        d[parts[-1]] = value
    return result


def translate_value(value: str, dictionary: dict) -> str:
    """
    Translate a value using the vernacular dictionary.
    Handles exact matches, partial matches, and preserves placeholders.
    """
    if not isinstance(value, str):
        return value
    
    # Check for exact match first
    if value in dictionary:
        return dictionary[value]
    
    # Check for case-insensitive match
    value_lower = value.lower()
    for k, v in dictionary.items():
        if k.lower() == value_lower:
            # Preserve original casing pattern
            if value.isupper():
                return v.upper()
            elif value[0].isupper():
                return v[0].upper() + v[1:] if len(v) > 1 else v.upper()
            return v
    
    # Handle compound phrases
    result = value
    # Sort by length (longest first) to avoid partial replacements
    sorted_terms = sorted(dictionary.items(), key=lambda x: len(x[0]), reverse=True)
    
    for english, translated in sorted_terms:
        # Use word boundaries to avoid partial word matches
        pattern = r'\b' + re.escape(english) + r'\b'
        if re.search(pattern, result, re.IGNORECASE):
            # Preserve casing
            def replace_with_case(match):
                matched = match.group(0)
                if matched.isupper():
                    return translated.upper()
                elif matched[0].isupper():
                    return translated[0].upper() + translated[1:] if len(translated) > 1 else translated.upper()
                return translated
            result = re.sub(pattern, replace_with_case, result, flags=re.IGNORECASE)
    
    return result


def translate_locale(en_data: dict, target_locale: str, dictionary: dict) -> dict:
    """Translate all values in the English locale to the target language."""
    result = {}
    
    flat_en = flatten_json(en_data)
    
    for key, value in flat_en.items():
        # Skip meta section
        if key.startswith('meta.'):
            continue
        
        if isinstance(value, str):
            translated = translate_value(value, dictionary)
            result[key] = translated
        else:
            result[key] = value
    
    return unflatten_json(result)


def update_locale_file(locale_path: Path, en_data: dict, dictionary: dict, locale_code: str):
    """Update a locale file with vernacular translations."""
    
    # Load existing locale data
    with open(locale_path, 'r', encoding='utf-8') as f:
        locale_data = json.load(f)
    
    # Flatten both
    flat_en = flatten_json(en_data)
    flat_locale = flatten_json(locale_data)
    
    updated_count = 0
    
    for key, en_value in flat_en.items():
        if key.startswith('meta.'):
            continue
            
        if key in flat_locale:
            current_value = flat_locale[key]
            
            # Only translate if current value equals English (placeholder)
            if current_value == en_value and isinstance(en_value, str):
                translated = translate_value(en_value, dictionary)
                if translated != en_value:
                    flat_locale[key] = translated
                    updated_count += 1
    
    # Unflatten and save
    result = unflatten_json(flat_locale)
    
    # Preserve original meta
    if 'meta' in locale_data:
        result['meta'] = locale_data['meta']
    
    with open(locale_path, 'w', encoding='utf-8') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    
    return updated_count


def main():
    locales_dir = Path(__file__).parent.parent / 'src' / 'locales'
    
    # Load English as reference
    en_path = locales_dir / 'en.json'
    with open(en_path, 'r', encoding='utf-8') as f:
        en_data = json.load(f)
    
    print("🌍 Applying vernacular translations...")
    print(f"   English has {len(flatten_json(en_data))} keys\n")
    
    locales = [
        ('fr', VERNACULAR_FR, 'French'),
        ('de', VERNACULAR_DE, 'German'),
        ('es', VERNACULAR_ES, 'Spanish'),
        ('ar', VERNACULAR_AR, 'Arabic'),
    ]
    
    total_updated = 0
    
    for code, dictionary, name in locales:
        locale_path = locales_dir / f'{code}.json'
        if locale_path.exists():
            count = update_locale_file(locale_path, en_data, dictionary, code)
            print(f"   {name} ({code}): {count} translations updated")
            total_updated += count
        else:
            print(f"   ⚠️  {name} ({code}): File not found")
    
    print(f"\n✅ Vernacular translation complete!")
    print(f"   Total translations updated: {total_updated}")
    print("\n⚠️  NOTE: Some specialized terms may need manual review.")


if __name__ == '__main__':
    main()
