"""add project management system

Revision ID: cc096eda932a
Revises: 16348c26f8db
Create Date: 2026-01-11 01:24:52.282728+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cc096eda932a"
down_revision: Union[str, None] = "16348c26f8db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("project_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_end_date", sa.Date(), nullable=True),
        sa.Column("actual_end_date", sa.Date(), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("default_story_points", sa.Integer(), nullable=True),
        sa.Column("sprint_duration_days", sa.Integer(), nullable=False),
        sa.Column("use_story_points", sa.Boolean(), nullable=False),
        sa.Column("use_time_tracking", sa.Boolean(), nullable=False),
        sa.Column("enable_watchers", sa.Boolean(), nullable=False),
        sa.Column("enable_wiki", sa.Boolean(), nullable=False),
        sa.Column("enable_issues", sa.Boolean(), nullable=False),
        sa.Column("enable_sprints", sa.Boolean(), nullable=False),
        sa.Column(
            "custom_user_story_statuses", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("custom_task_statuses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("custom_issue_statuses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related_rfq_id", sa.UUID(), nullable=True),
        sa.Column("related_work_order_id", sa.Integer(), nullable=True),
        sa.Column("related_a3_id", sa.UUID(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_user_stories", sa.Integer(), nullable=False),
        sa.Column("completed_user_stories", sa.Integer(), nullable=False),
        sa.Column("total_story_points", sa.Integer(), nullable=False),
        sa.Column("completed_story_points", sa.Integer(), nullable=False),
        sa.Column("total_issues", sa.Integer(), nullable=False),
        sa.Column("open_issues", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["related_a3_id"], ["a3s.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["related_rfq_id"], ["rfqs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["related_work_order_id"], ["work_orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_index("ix_projects_owner_status", "projects", ["owner_id", "status"], unique=False)
    op.create_index(op.f("ix_projects_project_type"), "projects", ["project_type"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index("ix_projects_type_status", "projects", ["project_type", "status"], unique=False)
    op.create_table(
        "board_views",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("board_type", sa.String(length=50), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("columns", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("swimlanes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_board_views_project_id"), "board_views", ["project_id"], unique=False)
    op.create_index(
        "ix_board_views_project_user", "board_views", ["project_id", "user_id"], unique=False
    )
    op.create_index(op.f("ix_board_views_user_id"), "board_views", ["user_id"], unique=False)
    op.create_table(
        "epics",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("ref", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("watchers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("custom_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "ref", name="uq_epic_project_ref"),
    )
    op.create_index(op.f("ix_epics_owner_id"), "epics", ["owner_id"], unique=False)
    op.create_index(op.f("ix_epics_project_id"), "epics", ["project_id"], unique=False)
    op.create_index("ix_epics_project_status", "epics", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_epics_status"), "epics", ["status"], unique=False)
    op.create_table(
        "milestones",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("milestone_type", sa.String(length=50), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("closed_items", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "slug", name="uq_milestone_project_slug"),
    )
    op.create_index(
        "ix_milestones_project_due", "milestones", ["project_id", "due_date"], unique=False
    )
    op.create_index(op.f("ix_milestones_project_id"), "milestones", ["project_id"], unique=False)
    op.create_table(
        "project_activities",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("activity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("entity_ref", sa.Integer(), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_activities_activity_type"),
        "project_activities",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        "ix_project_activities_project_created",
        "project_activities",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_activities_project_id"), "project_activities", ["project_id"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("can_edit", sa.Boolean(), nullable=False),
        sa.Column("can_comment", sa.Boolean(), nullable=False),
        sa.Column("can_invite", sa.Boolean(), nullable=False),
        sa.Column("can_delete", sa.Boolean(), nullable=False),
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        sa.Column("push_notifications", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "user_id", "id"),
    )
    op.create_table(
        "sprints",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("retrospective_notes", sa.Text(), nullable=True),
        sa.Column("planned_points", sa.Integer(), nullable=False),
        sa.Column("completed_points", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "slug", name="uq_sprint_project_slug"),
    )
    op.create_index(op.f("ix_sprints_project_id"), "sprints", ["project_id"], unique=False)
    op.create_index("ix_sprints_project_status", "sprints", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_sprints_status"), "sprints", ["status"], unique=False)
    op.create_table(
        "wiki_pages",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("page_type", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("watchers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["wiki_pages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "slug", name="uq_wiki_page_project_slug"),
    )
    op.create_index(op.f("ix_wiki_pages_project_id"), "wiki_pages", ["project_id"], unique=False)
    op.create_table(
        "issues",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("ref", sa.Integer(), nullable=False),
        sa.Column("milestone_id", sa.UUID(), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("issue_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("assigned_to_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("finished_date", sa.Date(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("watchers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("custom_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related_nc_id", sa.Integer(), nullable=True),
        sa.Column("related_capa_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_to_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["milestone_id"], ["milestones.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["related_capa_id"], ["capas.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["related_nc_id"], ["non_conformances.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "ref", name="uq_issue_project_ref"),
    )
    op.create_index("ix_issues_assigned", "issues", ["assigned_to_id"], unique=False)
    op.create_index(op.f("ix_issues_assigned_to_id"), "issues", ["assigned_to_id"], unique=False)
    op.create_index(op.f("ix_issues_issue_type"), "issues", ["issue_type"], unique=False)
    op.create_index(op.f("ix_issues_milestone_id"), "issues", ["milestone_id"], unique=False)
    op.create_index(op.f("ix_issues_priority"), "issues", ["priority"], unique=False)
    op.create_index(op.f("ix_issues_project_id"), "issues", ["project_id"], unique=False)
    op.create_index("ix_issues_project_status", "issues", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_issues_severity"), "issues", ["severity"], unique=False)
    op.create_index(op.f("ix_issues_status"), "issues", ["status"], unique=False)
    op.create_table(
        "user_stories",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("ref", sa.Integer(), nullable=False),
        sa.Column("epic_id", sa.UUID(), nullable=True),
        sa.Column("sprint_id", sa.UUID(), nullable=True),
        sa.Column("milestone_id", sa.UUID(), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("as_a", sa.String(length=255), nullable=True),
        sa.Column("i_want", sa.Text(), nullable=True),
        sa.Column("so_that", sa.Text(), nullable=True),
        sa.Column("acceptance_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("assigned_users", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("story_points", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("backlog_order", sa.Integer(), nullable=False),
        sa.Column("sprint_order", sa.Integer(), nullable=False),
        sa.Column("kanban_order", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("blocked_note", sa.Text(), nullable=True),
        sa.Column("estimated_hours", sa.Float(), nullable=True),
        sa.Column("actual_hours", sa.Float(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("watchers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("custom_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("related_work_order_id", sa.Integer(), nullable=True),
        sa.Column("related_ctq_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["epic_id"], ["epics.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["milestone_id"], ["milestones.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["related_ctq_id"], ["ctqs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["related_work_order_id"], ["work_orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sprint_id"], ["sprints.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "ref", name="uq_user_story_project_ref"),
    )
    op.create_index("ix_user_stories_epic", "user_stories", ["epic_id"], unique=False)
    op.create_index(op.f("ix_user_stories_epic_id"), "user_stories", ["epic_id"], unique=False)
    op.create_index(
        op.f("ix_user_stories_milestone_id"), "user_stories", ["milestone_id"], unique=False
    )
    op.create_index("ix_user_stories_owner", "user_stories", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_user_stories_project_id"), "user_stories", ["project_id"], unique=False
    )
    op.create_index(
        "ix_user_stories_project_status", "user_stories", ["project_id", "status"], unique=False
    )
    op.create_index("ix_user_stories_sprint", "user_stories", ["sprint_id"], unique=False)
    op.create_index(op.f("ix_user_stories_sprint_id"), "user_stories", ["sprint_id"], unique=False)
    op.create_index(op.f("ix_user_stories_status"), "user_stories", ["status"], unique=False)
    op.create_table(
        "issue_comments",
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mentions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_issue_comments_issue_id"), "issue_comments", ["issue_id"], unique=False
    )
    op.create_table(
        "story_comments",
        sa.Column("user_story_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mentions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_story_id"], ["user_stories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_comments_user_story_id"), "story_comments", ["user_story_id"], unique=False
    )
    op.create_table(
        "story_history",
        sa.Column("user_story_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_story_id"], ["user_stories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_history_user_story_id"), "story_history", ["user_story_id"], unique=False
    )
    op.create_table(
        "subtasks",
        sa.Column("user_story_id", sa.UUID(), nullable=False),
        sa.Column("ref", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assigned_to_id", sa.UUID(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_hours", sa.Float(), nullable=True),
        sa.Column("actual_hours", sa.Float(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_to_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_story_id"], ["user_stories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_story_id", "ref", name="uq_subtask_story_ref"),
    )
    op.create_index(op.f("ix_subtasks_user_story_id"), "subtasks", ["user_story_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subtasks_user_story_id"), table_name="subtasks")
    op.drop_table("subtasks")
    op.drop_index(op.f("ix_story_history_user_story_id"), table_name="story_history")
    op.drop_table("story_history")
    op.drop_index(op.f("ix_story_comments_user_story_id"), table_name="story_comments")
    op.drop_table("story_comments")
    op.drop_index(op.f("ix_issue_comments_issue_id"), table_name="issue_comments")
    op.drop_table("issue_comments")
    op.drop_index(op.f("ix_user_stories_status"), table_name="user_stories")
    op.drop_index(op.f("ix_user_stories_sprint_id"), table_name="user_stories")
    op.drop_index("ix_user_stories_sprint", table_name="user_stories")
    op.drop_index("ix_user_stories_project_status", table_name="user_stories")
    op.drop_index(op.f("ix_user_stories_project_id"), table_name="user_stories")
    op.drop_index("ix_user_stories_owner", table_name="user_stories")
    op.drop_index(op.f("ix_user_stories_milestone_id"), table_name="user_stories")
    op.drop_index(op.f("ix_user_stories_epic_id"), table_name="user_stories")
    op.drop_index("ix_user_stories_epic", table_name="user_stories")
    op.drop_table("user_stories")
    op.drop_index(op.f("ix_issues_status"), table_name="issues")
    op.drop_index(op.f("ix_issues_severity"), table_name="issues")
    op.drop_index("ix_issues_project_status", table_name="issues")
    op.drop_index(op.f("ix_issues_project_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_priority"), table_name="issues")
    op.drop_index(op.f("ix_issues_milestone_id"), table_name="issues")
    op.drop_index(op.f("ix_issues_issue_type"), table_name="issues")
    op.drop_index(op.f("ix_issues_assigned_to_id"), table_name="issues")
    op.drop_index("ix_issues_assigned", table_name="issues")
    op.drop_table("issues")
    op.drop_index(op.f("ix_wiki_pages_project_id"), table_name="wiki_pages")
    op.drop_table("wiki_pages")
    op.drop_index(op.f("ix_sprints_status"), table_name="sprints")
    op.drop_index("ix_sprints_project_status", table_name="sprints")
    op.drop_index(op.f("ix_sprints_project_id"), table_name="sprints")
    op.drop_table("sprints")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_project_activities_project_id"), table_name="project_activities")
    op.drop_index("ix_project_activities_project_created", table_name="project_activities")
    op.drop_index(op.f("ix_project_activities_activity_type"), table_name="project_activities")
    op.drop_table("project_activities")
    op.drop_index(op.f("ix_milestones_project_id"), table_name="milestones")
    op.drop_index("ix_milestones_project_due", table_name="milestones")
    op.drop_table("milestones")
    op.drop_index(op.f("ix_epics_status"), table_name="epics")
    op.drop_index("ix_epics_project_status", table_name="epics")
    op.drop_index(op.f("ix_epics_project_id"), table_name="epics")
    op.drop_index(op.f("ix_epics_owner_id"), table_name="epics")
    op.drop_table("epics")
    op.drop_index(op.f("ix_board_views_user_id"), table_name="board_views")
    op.drop_index("ix_board_views_project_user", table_name="board_views")
    op.drop_index(op.f("ix_board_views_project_id"), table_name="board_views")
    op.drop_table("board_views")
    op.drop_index("ix_projects_type_status", table_name="projects")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_project_type"), table_name="projects")
    op.drop_index("ix_projects_owner_status", table_name="projects")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
