'use client';

import * as React from 'react';
import {
  TrendingUp,
  TrendingDown,
  Brain,
  Target,
  AlertTriangle,
  CheckCircle2,
  Clock,
  Users,
  BarChart3,
  LineChart,
  PieChart,
  Zap,
  Activity,
  Eye,
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { useAnalyticsStore } from '@/stores';
import { MLInsight, PerformanceTrend } from '@/api/analytics';
import { cn } from '@/lib/utils';

export default function AnalyticsPage() {
  const [selectedPeriod, setSelectedPeriod] = React.useState('7d');
  
  const { insights, trends, health, loading, fetchInsights, fetchTrends, fetchHealth } = useAnalyticsStore();

  React.useEffect(() => {
    fetchInsights();
    fetchTrends();
    fetchHealth();
  }, [fetchInsights, fetchTrends, fetchHealth]);

  return (
    <div className="space-y-6" data-testid="analytics-page">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Advanced Analytics</h1>
          <p className="text-muted-foreground">AI-driven insights and predictive performance metrics</p>
        </div>
        <div className="flex items-center gap-2">
          <Select value={selectedPeriod} onValueChange={setSelectedPeriod}>
            <SelectTrigger className="w-[150px]">
              <SelectValue placeholder="Select period" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="24h">Last 24 hours</SelectItem>
              <SelectItem value="7d">Last 7 days</SelectItem>
              <SelectItem value="30d">Last 30 days</SelectItem>
              <SelectItem value="90d">Last 90 days</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="outline" className="gap-2">
            <Zap className="h-4 w-4" />
            Recalculate
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {trends.slice(0, 4).map((trend, i) => (
          <Card key={i}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">{trend.metric}</CardTitle>
              {trend.trend === 'up' ? (
                <TrendingUp className="h-4 w-4 text-green-500" />
              ) : trend.trend === 'down' ? (
                <TrendingDown className="h-4 w-4 text-red-500" />
              ) : (
                <Activity className="h-4 w-4 text-blue-500" />
              )}
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{trend.current_value}%</div>
              <p className="text-xs text-muted-foreground">
                <span className={trend.trend === 'up' ? 'text-green-500' : 'text-red-500'}>
                  {trend.change_percent > 0 ? '+' : ''}{trend.change_percent}%
                </span>{' '}
                from previous period
              </p>
              <div className="mt-4 flex items-center gap-2">
                <Badge variant="outline" className="font-normal text-[10px]">PREDICTION</Badge>
                <span className="text-xs font-medium">{trend.prediction_7d}% in 7 days</span>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card className="md:col-span-2">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Brain className="h-5 w-5 text-indigo-500" />
              AI Insights & Predictions
            </CardTitle>
            <CardDescription>
              Actionable recommendations generated by Sensei ML models
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {loading ? (
                <div className="py-12 text-center text-muted-foreground">Loading AI insights...</div>
              ) : (
                insights.map((insight) => (
                  <div key={insight.id} className="p-4 border rounded-lg hover:bg-muted/30 transition-colors">
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <Badge variant={
                          insight.type === 'anomaly' ? 'destructive' :
                          insight.type === 'prediction' ? 'warning' :
                          'default'
                        }>
                          {insight.type.toUpperCase()}
                        </Badge>
                        <h4 className="font-semibold">{insight.title}</h4>
                      </div>
                      <Badge variant="outline">
                        {(insight.confidence * 100).toFixed(0)}% confidence
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mb-4">{insight.description}</p>
                    {insight.action_items && (
                      <div className="space-y-2">
                        <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Recommended Actions</p>
                        <ul className="grid gap-2 sm:grid-cols-2">
                          {insight.action_items.map((item, idx) => (
                            <li key={idx} className="text-xs flex items-center gap-2">
                              <Target className="h-3 w-3 text-indigo-500" />
                              {item}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Model Performance</CardTitle>
            <CardDescription>Sensei OS model health</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {loading ? (
                <div className="py-8 text-center text-muted-foreground text-xs">Loading health data...</div>
              ) : health?.models ? (
                Object.entries(health.models).map(([name, data]: [string, any]) => (
                  <div key={name} className="space-y-2">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-muted-foreground capitalize">{name.replace('_', ' ')}</span>
                      <span className="font-medium">{(data.accuracy * 100).toFixed(1)}% {data.metric || 'accuracy'}</span>
                    </div>
                    <Progress value={data.accuracy * 100} className="h-1.5" />
                  </div>
                ))
              ) : (
                <>
                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-muted-foreground">Quote Predictor</span>
                      <span className="font-medium">92.4% accuracy</span>
                    </div>
                    <Progress value={92.4} className="h-1.5" />
                  </div>
                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-muted-foreground">CBM Predictor</span>
                      <span className="font-medium">88.7% F1 score</span>
                    </div>
                    <Progress value={88.7} className="h-1.5" />
                  </div>
                </>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// Types
interface MLInsight {
  id: string;
  type: 'prediction' | 'anomaly' | 'recommendation' | 'trend';
  title: string;
  description: string;
  confidence: number;
  impact: 'high' | 'medium' | 'low';
  category: string;
  created_at: string;
  model_name: string;
  action_items?: string[];
}

interface PerformanceTrend {
  metric: string;
  current_value: number;
  previous_value: number;
  change_percent: number;
  trend: 'up' | 'down' | 'stable';
  prediction_7d: number;
  prediction_30d: number;
}

interface ModelPerformance {
  model_name: string;
  accuracy: number;
  precision: number;
  recall: number;
  f1_score: number;
  latency_ms: number;
  predictions_today: number;
  status: 'healthy' | 'warning' | 'critical';
}

export default function AnalyticsPage() {
  const [selectedPeriod, setSelectedPeriod] = React.useState('7d');
  const [activeTab, setActiveTab] = React.useState('overview');

  // Mock ML Insights
  const [insights, setInsights] = React.useState<MLInsight[]>([
    {
      id: '1',
      type: 'prediction',
      title: 'Quote Success Rate Declining',
      description: 'ML model predicts 15% drop in quote win rate over next 30 days based on current pipeline trends.',
      confidence: 0.87,
      impact: 'high',
      category: 'Sales',
      created_at: '2026-01-08T09:00:00Z',
      model_name: 'quote_win_predictor',
      action_items: [
        'Review pricing strategy for industrial sector',
        'Increase follow-up frequency with prospects',
        'Focus on high-value opportunities'
      ],
    },
    {
      id: '2',
      type: 'anomaly',
      title: 'Unusual Production Downtime Pattern',
      description: 'Machine #3 showing 23% increase in unplanned stops. Pattern suggests preventive maintenance needed.',
      confidence: 0.92,
      impact: 'high',
      category: 'Production',
      created_at: '2026-01-08T07:30:00Z',
      model_name: 'cbm_predictor',
      action_items: [
        'Schedule inspection for CNC Machine #3',
        'Check spindle bearing condition',
        'Review maintenance logs'
      ],
    },
    {
      id: '3',
      type: 'recommendation',
      title: 'Optimize Training Schedule',
      description: 'AI recommends shifting forklift training to Tuesday afternoons based on historical completion rates (+28%).',
      confidence: 0.78,
      impact: 'medium',
      category: 'Training',
      created_at: '2026-01-08T06:00:00Z',
      model_name: 'learning_optimizer',
    },
    {
      id: '4',
      type: 'trend',
      title: 'Quality Metrics Improving',
      description: 'First-pass yield trending up 12% over last 30 days. Countermeasures from A3-2024-008 are effective.',
      confidence: 0.95,
      impact: 'medium',
      category: 'Quality',
      created_at: '2026-01-07T14:00:00Z',
      model_name: 'quality_trend_analyzer',
    },
  ]);

  // Mock Performance Trends
  const [trends, setTrends] = React.useState<PerformanceTrend[]>([
    {
      metric: 'Quote Win Rate',
      current_value: 42.5,
      previous_value: 45.2,
      change_percent: -5.97,
      trend: 'down',
      prediction_7d: 41.8,
      prediction_30d: 38.3,
    },
    {
      metric: 'First Pass Yield',
      current_value: 94.2,
      previous_value: 89.8,
      change_percent: 4.90,
      trend: 'up',
      prediction_7d: 95.1,
      prediction_30d: 96.5,
    },
    {
      metric: 'OTD (On-Time Delivery)',
      current_value: 88.7,
      previous_value: 87.9,
      change_percent: 0.91,
      trend: 'up',
      prediction_7d: 89.2,
      prediction_30d: 90.5,
    },
    {
      metric: 'Training Completion',
      current_value: 91.3,
      previous_value: 91.1,
      change_percent: 0.22,
      trend: 'stable',
      prediction_7d: 91.5,
      prediction_30d: 92.0,
    },
  ]);

  // Mock Model Performance
  const [models, setModels] = React.useState<ModelPerformance[]>([
    {
      model_name: 'Quote Win Predictor',
      accuracy: 0.847,
      precision: 0.821,
      recall: 0.869,
      f1_score: 0.844,
      latency_ms: 23.5,
      predictions_today: 47,
      status: 'healthy',
    },
    {
      model_name: 'CBM Failure Predictor',
      accuracy: 0.923,
      precision: 0.905,
      recall: 0.941,
      f1_score: 0.922,
      latency_ms: 18.2,
      predictions_today: 156,
      status: 'healthy',
    },
    {
      model_name: 'Learning Recommender',
      accuracy: 0.782,
      precision: 0.756,
      recall: 0.811,
      f1_score: 0.782,
      latency_ms: 31.7,
      predictions_today: 89,
      status: 'warning',
    },
    {
      model_name: 'Quality Trend Analyzer',
      accuracy: 0.891,
      precision: 0.873,
      recall: 0.908,
      f1_score: 0.890,
      latency_ms: 15.3,
      predictions_today: 234,
      status: 'healthy',
    },
  ]);

  const getInsightIcon = (type: MLInsight['type']) => {
    const icons = {
      prediction: TrendingUp,
      anomaly: AlertTriangle,
      recommendation: Target,
      trend: LineChart,
    };
    return icons[type] || Brain;
  };

  const getImpactColor = (impact: string) => {
    const colors = {
      high: 'bg-red-100 text-red-700 border-red-200',
      medium: 'bg-yellow-100 text-yellow-700 border-yellow-200',
      low: 'bg-blue-100 text-blue-700 border-blue-200',
    };
    return colors[impact as keyof typeof colors] || colors.low;
  };

  const getModelStatusColor = (status: string) => {
    const colors = {
      healthy: 'text-green-600',
      warning: 'text-yellow-600',
      critical: 'text-red-600',
    };
    return colors[status as keyof typeof colors] || colors.healthy;
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Brain className="h-6 w-6 text-primary" />
            AI-Powered Analytics
          </h1>
          <p className="text-muted-foreground">
            Machine learning insights and predictive analytics
          </p>
        </div>
        <Select value={selectedPeriod} onValueChange={setSelectedPeriod}>
          <SelectTrigger className="w-32">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="24h">24 Hours</SelectItem>
            <SelectItem value="7d">7 Days</SelectItem>
            <SelectItem value="30d">30 Days</SelectItem>
            <SelectItem value="90d">90 Days</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Key Metrics */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active Models</CardTitle>
            <Brain className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{models.length}</div>
            <p className="text-xs text-muted-foreground">
              {models.filter(m => m.status === 'healthy').length} healthy
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">ML Insights</CardTitle>
            <Zap className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{insights.length}</div>
            <p className="text-xs text-muted-foreground">
              {insights.filter(i => i.impact === 'high').length} high priority
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Predictions Today</CardTitle>
            <Activity className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {models.reduce((sum, m) => sum + m.predictions_today, 0)}
            </div>
            <p className="text-xs text-muted-foreground">
              Across all models
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Avg Accuracy</CardTitle>
            <Target className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {(models.reduce((sum, m) => sum + m.accuracy, 0) / models.length * 100).toFixed(1)}%
            </div>
            <p className="text-xs text-muted-foreground">
              Model performance
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="insights">ML Insights</TabsTrigger>
          <TabsTrigger value="trends">Predictive Trends</TabsTrigger>
          <TabsTrigger value="models">Model Performance</TabsTrigger>
        </TabsList>

        {/* Overview Tab */}
        <TabsContent value="overview" className="space-y-4">
          {/* Top Insights */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Zap className="h-5 w-5 text-primary" />
                Priority ML Insights
              </CardTitle>
              <CardDescription>AI-generated insights requiring attention</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              {insights
                .filter(i => i.impact === 'high')
                .map((insight) => {
                  const Icon = getInsightIcon(insight.type);
                  return (
                    <Card key={insight.id} className="border-l-4 border-l-primary">
                      <CardContent className="p-4">
                        <div className="flex items-start gap-3">
                          <div className="p-2 bg-primary/10 rounded-lg">
                            <Icon className="h-5 w-5 text-primary" />
                          </div>
                          <div className="flex-1 space-y-2">
                            <div className="flex items-start justify-between">
                              <div>
                                <h4 className="font-semibold">{insight.title}</h4>
                                <p className="text-sm text-muted-foreground mt-1">
                                  {insight.description}
                                </p>
                              </div>
                              <Badge className={getImpactColor(insight.impact)}>
                                {insight.impact}
                              </Badge>
                            </div>
                            <div className="flex items-center gap-4 text-xs text-muted-foreground">
                              <div className="flex items-center gap-1">
                                <Eye className="h-3 w-3" />
                                Confidence: {(insight.confidence * 100).toFixed(0)}%
                              </div>
                              <div className="flex items-center gap-1">
                                <Brain className="h-3 w-3" />
                                {insight.model_name}
                              </div>
                              <Badge variant="outline">{insight.category}</Badge>
                            </div>
                            {insight.action_items && (
                              <div className="mt-3 p-3 bg-muted rounded-lg">
                                <div className="text-xs font-medium mb-2">Recommended Actions:</div>
                                <ul className="text-xs space-y-1">
                                  {insight.action_items.map((action, idx) => (
                                    <li key={idx} className="flex items-start gap-2">
                                      <CheckCircle2 className="h-3 w-3 mt-0.5 text-primary" />
                                      {action}
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  );
                })}
            </CardContent>
          </Card>

          {/* Performance Trends Preview */}
          <div className="grid gap-4 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Key Metric Trends</CardTitle>
                <CardDescription>Current vs predicted values</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {trends.slice(0, 2).map((trend) => (
                  <div key={trend.metric}>
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm font-medium">{trend.metric}</span>
                      <div className="flex items-center gap-2">
                        <span className="text-2xl font-bold">{trend.current_value}%</span>
                        <Badge variant={trend.trend === 'up' ? 'default' : trend.trend === 'down' ? 'destructive' : 'secondary'}>
                          {trend.trend === 'up' ? <TrendingUp className="h-3 w-3" /> : trend.trend === 'down' ? <TrendingDown className="h-3 w-3" /> : null}
                          {Math.abs(trend.change_percent).toFixed(1)}%
                        </Badge>
                      </div>
                    </div>
                    <div className="flex gap-2 text-xs text-muted-foreground">
                      <div>7d: {trend.prediction_7d}%</div>
                      <div>30d: {trend.prediction_30d}%</div>
                    </div>
                    <Progress 
                      value={(trend.current_value / 100) * 100} 
                      className="h-2 mt-2"
                    />
                  </div>
                ))}
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Model Health Status</CardTitle>
                <CardDescription>Real-time model monitoring</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {models.map((model) => (
                  <div key={model.model_name} className="flex items-center justify-between">
                    <div className="flex-1">
                      <div className="text-sm font-medium">{model.model_name}</div>
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <span>Acc: {(model.accuracy * 100).toFixed(1)}%</span>
                        <span>•</span>
                        <span>{model.predictions_today} predictions</span>
                      </div>
                    </div>
                    <Badge
                      variant={model.status === 'healthy' ? 'default' : model.status === 'warning' ? 'secondary' : 'destructive'}
                      className="capitalize"
                    >
                      {model.status}
                    </Badge>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* ML Insights Tab */}
        <TabsContent value="insights" className="space-y-4">
          <div className="grid gap-4">
            {insights.map((insight) => {
              const Icon = getInsightIcon(insight.type);
              return (
                <Card key={insight.id}>
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      <div className="p-3 bg-primary/10 rounded-lg">
                        <Icon className="h-6 w-6 text-primary" />
                      </div>
                      <div className="flex-1 space-y-3">
                        <div className="flex items-start justify-between">
                          <div>
                            <h3 className="font-semibold text-lg">{insight.title}</h3>
                            <Badge variant="outline" className="mt-1 capitalize">{insight.type}</Badge>
                          </div>
                          <Badge className={getImpactColor(insight.impact)}>
                            {insight.impact} impact
                          </Badge>
                        </div>
                        <p className="text-muted-foreground">{insight.description}</p>
                        <div className="flex items-center gap-6 text-sm">
                          <div className="flex items-center gap-2">
                            <Eye className="h-4 w-4 text-muted-foreground" />
                            <span>Confidence: {(insight.confidence * 100).toFixed(0)}%</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <Brain className="h-4 w-4 text-muted-foreground" />
                            <span>{insight.model_name}</span>
                          </div>
                          <Badge variant="secondary">{insight.category}</Badge>
                        </div>
                        {insight.action_items && (
                          <div className="mt-4 p-4 bg-muted rounded-lg">
                            <div className="font-medium mb-3">Recommended Actions:</div>
                            <ul className="space-y-2">
                              {insight.action_items.map((action, idx) => (
                                <li key={idx} className="flex items-start gap-2">
                                  <CheckCircle2 className="h-5 w-5 mt-0.5 text-primary flex-shrink-0" />
                                  <span>{action}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </TabsContent>

        {/* Predictive Trends Tab */}
        <TabsContent value="trends" className="space-y-4">
          <div className="grid gap-4">
            {trends.map((trend) => (
              <Card key={trend.metric}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle>{trend.metric}</CardTitle>
                    <Badge
                      variant={trend.trend === 'up' ? 'default' : trend.trend === 'down' ? 'destructive' : 'secondary'}
                      className="gap-1"
                    >
                      {trend.trend === 'up' ? <TrendingUp className="h-3 w-3" /> : 
                       trend.trend === 'down' ? <TrendingDown className="h-3 w-3" /> : null}
                      {trend.change_percent > 0 ? '+' : ''}{trend.change_percent.toFixed(1)}%
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-3 gap-4">
                    <div className="text-center p-4 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">Current</div>
                      <div className="text-2xl font-bold">{trend.current_value}%</div>
                    </div>
                    <div className="text-center p-4 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">7-Day Forecast</div>
                      <div className="text-2xl font-bold">{trend.prediction_7d}%</div>
                    </div>
                    <div className="text-center p-4 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">30-Day Forecast</div>
                      <div className="text-2xl font-bold">{trend.prediction_30d}%</div>
                    </div>
                  </div>
                  <div>
                    <div className="flex justify-between text-sm mb-2">
                      <span>Progress to 30-day target</span>
                      <span className={trend.prediction_30d > trend.current_value ? 'text-green-600' : 'text-red-600'}>
                        {((trend.prediction_30d - trend.current_value) / trend.current_value * 100).toFixed(1)}% change expected
                      </span>
                    </div>
                    <Progress value={(trend.current_value / trend.prediction_30d) * 100} className="h-3" />
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        {/* Model Performance Tab */}
        <TabsContent value="models" className="space-y-4">
          <div className="grid gap-4">
            {models.map((model) => (
              <Card key={model.model_name}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle>{model.model_name}</CardTitle>
                    <Badge
                      variant={model.status === 'healthy' ? 'default' : model.status === 'warning' ? 'secondary' : 'destructive'}
                      className="capitalize"
                    >
                      {model.status}
                    </Badge>
                  </div>
                  <CardDescription>
                    {model.predictions_today} predictions today • {model.latency_ms}ms avg latency
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="text-center p-3 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">Accuracy</div>
                      <div className="text-xl font-bold">{(model.accuracy * 100).toFixed(1)}%</div>
                      <Progress value={model.accuracy * 100} className="h-1 mt-2" />
                    </div>
                    <div className="text-center p-3 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">Precision</div>
                      <div className="text-xl font-bold">{(model.precision * 100).toFixed(1)}%</div>
                      <Progress value={model.precision * 100} className="h-1 mt-2" />
                    </div>
                    <div className="text-center p-3 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">Recall</div>
                      <div className="text-xl font-bold">{(model.recall * 100).toFixed(1)}%</div>
                      <Progress value={model.recall * 100} className="h-1 mt-2" />
                    </div>
                    <div className="text-center p-3 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">F1 Score</div>
                      <div className="text-xl font-bold">{(model.f1_score * 100).toFixed(1)}%</div>
                      <Progress value={model.f1_score * 100} className="h-1 mt-2" />
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
