apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensei.fullname" . }}-frontend
  labels:
    {{- include "sensei.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.autoscaling.frontend.enabled }}
  replicas: {{ .Values.replicaCount.frontend }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sensei.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "sensei.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sensei.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: frontend
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 12 }}
        image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.frontend.targetPort }}
          protocol: TCP
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://{{ (index .Values.ingress.hosts 0).host }}"
        livenessProbe:
          {{- toYaml .Values.healthChecks.frontend.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.healthChecks.frontend.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources.frontend | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
