{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "sensei.fullname" . }}-external-secret
  labels:
    {{- include "sensei.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ include "sensei.fullname" . }}-secret
    creationPolicy: Owner
  data:
    {{- range $key, $val := .Values.externalSecrets.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $val.remoteKey }}
        property: {{ $val.remoteProperty }}
    {{- end }}
{{- end }}
