{{- if .Values.senseiApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensei.fullname" . }}-sensei-api
  labels:
    {{- include "sensei.labels" . | nindent 4 }}
    app.kubernetes.io/component: sensei-api
spec:
  type: {{ .Values.service.senseiApi.type }}
  ports:
    - port: {{ .Values.service.senseiApi.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sensei.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sensei-api
{{- end }}
