//! Chatbot service for conversational AI interactions.
//!
//! Provides a [`ChatbotService`] trait with chat and streaming-chat
//! methods, along with an in-memory implementation backed by
//! [`sensei_zt::llm::LlamaRunner`] for LLaMA-based inference or
//! pattern-matching fallback when model weights are unavailable.

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use sensei_core::error::{Result, SenseiError};
use sensei_core::types::EntityId;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::{mpsc, Mutex, RwLock};

// ──────────────────────────────────────────────
// DTOs
// ──────────────────────────────────────────────

/// Configuration for the chatbot service.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatbotConfig {
    /// Optional path to model weights file.
    pub model_path: Option<String>,
    /// Maximum number of tokens to generate per response.
    #[serde(default = "default_max_tokens")]
    pub max_tokens: usize,
    /// Sampling temperature (0.0 = greedy, higher = more random).
    #[serde(default = "default_temperature")]
    pub temperature: f32,
    /// Top-k sampling parameter (0 = disabled).
    #[serde(default = "default_top_k")]
    pub top_k: u32,
    /// Top-p (nucleus) sampling parameter (0.0 = disabled, 1.0 = all).
    #[serde(default = "default_top_p")]
    pub top_p: f32,
    /// System prompt prepended to all conversations.
    #[serde(default = "default_system_prompt")]
    pub system_prompt: String,
}

fn default_max_tokens() -> usize {
    256
}
fn default_temperature() -> f32 {
    0.7
}
fn default_top_k() -> u32 {
    40
}
fn default_top_p() -> f32 {
    0.9
}
fn default_system_prompt() -> String {
    "You are Starz Forge AI, the manufacturing operations assistant of the Starz group. You help users with quality management, maintenance, production, supply chain, finance, HR, and continuous improvement topics.".to_string()
}

impl Default for ChatbotConfig {
    fn default() -> Self {
        Self {
            model_path: None,
            max_tokens: default_max_tokens(),
            temperature: default_temperature(),
            top_k: default_top_k(),
            top_p: default_top_p(),
            system_prompt: default_system_prompt(),
        }
    }
}

/// A single chat message in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// The role of the message sender (e.g., "user", "assistant", "system").
    pub role: String,
    /// The message content.
    pub content: String,
    /// When this message was sent.
    pub timestamp: DateTime<Utc>,
}

impl ChatMessage {
    /// Create a new user message.
    pub fn user(content: String) -> Self {
        Self {
            role: "user".to_string(),
            content,
            timestamp: Utc::now(),
        }
    }

    /// Create a new assistant message.
    pub fn assistant(content: String) -> Self {
        Self {
            role: "assistant".to_string(),
            content,
            timestamp: Utc::now(),
        }
    }

    /// Create a new system message.
    pub fn system(content: String) -> Self {
        Self {
            role: "system".to_string(),
            content,
            timestamp: Utc::now(),
        }
    }
}

/// Response from a chat request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    /// The assistant's response message.
    pub message: ChatMessage,
    /// Unique conversation identifier.
    pub conversation_id: String,
    /// Whether this response was generated by the model or fallback.
    pub is_fallback: bool,
}

/// Per-request sampling parameters that override the service defaults.
///
/// `None` fields fall back to the service configuration; providing a field
/// (even `0` for temperature/top-k) overrides it.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChatSamplingParams {
    /// Maximum number of tokens to generate.
    pub max_tokens: Option<usize>,
    /// Sampling temperature (0.0 = greedy).
    pub temperature: Option<f32>,
    /// Top-k sampling parameter (0 = disabled).
    pub top_k: Option<u32>,
    /// Top-p (nucleus) sampling parameter.
    pub top_p: Option<f32>,
}

impl ChatSamplingParams {
    /// Effective max tokens for a request (request override or config).
    pub fn max_tokens_or(&self, config: usize) -> usize {
        self.max_tokens.unwrap_or(config)
    }

    /// Effective temperature for a request (request override or config).
    pub fn temperature_or(&self, config: f32) -> f32 {
        self.temperature.unwrap_or(config)
    }

    /// Effective top-k for a request (request override or config).
    pub fn top_k_or(&self, config: u32) -> u32 {
        self.top_k.unwrap_or(config)
    }

    /// Effective top-p for a request (request override or config).
    pub fn top_p_or(&self, config: f32) -> f32 {
        self.top_p.unwrap_or(config)
    }
}

// ──────────────────────────────────────────────
// Trait
// ──────────────────────────────────────────────

/// Chatbot service for conversational AI.
///
/// Provides methods for single-turn chat, streaming chat, and
/// conversation history retrieval.
#[async_trait]
pub trait ChatbotService: Send + Sync {
    /// Send a chat message and receive a response.
    ///
    /// `tenant_id` identifies the tenant/organisation.
    /// `user_id` identifies the user sending the message.
    /// `message` is the user's input text.
    /// `conversation_id` optionally specifies an existing conversation
    /// to continue. If `None`, a new conversation is started.
    /// `sampling` optionally overrides the configured sampling parameters
    /// (max tokens, temperature, top-k, top-p) for this request.
    /// `system_context` is the server-built authoritative context bundle
    /// (Context Kernel, sixteenth audit 8/96) threaded into the prompt
    /// BEFORE generation — the model never invents the retrieval strategy.
    async fn chat(
        &self,
        tenant_id: EntityId,
        user_id: EntityId,
        message: &str,
        conversation_id: Option<&str>,
        sampling: Option<ChatSamplingParams>,
        system_context: Option<&str>,
    ) -> Result<ChatResponse>;

    /// Stream a chat response token by token.
    ///
    /// Returns a [`mpsc::Receiver`] that yields result strings, each
    /// representing one token (or a chunk of the response).
    /// `sampling` optionally overrides the configured sampling parameters
    /// for this request.
    async fn stream_chat(
        &self,
        tenant_id: EntityId,
        user_id: EntityId,
        message: &str,
        conversation_id: Option<&str>,
        sampling: Option<ChatSamplingParams>,
    ) -> Result<mpsc::Receiver<Result<String>>>;

    /// Retrieve the full conversation history.
    async fn get_conversation_history(
        &self,
        tenant_id: EntityId,
        conversation_id: &str,
    ) -> Result<Vec<ChatMessage>>;
}

// ──────────────────────────────────────────────
// SenseiChatbotService (LLaMA-backed)
// ──────────────────────────────────────────────

/// LLaMA-backed chatbot service using [`sensei_zt::llm::LlamaRunner`].
///
/// When model weights are available, runs the full transformer pipeline
/// via Zig FFI. Otherwise falls back to pattern-matching responses.
pub struct SenseiChatbotService {
    /// The underlying LLaMA runner (wrapped in Mutex for thread safety).
    runner: Arc<Mutex<Option<sensei_zt::llm::LlamaRunner>>>,
    /// Chatbot configuration.
    config: ChatbotConfig,
    /// In-memory conversation store keyed by conversation ID.
    conversation_store: Arc<RwLock<HashMap<String, Vec<ChatMessage>>>>,
}

impl SenseiChatbotService {
    /// Create a new [`SenseiChatbotService`].
    ///
    /// Attempts to load model weights from `config.model_path`. If the
    /// path is `None` or loading fails, falls back to the pure-Rust
    /// pattern-matching chatbot.
    pub fn new(config: ChatbotConfig) -> Self {
        let runner = if let Some(ref path) = config.model_path {
            // Attempt to load weights from file
            match std::fs::read(path) {
                Ok(bytes) => {
                    // Interpret bytes as f32 weights
                    let weight_count = bytes.len() / 4;
                    let mut weights = vec![0.0f32; weight_count];
                    unsafe {
                        std::ptr::copy_nonoverlapping(
                            bytes.as_ptr(),
                            weights.as_mut_ptr() as *mut u8,
                            bytes.len(),
                        );
                    }

                    let llm_config = sensei_zt::llm::LlamaConfig::default();
                    match sensei_zt::llm::LlamaRunner::new(llm_config, &weights) {
                        Ok(runner) => {
                            tracing::info!("Loaded LLaMA model weights from {path}");
                            Some(runner)
                        }
                        Err(e) => {
                            tracing::warn!(
                                "Failed to initialise LLaMA runner from {path}: {e}. Falling back to pattern matching."
                            );
                            None
                        }
                    }
                }
                Err(e) => {
                    tracing::warn!(
                        "Failed to read model weights from {path}: {e}. Falling back to pattern matching."
                    );
                    None
                }
            }
        } else {
            None
        };

        Self {
            runner: Arc::new(Mutex::new(runner)),
            config,
            conversation_store: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    /// Generate a conversation ID for a new conversation.
    fn generate_conversation_id() -> String {
        uuid::Uuid::new_v4().to_string()
    }

    /// Build the full prompt including system prompt, the authoritative
    /// live context bundle and conversation history.
    fn build_prompt(
        &self,
        message: &str,
        history: &[ChatMessage],
        system_context: Option<&str>,
    ) -> String {
        let mut prompt = String::new();

        // System prompt
        prompt.push_str(&self.config.system_prompt);
        prompt.push('\n');

        // Context Kernel (sixteenth audit 8/96): the authoritative live
        // bundle is part of the prompt — generation happens WITH it, it is
        // not attached afterwards as metadata.
        if let Some(context) = system_context {
            let trimmed = context.trim();
            if !trimmed.is_empty() {
                prompt.push_str("AUTHORITATIVE CONTEXT (live): ");
                prompt.push_str(trimmed);
                prompt.push('\n');
            }
        }

        // Conversation history
        for msg in history {
            prompt.push_str(&format!("{}: {}\n", msg.role, msg.content));
        }

        // Current message
        prompt.push_str(&format!("user: {message}\n"));
        prompt.push_str("assistant: ");

        prompt
    }
}

#[async_trait]
impl ChatbotService for SenseiChatbotService {
    async fn chat(
        &self,
        _tenant_id: EntityId,
        _user_id: EntityId,
        message: &str,
        conversation_id: Option<&str>,
        sampling: Option<ChatSamplingParams>,
        system_context: Option<&str>,
    ) -> Result<ChatResponse> {
        let conv_id = conversation_id
            .map(|s| s.to_string())
            .unwrap_or_else(Self::generate_conversation_id);

        // Get or create conversation history
        let history = {
            let store = self.conversation_store.read().await;
            store.get(&conv_id).cloned().unwrap_or_default()
        };

        // Build prompt
        let prompt = self.build_prompt(message, &history, system_context);

        // Per-request sampling overrides the configured defaults.
        let sampling = sampling.unwrap_or_default();
        let max_tokens = sampling.max_tokens_or(self.config.max_tokens);
        let temperature = sampling.temperature_or(self.config.temperature);
        let top_k = sampling.top_k_or(self.config.top_k);
        let top_p = sampling.top_p_or(self.config.top_p);

        // Generate response
        let mut runner_guard = self.runner.lock().await;
        let (response, is_fallback) = if let Some(ref mut runner) = *runner_guard {
            match runner.generate(&prompt, max_tokens, temperature, top_k, top_p) {
                Ok(resp) => (resp, false),
                Err(e) => {
                    tracing::warn!("LLaMA generation failed: {e}. Falling back.");
                    (fallback_chat(message), true)
                }
            }
        } else {
            (fallback_chat(message), true)
        };

        // Save to conversation history
        {
            let mut store = self.conversation_store.write().await;
            let conv = store.entry(conv_id.clone()).or_default();
            conv.push(ChatMessage::user(message.to_string()));
            conv.push(ChatMessage::assistant(response.clone()));
        }

        Ok(ChatResponse {
            message: ChatMessage::assistant(response),
            conversation_id: conv_id,
            is_fallback,
        })
    }

    async fn stream_chat(
        &self,
        tenant_id: EntityId,
        user_id: EntityId,
        message: &str,
        conversation_id: Option<&str>,
        sampling: Option<ChatSamplingParams>,
    ) -> Result<mpsc::Receiver<Result<String>>> {
        let (tx, rx) = mpsc::channel::<Result<String>>(64);

        let this = self.clone();
        let message = message.to_string();
        let conv_id = conversation_id
            .map(|s| s.to_string())
            .unwrap_or_else(Self::generate_conversation_id);

        tokio::spawn(async move {
            // Get the full response first
            let response = this
                .chat(tenant_id, user_id, &message, Some(&conv_id), sampling, None)
                .await;

            match response {
                Ok(chat_resp) => {
                    // Stream tokens word by word
                    for word in chat_resp.message.content.split(' ') {
                        if tx.send(Ok(format!("{word} "))).await.is_err() {
                            break;
                        }
                        tokio::time::sleep(std::time::Duration::from_millis(20)).await;
                    }
                }
                Err(e) => {
                    let _ = tx.send(Err(e)).await;
                }
            }
        });

        Ok(rx)
    }

    async fn get_conversation_history(
        &self,
        _tenant_id: EntityId,
        conversation_id: &str,
    ) -> Result<Vec<ChatMessage>> {
        let store = self.conversation_store.read().await;
        store.get(conversation_id).cloned().ok_or_else(|| {
            SenseiError::NotFound(format!("Conversation {conversation_id} not found"))
        })
    }
}

impl Clone for SenseiChatbotService {
    fn clone(&self) -> Self {
        Self {
            runner: Arc::clone(&self.runner),
            config: self.config.clone(),
            conversation_store: Arc::clone(&self.conversation_store),
        }
    }
}

// ──────────────────────────────────────────────
// InMemoryChatbotService (always fallback)
// ──────────────────────────────────────────────

/// In-memory chatbot service using pattern-matching fallback only.
///
/// This is intended for development, testing, and demo environments
/// where no model weights are available.
pub struct InMemoryChatbotService {
    config: ChatbotConfig,
    conversation_store: Arc<RwLock<HashMap<String, Vec<ChatMessage>>>>,
}

impl InMemoryChatbotService {
    /// Create a new [`InMemoryChatbotService`].
    pub fn new(config: ChatbotConfig) -> Self {
        Self {
            config,
            conversation_store: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    fn generate_conversation_id() -> String {
        uuid::Uuid::new_v4().to_string()
    }
}

impl Default for InMemoryChatbotService {
    fn default() -> Self {
        Self::new(ChatbotConfig::default())
    }
}

#[async_trait]
impl ChatbotService for InMemoryChatbotService {
    async fn chat(
        &self,
        _tenant_id: EntityId,
        _user_id: EntityId,
        message: &str,
        conversation_id: Option<&str>,
        _sampling: Option<ChatSamplingParams>,
        _system_context: Option<&str>,
    ) -> Result<ChatResponse> {
        let conv_id = conversation_id
            .map(|s| s.to_string())
            .unwrap_or_else(Self::generate_conversation_id);

        let response = fallback_chat(message);

        // Save to conversation history
        {
            let mut store = self.conversation_store.write().await;
            let conv = store.entry(conv_id.clone()).or_default();
            conv.push(ChatMessage::user(message.to_string()));
            conv.push(ChatMessage::assistant(response.clone()));
        }

        Ok(ChatResponse {
            message: ChatMessage::assistant(response),
            conversation_id: conv_id,
            is_fallback: true,
        })
    }

    async fn stream_chat(
        &self,
        tenant_id: EntityId,
        user_id: EntityId,
        message: &str,
        conversation_id: Option<&str>,
        sampling: Option<ChatSamplingParams>,
    ) -> Result<mpsc::Receiver<Result<String>>> {
        let (tx, rx) = mpsc::channel(64);

        let this = self.clone();
        let message = message.to_string();
        let conv_id = conversation_id
            .map(|s| s.to_string())
            .unwrap_or_else(Self::generate_conversation_id);

        tokio::spawn(async move {
            let response = this
                .chat(tenant_id, user_id, &message, Some(&conv_id), sampling, None)
                .await;

            match response {
                Ok(chat_resp) => {
                    for word in chat_resp.message.content.split(' ') {
                        if tx.send(Ok(format!("{word} "))).await.is_err() {
                            break;
                        }
                        tokio::time::sleep(std::time::Duration::from_millis(20)).await;
                    }
                }
                Err(e) => {
                    let _ = tx.send(Err(e)).await;
                }
            }
        });

        Ok(rx)
    }

    async fn get_conversation_history(
        &self,
        _tenant_id: EntityId,
        conversation_id: &str,
    ) -> Result<Vec<ChatMessage>> {
        let store = self.conversation_store.read().await;
        store.get(conversation_id).cloned().ok_or_else(|| {
            SenseiError::NotFound(format!("Conversation {conversation_id} not found"))
        })
    }
}

impl Clone for InMemoryChatbotService {
    fn clone(&self) -> Self {
        Self {
            config: self.config.clone(),
            conversation_store: Arc::clone(&self.conversation_store),
        }
    }
}

// ──────────────────────────────────────────────
// Fallback pattern-matching
// ──────────────────────────────────────────────

struct FallbackPattern {
    keywords: &'static [&'static str],
    response: &'static str,
}

const FALLBACK_PATTERNS: &[FallbackPattern] = &[
    FallbackPattern {
        keywords: &["hello", "hi", "hey", "greetings"],
        response: "Hello! I'm Starz Forge AI, your manufacturing assistant. How can I help you today?",
    },
    FallbackPattern {
        keywords: &["help", "what can you do", "capabilities"],
        response: "I can help you with quality management, maintenance tracking, production monitoring, supply chain management, and continuous improvement initiatives. Try asking me about a specific topic!",
    },
    FallbackPattern {
        keywords: &["quality", "ncr", "non-conformance", "inspection"],
        response: "For quality management, I can help with non-conformance reports (NCRs), corrective actions (CAPAs), inspections, audits, and supplier quality. What specific quality topic interests you?",
    },
    FallbackPattern {
        keywords: &["maintenance", "pm", "preventive", "equipment", "work request"],
        response: "For maintenance, I can assist with work requests, preventive maintenance schedules, equipment tracking, and warranty management. What maintenance task can I help with?",
    },
    FallbackPattern {
        keywords: &["production", "manufacturing", "work order", "schedule"],
        response: "For production, I can help with work orders, production scheduling, bill of materials (BOM), and material requirements planning (MRP). What production topic would you like to explore?",
    },
    FallbackPattern {
        keywords: &["supply chain", "inventory", "purchase order", "rfq", "supplier"],
        response: "For supply chain, I can assist with RFQs, purchase orders, inventory management, sales orders, and supplier evaluation. How can I help with your supply chain needs?",
    },
    FallbackPattern {
        keywords: &["finance", "invoice", "payment", "budget", "accounting"],
        response: "For finance, I can help with invoices, payments, budgets, journal entries, and cost rollups. What financial topic would you like to discuss?",
    },
    FallbackPattern {
        keywords: &["hr", "employee", "training", "leave", "timecard"],
        response: "For HR, I can assist with employee management, training records, leave requests, timecards, and performance reviews. How can I help with HR matters?",
    },
    FallbackPattern {
        keywords: &["continuous improvement", "kaizen", "lean", "six sigma", "andon"],
        response: "For continuous improvement, I can help with Andon systems, A3 problem-solving, risk management, and Kaizen projects. What improvement initiative are you working on?",
    },
    FallbackPattern {
        keywords: &["safety", "lockout", "tagout", "loto", "osha"],
        response: "For safety, I can assist with lockout/tagout (LOTO) procedures, safety audits, and compliance tracking. Safety is our top priority — how can I help?",
    },
    FallbackPattern {
        keywords: &["thanks", "thank you", "appreciate"],
        response: "You're welcome! I'm here to help. Feel free to ask me anything about manufacturing operations.",
    },
    FallbackPattern {
        keywords: &["bye", "goodbye", "see you"],
        response: "Goodbye! Feel free to come back anytime you need assistance with your manufacturing operations.",
    },
];

const DEFAULT_FALLBACK: &str = "I'm Starz Forge AI, your manufacturing operations assistant. I can help with quality, maintenance, production, supply chain, finance, HR, and continuous improvement topics. What would you like to know more about?";

/// Generate a fallback response using keyword matching.
pub(crate) fn fallback_chat(input: &str) -> String {
    let lower = input.to_lowercase();

    let best = FALLBACK_PATTERNS
        .iter()
        .filter_map(|pattern| {
            let match_count = pattern
                .keywords
                .iter()
                .filter(|kw| lower.contains(&kw.to_lowercase()))
                .count();
            if match_count > 0 {
                Some((match_count, pattern.response))
            } else {
                None
            }
        })
        .max_by_key(|(count, _)| *count);

    match best {
        Some((_, response)) => {
            // Template expansion: replace {input} with the user's input
            if response.contains("{input}") {
                response.replace("{input}", input)
            } else {
                response.to_string()
            }
        }
        None => DEFAULT_FALLBACK.to_string(),
    }
}

// ──────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_in_memory_chat() {
        let service = InMemoryChatbotService::default();
        let tenant_id = EntityId::new_v4();
        let user_id = EntityId::new_v4();

        let response = service
            .chat(tenant_id, user_id, "hello", None, None, None)
            .await
            .expect("chat should succeed");

        assert!(response.message.content.contains("Hello!"));
        assert!(response.is_fallback);
        assert!(!response.conversation_id.is_empty());
    }

    #[tokio::test]
    async fn test_in_memory_chat_with_conversation() {
        let service = InMemoryChatbotService::default();
        let tenant_id = EntityId::new_v4();
        let user_id = EntityId::new_v4();
        let conv_id = "test-conv-123";

        let response = service
            .chat(tenant_id, user_id, "hello", Some(conv_id), None, None)
            .await
            .expect("chat should succeed");

        assert_eq!(response.conversation_id, conv_id);
    }

    #[tokio::test]
    async fn test_conversation_history() {
        let service = InMemoryChatbotService::default();
        let tenant_id = EntityId::new_v4();
        let user_id = EntityId::new_v4();

        let conv_id = "history-test-conv";

        // Send two messages
        service
            .chat(tenant_id, user_id, "hello", Some(conv_id), None, None)
            .await
            .expect("first chat");
        service
            .chat(
                tenant_id,
                user_id,
                "help with quality",
                Some(conv_id),
                None,
                None,
            )
            .await
            .expect("second chat");

        let history = service
            .get_conversation_history(tenant_id, conv_id)
            .await
            .expect("should get history");

        // Should have 4 messages (user + assistant for each of 2 turns)
        assert_eq!(history.len(), 4);
        assert_eq!(history[0].role, "user");
        assert_eq!(history[1].role, "assistant");
        assert_eq!(history[2].role, "user");
        assert_eq!(history[3].role, "assistant");
    }

    #[tokio::test]
    async fn test_conversation_history_not_found() {
        let service = InMemoryChatbotService::default();
        let tenant_id = EntityId::new_v4();

        let result = service
            .get_conversation_history(tenant_id, "non-existent")
            .await;

        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_stream_chat() {
        let service = InMemoryChatbotService::default();
        let tenant_id = EntityId::new_v4();
        let user_id = EntityId::new_v4();

        let mut rx = service
            .stream_chat(tenant_id, user_id, "hello", None, None)
            .await
            .expect("stream chat should succeed");

        let mut full_response = String::new();
        while let Some(result) = rx.recv().await {
            match result {
                Ok(chunk) => full_response.push_str(&chunk),
                Err(_) => break,
            }
        }

        assert!(full_response.contains("Hello!"));
    }

    #[tokio::test]
    async fn test_quality_topic() {
        let service = InMemoryChatbotService::default();
        let tenant_id = EntityId::new_v4();
        let user_id = EntityId::new_v4();

        let response = service
            .chat(
                tenant_id,
                user_id,
                "I need help with quality inspection",
                None,
                None,
                None,
            )
            .await
            .expect("chat should succeed");

        assert!(response.message.content.contains("quality"));
    }

    #[tokio::test]
    async fn test_chatbot_config_default() {
        let config = ChatbotConfig::default();
        assert_eq!(config.max_tokens, 256);
        assert!((config.temperature - 0.7).abs() < f32::EPSILON);
        assert_eq!(config.top_k, 40);
        assert!((config.top_p - 0.9).abs() < f32::EPSILON);
        assert!(!config.system_prompt.is_empty());
    }

    #[test]
    fn test_chat_message_constructors() {
        let user_msg = ChatMessage::user("hello".to_string());
        assert_eq!(user_msg.role, "user");
        assert_eq!(user_msg.content, "hello");

        let assistant_msg = ChatMessage::assistant("hi there".to_string());
        assert_eq!(assistant_msg.role, "assistant");
        assert_eq!(assistant_msg.content, "hi there");

        let system_msg = ChatMessage::system("be helpful".to_string());
        assert_eq!(system_msg.role, "system");
        assert_eq!(system_msg.content, "be helpful");
    }
}
