//! AI Reasoning Engine — A3 Pattern Analysis, Socratic Mentoring, and 5 Whys.
//!
//! Ported from [`reasoning_engine.py`](backend/src/sensei/services/ai/reasoning_engine.py).
//!
//! # Components
//!
//! - [`A3PatternAnalyzer`] — Analyzes closed A3 reports, computes countermeasure
//!   correlations, and suggests countermeasures based on historical success rates.
//! - [`SocraticMentor`] — Generates Socratic/challenging prompts for mentoring
//!   sessions, adapting to different mentor personas and A3 phases.
//! - [`FiveWhysAssistant`] — Performs 5-Whys root cause analysis, classifies waste
//!   categories, and identifies muda types using keyword-based pattern matching.
//! - [`SenseiReasoningEngine`] — Orchestrates the three assistants and provides a
//!   unified public API.

use chrono::{DateTime, Utc};
use rand::Rng;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/// Phase of the A3 problem-solving process.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum A3Phase {
    ProblemDefinition,
    CurrentState,
    TargetState,
    RootCauseAnalysis,
    CountermeasurePlanning,
    Implementation,
    ResultsReview,
    Reflection,
}

/// Lean waste category.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LeanWasteCategory {
    Defects,
    Overproduction,
    Waiting,
    NonUtilizedTalent,
    Transportation,
    Inventory,
    Motion,
    ExcessProcessing,
}

/// Specific muda (waste) sub-type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MudaType {
    Correction,
    Overproduction,
    Motion,
    Conveyance,
    Inventory,
    Processing,
    WaitTime,
    KnowledgeDeficit,
}

/// Mentor persona for Socratic mentoring.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MentorPersona {
    CriticalThinker,
    ProcessImprover,
    LeanCoach,
    Challenger,
}

/// Type of prompt generated by the mentor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PromptType {
    Exploration,
    Reflection,
    Assumption,
    Evidence,
    ActionPlanning,
    Perspective,
}

/// Trend direction for KPIs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KPITrend {
    Improving,
    Declining,
    Stable,
    Volatile,
    Unknown,
}

// ---------------------------------------------------------------------------
// Data Models
// ---------------------------------------------------------------------------

/// A single KPI measurement.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KPIMetric {
    pub name: String,
    pub current_value: f64,
    pub target_value: f64,
    pub baseline_value: f64,
    pub unit: String,
    pub trend: KPITrend,
    pub measured_at: DateTime<Utc>,
}

impl KPIMetric {
    /// Returns `true` if the current value meets or exceeds the target.
    pub fn is_on_target(&self) -> bool {
        if self.current_value >= self.target_value {
            true
        } else {
            // Allow 5 % tolerance below target
            let tolerance = self.target_value * 0.05;
            (self.target_value - self.current_value).abs() <= tolerance
        }
    }
}

/// A proposed countermeasure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Countermeasure {
    pub id: Uuid,
    pub description: String,
    pub category: String,
    pub expected_impact: String,
    pub effort: String,
    pub owner: String,
    pub target_date: DateTime<Utc>,
}

/// A closed A3 report used for pattern analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct A3Report {
    pub id: Uuid,
    pub title: String,
    pub problem_statement: String,
    pub waste_category: Option<LeanWasteCategory>,
    pub muda_type: Option<MudaType>,
    pub countermeasures: Vec<Countermeasure>,
    pub kpis: Vec<KPIMetric>,
    pub closed_at: DateTime<Utc>,
}

/// Correlation between a countermeasure category and KPI improvement.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountermeasureCorrelation {
    pub category: String,
    pub avg_improvement: f64,
    pub sample_size: usize,
    pub success_rate: f64,
    pub applied_count: usize,
}

/// A challenging prompt for Socratic mentoring.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChallengingPrompt {
    pub id: Uuid,
    pub prompt_type: PromptType,
    pub content: String,
    pub persona: MentorPersona,
    pub phase: A3Phase,
    pub follow_ups: Vec<String>,
    pub created_at: DateTime<Utc>,
}

/// A suggested root cause from the 5 Whys analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RootCauseSuggestion {
    pub cause: String,
    pub pattern_match_score: f64,
    pub evidence_needed: Vec<String>,
    pub related_waste: Option<LeanWasteCategory>,
    pub related_muda: Option<MudaType>,
}

// ---------------------------------------------------------------------------
// Constants: Prompt Templates
// ---------------------------------------------------------------------------

/// Prompt templates indexed by (persona, prompt_type).
fn prompt_templates(
    persona: MentorPersona,
    prompt_type: PromptType,
) -> &'static [&'static str] {
    use MentorPersona::*;
    use PromptType::*;

    match (persona, prompt_type) {
        (CriticalThinker, Exploration) => &[
            "What evidence supports your current understanding of this problem?",
            "What assumptions are you making about the current state?",
            "How do you know this is the real problem versus a symptom?",
        ],
        (CriticalThinker, Reflection) => &[
            "Looking back at similar problems, what patterns do you notice?",
            "What would have happened if you had taken a different approach?",
            "How does this connect to what you learned from previous A3s?",
        ],
        (CriticalThinker, Assumption) => &[
            "What are you taking for granted in your analysis?",
            "How would your conclusions change if your assumptions were wrong?",
            "What data would prove your hypothesis incorrect?",
        ],
        (CriticalThinker, Evidence) => &[
            "What specific data supports this conclusion?",
            "How reliable is your data source?",
            "What additional measurements would strengthen your analysis?",
        ],
        (CriticalThinker, ActionPlanning) => &[
            "What are the potential unintended consequences of your countermeasures?",
            "How will you measure effectiveness of each action?",
            "What is your contingency plan if this doesn't work?",
        ],
        (CriticalThinker, Perspective) => &[
            "How would the operator on the floor view this situation?",
            "What would your toughest critic say about this plan?",
            "Consider this from the customer's perspective — what matters most?",
        ],
        (ProcessImprover, Exploration) => &[
            "What is the current process flow for this work?",
            "Where do you see the biggest opportunities for improvement?",
            "How does this process connect to upstream and downstream activities?",
        ],
        (ProcessImprover, Reflection) => &[
            "What waste have you identified in the current process?",
            "Which process steps add value versus those that don't?",
            "How stable is the current process?",
        ],
        (ProcessImprover, Assumption) => &[
            "Are you assuming the current process is optimized?",
            "What process constraints are you accepting as fixed?",
            "How would redesigning the process change the outcome?",
        ],
        (ProcessImprover, Evidence) => &[
            "What process data have you collected?",
            "How do you know the process is in control?",
            "What is the actual cycle time versus the takt time?",
        ],
        (ProcessImprover, ActionPlanning) => &[
            "How will you standardize this improvement?",
            "What error-proofing (poka-yoke) can you implement?",
            "How will you train the team on the new process?",
        ],
        (ProcessImprover, Perspective) => &[
            "How does this improvement affect overall value stream flow?",
            "What would Taiichi Ohno say about this approach?",
            "How does this align with lean principles?",
        ],
        (LeanCoach, Exploration) => &[
            "What does your Gemba walk tell you about this situation?",
            "Have you observed the actual work being done?",
            "What does the data say versus what people say?",
        ],
        (LeanCoach, Reflection) => &[
            "What lean tools could be applied here?",
            "How does this problem relate to the 8 wastes?",
            "What is the ideal target condition?",
        ],
        (LeanCoach, Assumption) => &[
            "Are you assuming the current method is the best method?",
            "What would happen if you reduced batch size?",
            "What constraints are you accepting that could be eliminated?",
        ],
        (LeanCoach, Evidence) => &[
            "Show me the data on your board. What does it tell you?",
            "How do you know this improvement is sustainable?",
            "What metrics will you track to verify?",
        ],
        (LeanCoach, ActionPlanning) => &[
            "What is your plan for standardized work?",
            "How will you make this improvement visual?",
            "What kaizen events will support this change?",
        ],
        (LeanCoach, Perspective) => &[
            "How does this affect the overall OEE?",
            "What is the impact on takt time and flow?",
            "How does this support the principles of JIT and Jidoka?",
        ],
        (Challenger, Exploration) => &[
            "Why do you think this is the right problem to solve?",
            "What if you're solving the wrong problem entirely?",
            "Challenge your own assumptions — what would you do differently?",
        ],
        (Challenger, Reflection) => &[
            "What would you do if you had half the budget?",
            "If you had to solve this in 24 hours, what would you do?",
            "What if your solution creates a worse problem elsewhere?",
        ],
        (Challenger, Assumption) => &[
            "Prove to me that this is the root cause. Why not something else?",
            "What sacred cows are you protecting?",
            "What if you're wrong? What then?",
        ],
        (Challenger, Evidence) => &[
            "That's an interesting claim — where's the data?",
            "How do you know your measurement is accurate?",
            "What sample size do you need to be confident?",
        ],
        (Challenger, ActionPlanning) => &[
            "Your plan seems safe. What's a bolder approach?",
            "What did you intentionally leave out of the plan?",
            "What keeps you up at night about this plan?",
        ],
        (Challenger, Perspective) => &[
            "How would a startup disrupt your current approach?",
            "What would the market leader do in this situation?",
            "If you were advising a competitor, what would you tell them?",
        ],
    }
}

/// Phase-to-prompt-type focus mapping.
fn phase_focus(phase: A3Phase) -> &'static [PromptType] {
    match phase {
        A3Phase::ProblemDefinition => &[PromptType::Exploration, PromptType::Assumption],
        A3Phase::CurrentState => &[PromptType::Exploration, PromptType::Evidence],
        A3Phase::TargetState => &[PromptType::Reflection, PromptType::Perspective],
        A3Phase::RootCauseAnalysis => &[PromptType::Assumption, PromptType::Evidence, PromptType::Exploration],
        A3Phase::CountermeasurePlanning => &[PromptType::ActionPlanning, PromptType::Perspective],
        A3Phase::Implementation => &[PromptType::ActionPlanning, PromptType::Reflection],
        A3Phase::ResultsReview => &[PromptType::Evidence, PromptType::Reflection],
        A3Phase::Reflection => &[PromptType::Reflection, PromptType::Perspective],
    }
}

// ---------------------------------------------------------------------------
// Waste & Root Cause Pattern Data
// ---------------------------------------------------------------------------

fn waste_keywords() -> [(LeanWasteCategory, &'static [&'static str]); 8] {
    use LeanWasteCategory::*;
    [
        (Defects, &[
            "defect", "rework", "scrap", "error", "mistake", "non-conformance",
            "nonconformance", "nc", "fail", "failure", "correction", "reject",
            "rejection", "quality issue", "nonconforming",
        ]),
        (Overproduction, &[
            "overproduction", "too much", "excess", "overproduce", "producing ahead",
            "making more", "over supply", "oversupply", "building ahead",
        ]),
        (Waiting, &[
            "waiting", "delay", "idle", "downtime", "queue", "bottleneck",
            "wait", "stalled", "held up", "not moving", "standby",
        ]),
        (NonUtilizedTalent, &[
            "underutilized", "talent", "skill", "creativity", "suggestion",
            "ideas not used", "not engaged", "boredom", "lack of training",
            "not empowered", "employee potential",
        ]),
        (Transportation, &[
            "transportation", "moving", "conveyance", "material handling",
            "excess movement", "relocation", "transferring", "shipping back and forth",
        ]),
        (Inventory, &[
            "inventory", "stock", "wip", "work in progress", "finished goods",
            "excess material", "storage", "warehouse overflow", "buffer stock",
        ]),
        (Motion, &[
            "motion", "walking", "reaching", "bending", "searching for tools",
            "excessive movement", "unnecessary motion", "ergonomic",
        ]),
        (ExcessProcessing, &[
            "overprocessing", "excess processing", "extra steps", "redundant",
            "unnecessary process", "over-engineer", "too many approvals",
            "duplicate entry", "double checking",
        ]),
    ]
}

fn muda_keywords() -> [(MudaType, &'static [&'static str]); 8] {
    use MudaType::*;
    [
        (Correction, &[
            "fix", "rework", "correct", "repair", "scrap", "reject",
            "inspection", "testing", "checking", "re-do",
        ]),
        (Overproduction, &[
            "overproduc", "batch", "large lot", "push system", "produce ahead",
            "excess capacity",
        ]),
        (Motion, &[
            "walk", "reach", "search", "bend", "lift", "carry", "move to",
        ]),
        (Conveyance, &[
            "transport", "move material", "transfer", "ship", "deliver",
            "conveyor", "forklift", "truck",
        ]),
        (Inventory, &[
            "stock", "storage", "warehouse", "wip", "buffer", "inventory",
            "stored", "pile", "stack",
        ]),
        (Processing, &[
            "process step", "approval", "sign-off", "verification", "document",
            "report", "entry", "data input",
        ]),
        (WaitTime, &[
            "wait", "delay", "queue", "idle", "downtime", "held", "standby",
            "bottleneck", "slow",
        ]),
        (KnowledgeDeficit, &[
            "training", "knowledge", "skill", "information", "procedure",
            "instruction", "unclear", "confusion", "misunderstanding",
            "not know", "lack of training",
        ]),
    ]
}

fn root_cause_patterns() -> Vec<RootCausePattern> {
    vec![
        RootCausePattern {
            pattern: "standard|procedure|work instruction|specification",
            category: "Lack of Standardization",
            evidence_questions: &[
                "Is there a documented standard for this work?",
                "When was the standard last updated?",
                "Do operators know where to find the standard?",
            ],
        },
        RootCausePattern {
            pattern: "training|skill|knowledge|competence|qualification",
            category: "Insufficient Training",
            evidence_questions: &[
                "What training has been provided?",
                "How is competency verified?",
                "Is there a training matrix for this skill?",
            ],
        },
        RootCausePattern {
            pattern: "communication|handoff|shift change|report|information",
            category: "Communication Breakdown",
            evidence_questions: &[
                "How is information transferred between shifts?",
                "What visual management is in place?",
                "Are there standard communication protocols?",
            ],
        },
        RootCausePattern {
            pattern: "tool|equipment|machine|calibrat|maintenance",
            category: "Equipment / Tooling Issue",
            evidence_questions: &[
                "When was the last preventive maintenance?",
                "Is the equipment properly calibrated?",
                "Are there spare parts available?",
            ],
        },
        RootCausePattern {
            pattern: "design|engineering|drawing|print|spec",
            category: "Design / Engineering Issue",
            evidence_questions: &[
                "Was the design reviewed for manufacturability?",
                "Are the specifications clear and measurable?",
                "Has a design FMEA been completed?",
            ],
        },
        RootCausePattern {
            pattern: "material|supplier|raw|vendor|incoming quality",
            category: "Material / Supplier Issue",
            evidence_questions: &[
                "Has the supplier been qualified?",
                "Are incoming materials inspected?",
                "Is there a material certification process?",
            ],
        },
        RootCausePattern {
            pattern: "layout|workstation|ergonomic|5s|organization",
            category: "Workplace Organization",
            evidence_questions: &[
                "Is the workstation organized per 5S?",
                "Are tools within easy reach?",
                "Has a motion study been conducted?",
            ],
        },
        RootCausePattern {
            pattern: "schedule|planning|priority|resource|capacity",
            category: "Scheduling / Planning Issue",
            evidence_questions: &[
                "How is work prioritized?",
                "Is there a level loading (heijunka) process?",
                "Are resources allocated based on takt time?",
            ],
        },
        RootCausePattern {
            pattern: "measurement|gauge|inspect|test|check",
            category: "Measurement System Issue",
            evidence_questions: &[
                "Has a Gage R&R been performed?",
                "Are measurement devices calibrated?",
                "Is the measurement method standardized?",
            ],
        },
        RootCausePattern {
            pattern: "culture|accountability|ownership|morale|engagement",
            category: "Cultural / Behavioral Issue",
            evidence_questions: &[
                "What is the team's engagement level?",
                "Is there ownership of the process?",
                "How are problems escalated?",
            ],
        },
    ]
}

struct RootCausePattern {
    pattern: &'static str,
    category: &'static str,
    evidence_questions: &'static [&'static str],
}

// ---------------------------------------------------------------------------
// A3PatternAnalyzer
// ---------------------------------------------------------------------------

/// Analyzes closed A3 reports to identify patterns, compute countermeasure
/// correlations, and suggest effective countermeasures.
pub struct A3PatternAnalyzer {
    /// Maximum number of closed A3 reports to retain.
    max_history: usize,
    /// Closed A3 reports indexed by ID.
    closed_a3s: HashMap<Uuid, A3Report>,
    /// Cache of computed countermeasure correlations.
    correlations: Vec<CountermeasureCorrelation>,
    /// Cache of category → success rate.
    success_rates: HashMap<String, f64>,
    /// Whether the correlation cache is stale.
    correlations_dirty: bool,
}

impl A3PatternAnalyzer {
    /// Create a new [`A3PatternAnalyzer`] with the given history limit.
    pub fn new(max_history: usize) -> Self {
        Self {
            max_history,
            closed_a3s: HashMap::new(),
            correlations: Vec::new(),
            success_rates: HashMap::new(),
            correlations_dirty: false,
        }
    }

    /// Register a closed A3 report for pattern analysis.
    ///
    /// If the history exceeds `max_history`, the oldest 25 % are evicted.
    pub fn add_closed_a3(&mut self, a3: A3Report) {
        self.closed_a3s.insert(a3.id, a3);
        self.correlations_dirty = true;
        self.evict_cache_if_needed();
    }

    /// Remove the oldest 25 % of A3 reports when history exceeds the limit.
    fn evict_cache_if_needed(&mut self) {
        if self.closed_a3s.len() <= self.max_history {
            return;
        }

        let mut entries: Vec<(DateTime<Utc>, Uuid)> = self
            .closed_a3s
            .values()
            .map(|a3| (a3.closed_at, a3.id))
            .collect();
        entries.sort_by(|a, b| a.0.cmp(&b.0));

        let to_remove = self.max_history / 4;
        for (_, id) in entries.iter().take(to_remove) {
            self.closed_a3s.remove(id);
        }
        self.correlations_dirty = true;
    }

    /// Compute the improvement for each KPI in an A3 report.
    fn calculate_kpi_improvements(a3: &A3Report) -> HashMap<String, f64> {
        a3.kpis
            .iter()
            .map(|kpi| {
                let improvement = if kpi.baseline_value != 0.0 {
                    (kpi.current_value - kpi.baseline_value) / kpi.baseline_value
                } else {
                    kpi.current_value
                };
                (kpi.name.clone(), improvement)
            })
            .collect()
    }

    /// (Re)compute countermeasure correlations from all closed A3s.
    fn compute_correlations(&mut self) {
        if !self.correlations_dirty && !self.correlations.is_empty() {
            return;
        }

        // Collect category → improvements for each applied countermeasure
        let mut category_improvements: HashMap<String, Vec<f64>> = HashMap::new();
        let mut category_count: HashMap<String, usize> = HashMap::new();

        for a3 in self.closed_a3s.values() {
            let improvements = Self::calculate_kpi_improvements(a3);
            let avg_improvement: f64 = if improvements.is_empty() {
                0.0
            } else {
                improvements.values().sum::<f64>() / improvements.len() as f64
            };

            for cm in &a3.countermeasures {
                category_improvements
                    .entry(cm.category.clone())
                    .or_default()
                    .push(avg_improvement);
                *category_count.entry(cm.category.clone()).or_insert(0) += 1;
            }
        }

        let mut correlations = Vec::new();
        let mut success_rates = HashMap::new();

        for (category, improvements) in &category_improvements {
            let sample_size = improvements.len();
            let avg_improvement = improvements.iter().sum::<f64>() / sample_size as f64;
            // "Success" = improvement > 5 %
            let successes = improvements.iter().filter(|&&v| v > 0.05).count();
            let success_rate = successes as f64 / sample_size as f64;
            let applied_count = *category_count.get(category).unwrap_or(&0);

            correlations.push(CountermeasureCorrelation {
                category: category.clone(),
                avg_improvement,
                sample_size,
                success_rate,
                applied_count,
            });
            success_rates.insert(category.clone(), success_rate);
        }

        // Sort by success rate descending
        correlations.sort_by(|a, b| b.success_rate.partial_cmp(&a.success_rate).unwrap_or(std::cmp::Ordering::Equal));

        self.correlations = correlations;
        self.success_rates = success_rates;
        self.correlations_dirty = false;
    }

    /// Suggest countermeasures for a given waste category, sorted by
    /// historical success rate.
    pub fn suggest_countermeasures(&mut self, waste_category: &str) -> Vec<CountermeasureCorrelation> {
        self.compute_correlations();
        // Filter and return correlations that match the waste category
        // (or return all if no specific matches)
        let mut matches: Vec<CountermeasureCorrelation> = self
            .correlations
            .iter()
            .filter(|c| {
                c.category.to_lowercase().contains(&waste_category.to_lowercase())
            })
            .cloned()
            .collect();

        if matches.is_empty() {
            // Return top 3 overall suggestions
            matches = self.correlations.iter().take(3).cloned().collect();
        }

        matches
    }

    /// Get the historical success rate for a countermeasure category.
    pub fn get_success_rate(&mut self, category: &str) -> f64 {
        self.compute_correlations();
        self.success_rates
            .get(category)
            .copied()
            .unwrap_or(0.5) // default 50 % if unknown
    }

    /// Get statistics about the pattern analysis.
    pub fn get_stats(&self) -> HashMap<String, serde_json::Value> {
        let mut stats = HashMap::new();
        stats.insert(
            "total_a3s_analyzed".to_string(),
            serde_json::Value::Number(serde_json::Number::from(self.closed_a3s.len() as u64)),
        );
        stats.insert(
            "correlations_cached".to_string(),
            serde_json::Value::Number(serde_json::Number::from(self.correlations.len() as u64)),
        );
        stats
    }

    /// Export the internal state as a serializable value.
    pub fn export_state(&self) -> HashMap<String, serde_json::Value> {
        let mut state = HashMap::new();
        state.insert(
            "closed_a3_count".to_string(),
            serde_json::Value::Number(serde_json::Number::from(self.closed_a3s.len() as u64)),
        );
        state
    }

    /// Get a reference to all correlations.
    pub fn correlations(&self) -> &[CountermeasureCorrelation] {
        &self.correlations
    }
}

impl Default for A3PatternAnalyzer {
    fn default() -> Self {
        Self::new(1000)
    }
}

// ---------------------------------------------------------------------------
// SocraticMentor
// ---------------------------------------------------------------------------

/// Generates Socratic/challenging prompts for mentoring sessions.
///
/// Adapts prompts based on the mentor persona and the current A3 phase.
pub struct SocraticMentor {
    /// Maximum session history entries to retain.
    max_history: usize,
    /// Conversation history per session.
    session_history: HashMap<String, Vec<ChallengingPrompt>>,
    /// Active sessions — maps session_id to (a3_id, start_time).
    active_sessions: HashMap<String, (String, DateTime<Utc>)>,
}

impl SocraticMentor {
    /// Create a new [`SocraticMentor`] with the given history limit.
    pub fn new(max_history: usize) -> Self {
        Self {
            max_history,
            session_history: HashMap::new(),
            active_sessions: HashMap::new(),
        }
    }

    /// Generate challenging prompts for a given content, persona, and phase.
    ///
    /// Prompts are stored in the history under a key derived from the content
    /// (used when no session is active). Prefer
    /// [`SocraticMentor::generate_prompts_for_session`] for session-scoped use.
    pub fn generate_prompts(
        &mut self,
        content: &str,
        persona: MentorPersona,
        phase: A3Phase,
    ) -> Vec<ChallengingPrompt> {
        let prompts = self.build_prompts(content, persona, phase);

        // Track in session history (keyed by a synthetic session key derived from content)
        let session_key = self.extract_key_terms(content).join("_");
        self.session_history
            .entry(session_key)
            .or_default()
            .extend(prompts.clone());

        self.evict_cache_if_needed();

        prompts
    }

    /// Generate challenging prompts for an explicit mentoring session.
    ///
    /// The prompts are recorded under `session_id` so that
    /// [`SocraticMentor::end_session`] and
    /// [`SocraticMentor::get_session_history`] report real per-session stats.
    pub fn generate_prompts_for_session(
        &mut self,
        session_id: &str,
        content: &str,
        persona: MentorPersona,
        phase: A3Phase,
    ) -> Vec<ChallengingPrompt> {
        // Auto-register the session if it was never started.
        if !self.active_sessions.contains_key(session_id) {
            self.active_sessions
                .insert(session_id.to_string(), (String::new(), Utc::now()));
        }

        let prompts = self.build_prompts(content, persona, phase);
        self.session_history
            .entry(session_id.to_string())
            .or_default()
            .extend(prompts.clone());

        self.evict_cache_if_needed();

        prompts
    }

    /// Build the prompt list for the given content without touching history.
    fn build_prompts(
        &self,
        content: &str,
        persona: MentorPersona,
        phase: A3Phase,
    ) -> Vec<ChallengingPrompt> {
        let focused_types = phase_focus(phase);
        let mut prompts = Vec::new();

        for &prompt_type in focused_types {
            let templates = prompt_templates(persona, prompt_type);
            if templates.is_empty() {
                continue;
            }

            let mut rng = rand::thread_rng();
            let idx = rng.gen_range(0..templates.len());
            let chosen = templates[idx];

            // Check if content contains keywords related to this prompt type
            let aspect = self.identify_aspect(content);
            let follow_ups = self.get_follow_ups(prompt_type);

            let prompt = ChallengingPrompt {
                id: Uuid::new_v4(),
                prompt_type,
                content: format!("{} (Ref: {})", chosen, aspect),
                persona,
                phase,
                follow_ups: follow_ups.into_iter().map(|s| s.to_string()).collect(),
                created_at: Utc::now(),
            };

            prompts.push(prompt);
        }

        prompts
    }

    /// Extract key terms from content (simplified — splits on whitespace and
    /// returns unique, non-trivial words).
    fn extract_key_terms(&self, content: &str) -> Vec<String> {
        let stop_words = [
            "the", "a", "an", "is", "are", "was", "were", "be", "been",
            "have", "has", "had", "do", "does", "did", "will", "would",
            "could", "should", "may", "might", "shall", "can", "need",
            "this", "that", "these", "those", "it", "its", "they", "them",
            "their", "we", "us", "our", "you", "your", "he", "she", "his",
            "her", "and", "or", "but", "not", "no", "nor", "so", "if",
            "then", "else", "when", "where", "why", "how", "what", "which",
            "who", "whom", "to", "of", "in", "for", "on", "with", "at",
            "by", "from", "as", "into", "through", "during", "before",
            "after", "above", "below", "between", "out", "off", "over",
            "under", "again", "further", "once",
        ];

        content
            .split(|c: char| !c.is_alphanumeric())
            .filter(|w| w.len() >= 3)
            .map(|w| w.to_lowercase())
            .filter(|w| !stop_words.contains(&w.as_str()))
            .collect()
    }

    /// Identify the aspect of the content (simplified keyword-based).
    fn identify_aspect(&self, content: &str) -> String {
        let lower = content.to_lowercase();
        if lower.contains("defect") || lower.contains("quality") {
            "Quality Issue".to_string()
        } else if lower.contains("delay") || lower.contains("wait") || lower.contains("time") {
            "Timing / Delay".to_string()
        } else if lower.contains("cost") || lower.contains("budget") || lower.contains("expense") {
            "Cost Concern".to_string()
        } else if lower.contains("process") || lower.contains("procedure") || lower.contains("step") {
            "Process Related".to_string()
        } else if lower.contains("people") || lower.contains("team") || lower.contains("training") {
            "People / Skills".to_string()
        } else {
            "General".to_string()
        }
    }

    /// Get follow-up prompts for a given prompt type.
    fn get_follow_ups(&self, prompt_type: PromptType) -> &'static [&'static str] {
        use PromptType::*;
        match prompt_type {
            Exploration => &[
                "Tell me more about that.",
                "What else have you observed?",
                "Can you elaborate on that point?",
            ],
            Reflection => &[
                "How does this compare to past experiences?",
                "What would you do differently next time?",
                "What lessons can you draw from this?",
            ],
            Assumption => &[
                "Why do you believe that is true?",
                "What if the opposite were true?",
                "How could you test that assumption?",
            ],
            Evidence => &[
                "What data supports that claim?",
                "How was that measurement taken?",
                "Can you show me the source?",
            ],
            ActionPlanning => &[
                "What's your first step?",
                "Who needs to be involved?",
                "What could go wrong and how will you mitigate it?",
            ],
            Perspective => &[
                "How would other stakeholders view this?",
                "What's the broader impact?",
                "Consider the long-term implications.",
            ],
        }
    }

    /// Start a mentoring session.
    pub fn start_session(&mut self, session_id: &str, a3_id: &str) {
        self.active_sessions
            .insert(session_id.to_string(), (a3_id.to_string(), Utc::now()));
        // A new session starts with an empty conversation history so per-session
        // stats reflect only this session's prompts.
        self.session_history.remove(session_id);
    }

    /// End a mentoring session and return session statistics.
    pub fn end_session(&mut self, session_id: &str) -> HashMap<String, serde_json::Value> {
        let mut stats = HashMap::new();
        if let Some((_a3_id, start_time)) = self.active_sessions.remove(session_id) {
            let duration = Utc::now() - start_time;
            let duration_minutes = duration.num_minutes();
            let history = self.session_history.get(session_id).map_or(0, |v| v.len());

            stats.insert(
                "session_duration_minutes".to_string(),
                serde_json::Value::Number(serde_json::Number::from(duration_minutes.max(0) as u64)),
            );
            stats.insert(
                "prompts_generated".to_string(),
                serde_json::Value::Number(serde_json::Number::from(history as u64)),
            );
        } else {
            stats.insert(
                "error".to_string(),
                serde_json::Value::String("Session not found".to_string()),
            );
        }
        stats
    }

    /// Evict the oldest 25 % of session histories when the limit is exceeded.
    fn evict_cache_if_needed(&mut self) {
        let total: usize = self.session_history.values().map(|v| v.len()).sum();
        if total <= self.max_history {
            return;
        }

        // Simple eviction: clear everything beyond max_history
        let mut all_entries: Vec<(String, ChallengingPrompt)> = self
            .session_history
            .iter()
            .flat_map(|(key, prompts)| {
                prompts.iter().map(|p| (key.clone(), p.clone()))
            })
            .collect();

        all_entries.sort_by(|a, b| a.1.created_at.cmp(&b.1.created_at));

        let target = self.max_history * 3 / 4; // keep 75 %
        let to_remove = all_entries.len().saturating_sub(target);

        self.session_history.clear();
        for (key, prompt) in all_entries.into_iter().skip(to_remove) {
            self.session_history.entry(key).or_default().push(prompt);
        }
    }

    /// Get the conversation history for a session.
    pub fn get_session_history(&self, session_id: &str) -> Vec<ChallengingPrompt> {
        self.session_history
            .get(session_id)
            .cloned()
            .unwrap_or_default()
    }

    /// Export internal state.
    pub fn export_state(&self) -> HashMap<String, serde_json::Value> {
        let mut state = HashMap::new();
        state.insert(
            "active_sessions".to_string(),
            serde_json::Value::Number(serde_json::Number::from(self.active_sessions.len() as u64)),
        );
        state.insert(
            "total_history".to_string(),
            serde_json::Value::Number(serde_json::Number::from(
                self.session_history.values().map(|v| v.len()).sum::<usize>() as u64,
            )),
        );
        state
    }
}

impl Default for SocraticMentor {
    fn default() -> Self {
        Self::new(5000)
    }
}

// ---------------------------------------------------------------------------
// FiveWhysAssistant
// ---------------------------------------------------------------------------

/// Performs 5-Whys root cause analysis and waste classification.
///
/// Uses keyword-based pattern matching to identify waste categories, muda
/// types, and potential root causes from problem descriptions.
#[allow(dead_code)]
pub struct FiveWhysAssistant {
    /// Maximum number of historical cause entries.
    max_history: usize,
    /// Historical (problem, cause) pairs.
    historical_causes: Vec<(String, String)>,
    /// Maximum historical entries before eviction.
    max_historical_causes: usize,
}

impl FiveWhysAssistant {
    /// Create a new [`FiveWhysAssistant`].
    pub fn new(max_history: usize) -> Self {
        Self {
            max_history,
            historical_causes: Vec::new(),
            max_historical_causes: 5000,
        }
    }

    /// Analyze a problem description using the 5 Whys method.
    ///
    /// Returns a list of [`RootCauseSuggestion`] items sorted by pattern
    /// match score (highest first).
    pub fn analyze_problem(&mut self, problem: &str) -> Vec<RootCauseSuggestion> {
        let patterns = root_cause_patterns();
        let mut suggestions: Vec<(f64, RootCauseSuggestion)> = patterns
            .iter()
            .map(|pattern| {
                let score = self.calculate_pattern_match(problem, pattern.pattern);
                if score > 0.0 {
                    let (waste, muda) = self.classify_from_text(problem);
                    (
                        score,
                        RootCauseSuggestion {
                            cause: pattern.category.to_string(),
                            pattern_match_score: score,
                            evidence_needed: pattern
                                .evidence_questions
                                .iter()
                                .map(|s| s.to_string())
                                .collect(),
                            related_waste: waste,
                            related_muda: muda,
                        },
                    )
                } else {
                    (0.0, RootCauseSuggestion {
                        cause: pattern.category.to_string(),
                        pattern_match_score: 0.0,
                        evidence_needed: Vec::new(),
                        related_waste: None,
                        related_muda: None,
                    })
                }
            })
            .filter(|(score, _)| *score > 0.0)
            .collect();

        // Sort by score descending
        suggestions.sort_by(|a, b| {
            b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal)
        });

        let result: Vec<RootCauseSuggestion> = suggestions
            .into_iter()
            .map(|(_, s)| s)
            .collect();

        // Store in historical causes
        if let Some(best) = result.first() {
            self.add_historical_cause(problem, &best.cause);
        }

        result
    }

    /// Calculate pattern match score based on keyword density.
    fn calculate_pattern_match(&self, text: &str, pattern: &str) -> f64 {
        let lower = text.to_lowercase();
        let keywords: Vec<&str> = pattern.split('|').collect();
        if keywords.is_empty() {
            return 0.0;
        }

        let total_words = text.split_whitespace().count();
        if total_words == 0 {
            return 0.0;
        }

        let matches: usize = keywords
            .iter()
            .filter(|kw| lower.contains(*kw))
            .count();

        // Score = (matches / total_keywords) * coverage_factor
        let ratio = matches as f64 / keywords.len() as f64;
        let coverage = ratio.min(1.0);
        coverage
    }

    /// Classify waste category and muda type from text.
    fn classify_from_text(&self, text: &str) -> (Option<LeanWasteCategory>, Option<MudaType>) {
        let waste = self.classify_waste(text);
        let muda = self.classify_muda_type(text);
        (waste, muda)
    }

    /// Classify the lean waste category based on keyword matching.
    pub fn classify_waste(&self, text: &str) -> Option<LeanWasteCategory> {
        let lower = text.to_lowercase();
        let mut best_category = None;
        let mut best_score = 0.0f64;

        for (category, keywords) in waste_keywords() {
            let matches: usize = keywords
                .iter()
                .filter(|kw| lower.contains(*kw))
                .count();
            let score = matches as f64 / keywords.len() as f64;

            if score > best_score {
                best_score = score;
                best_category = Some(category);
            }
        }

        best_category.filter(|_| best_score > 0.05)
    }

    /// Classify the muda type based on keyword matching.
    pub fn classify_muda_type(&self, text: &str) -> Option<MudaType> {
        let lower = text.to_lowercase();
        let mut best_type = None;
        let mut best_score = 0.0f64;

        for (muda_type, keywords) in muda_keywords() {
            let matches: usize = keywords
                .iter()
                .filter(|kw| lower.contains(*kw))
                .count();
            let score = matches as f64 / keywords.len() as f64;

            if score > best_score {
                best_score = score;
                best_type = Some(muda_type);
            }
        }

        best_type.filter(|_| best_score > 0.05)
    }

    /// Find similar historical causes.
    pub fn find_similar_historical(&self, pattern: &str) -> Vec<String> {
        let lower_pattern = pattern.to_lowercase();
        let mut matches: Vec<(usize, &str)> = self
            .historical_causes
            .iter()
            .filter_map(|(problem, cause)| {
                if problem.to_lowercase().contains(&lower_pattern) {
                    Some((0, cause.as_str()))
                } else {
                    // Simple word overlap
                    let pattern_words: Vec<&str> = lower_pattern
                        .split_whitespace()
                        .filter(|w| w.len() > 3)
                        .collect();
                    let overlap: usize = pattern_words
                        .iter()
                        .filter(|w| problem.to_lowercase().contains(*w))
                        .count();
                    if overlap > 0 {
                        Some((overlap, cause.as_str()))
                    } else {
                        None
                    }
                }
            })
            .collect();

        matches.sort_by(|a, b| b.0.cmp(&a.0));
        matches.dedup_by(|a, b| a.1 == b.1);

        matches.into_iter().take(5).map(|(_, s)| s.to_string()).collect()
    }

    /// Get evidence needs for a given pattern.
    pub fn get_evidence_needs(&self, pattern: &str) -> Vec<String> {
        let patterns = root_cause_patterns();
        for p in &patterns {
            let lower_pattern = pattern.to_lowercase();
            let keywords: Vec<&str> = p.pattern.split('|').collect();
            if keywords.iter().any(|kw| lower_pattern.contains(kw)) {
                return p.evidence_questions.iter().map(|s| s.to_string()).collect();
            }
        }
        vec![
            "What data supports this finding?".to_string(),
            "Can you verify this through direct observation?".to_string(),
            "What measurements confirm this analysis?".to_string(),
        ]
    }

    /// Add a historical cause entry.
    pub fn add_historical_cause(&mut self, problem: &str, cause: &str) {
        self.historical_causes
            .push((problem.to_string(), cause.to_string()));

        if self.historical_causes.len() > self.max_historical_causes {
            let to_remove = self.max_historical_causes / 4;
            self.historical_causes.drain(..to_remove);
        }
    }

    /// Get a summary of waste categories found in the historical data.
    pub fn get_waste_summary(&self) -> Vec<(LeanWasteCategory, usize)> {
        let mut counts: HashMap<LeanWasteCategory, usize> = HashMap::new();
        for (problem, _) in &self.historical_causes {
            if let Some(waste) = self.classify_waste(problem) {
                *counts.entry(waste).or_insert(0) += 1;
            }
        }

        let mut result: Vec<(LeanWasteCategory, usize)> = counts.into_iter().collect();
        result.sort_by(|a, b| b.1.cmp(&a.1));
        result
    }

    /// Export state.
    pub fn export_state(&self) -> HashMap<String, serde_json::Value> {
        let mut state = HashMap::new();
        state.insert(
            "historical_causes_count".to_string(),
            serde_json::Value::Number(serde_json::Number::from(self.historical_causes.len() as u64)),
        );
        state
    }
}

impl Default for FiveWhysAssistant {
    fn default() -> Self {
        Self::new(5000)
    }
}

// ---------------------------------------------------------------------------
// SenseiReasoningEngine
// ---------------------------------------------------------------------------

/// Unified reasoning engine that orchestrates A3 analysis, Socratic mentoring,
/// and 5 Whys root cause analysis.
pub struct SenseiReasoningEngine {
    pub pattern_analyzer: A3PatternAnalyzer,
    pub socratic_mentor: SocraticMentor,
    pub five_whys: FiveWhysAssistant,
}

impl SenseiReasoningEngine {
    /// Create a new [`SenseiReasoningEngine`].
    pub fn new() -> Self {
        Self {
            pattern_analyzer: A3PatternAnalyzer::default(),
            socratic_mentor: SocraticMentor::default(),
            five_whys: FiveWhysAssistant::default(),
        }
    }

    /// Register a closed A3 report for pattern analysis.
    pub fn register_closed_a3(&mut self, a3: A3Report) {
        self.pattern_analyzer.add_closed_a3(a3);
    }

    /// Suggest countermeasures for a waste category.
    pub fn suggest_countermeasures(
        &mut self,
        waste_category: &str,
    ) -> Vec<CountermeasureCorrelation> {
        self.pattern_analyzer.suggest_countermeasures(waste_category)
    }

    /// Generate challenging prompts for a session.
    pub fn generate_socratic_prompts(
        &mut self,
        session_id: &str,
        content: &str,
        persona: MentorPersona,
        phase: A3Phase,
    ) -> Vec<ChallengingPrompt> {
        self.socratic_mentor
            .generate_prompts_for_session(session_id, content, persona, phase)
    }

    /// Analyze root cause using 5 Whys.
    pub fn analyze_root_cause(&mut self, problem: &str) -> Vec<RootCauseSuggestion> {
        self.five_whys.analyze_problem(problem)
    }

    /// Classify waste category from text.
    pub fn classify_waste(&self, text: &str) -> Option<LeanWasteCategory> {
        self.five_whys.classify_waste(text)
    }

    /// Classify muda type from text.
    pub fn classify_muda_type(&self, text: &str) -> Option<MudaType> {
        self.five_whys.classify_muda_type(text)
    }

    /// Start a Socratic mentoring session.
    pub fn start_mentoring_session(&mut self, session_id: &str, a3_id: &str) {
        self.socratic_mentor.start_session(session_id, a3_id);
    }

    /// End a mentoring session.
    pub fn end_mentoring_session(&mut self, session_id: &str) -> HashMap<String, serde_json::Value> {
        self.socratic_mentor.end_session(session_id)
    }

    /// Get engine statistics.
    pub fn get_stats(&self) -> HashMap<String, serde_json::Value> {
        let mut stats = self.pattern_analyzer.get_stats();
        stats.insert(
            "five_whys_historical_causes".to_string(),
            serde_json::Value::Number(serde_json::Number::from(
                self.five_whys.historical_causes.len() as u64,
            )),
        );
        stats
    }
}

impl Default for SenseiReasoningEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -- A3PatternAnalyzer Tests ---------------------------------------------

    #[test]
    fn test_kpi_is_on_target() {
        let kpi = KPIMetric {
            name: "OEE".to_string(),
            current_value: 85.0,
            target_value: 80.0,
            baseline_value: 65.0,
            unit: "%".to_string(),
            trend: KPITrend::Improving,
            measured_at: Utc::now(),
        };
        assert!(kpi.is_on_target());

        let kpi_below = KPIMetric {
            name: "OEE".to_string(),
            current_value: 60.0,
            target_value: 80.0,
            baseline_value: 65.0,
            unit: "%".to_string(),
            trend: KPITrend::Declining,
            measured_at: Utc::now(),
        };
        assert!(!kpi_below.is_on_target());
    }

    #[test]
    fn test_add_closed_a3() {
        let mut analyzer = A3PatternAnalyzer::new(10);
        let a3 = A3Report {
            id: Uuid::new_v4(),
            title: "Test A3".to_string(),
            problem_statement: "Defect rate too high".to_string(),
            waste_category: Some(LeanWasteCategory::Defects),
            muda_type: None,
            countermeasures: vec![],
            kpis: vec![],
            closed_at: Utc::now(),
        };
        analyzer.add_closed_a3(a3);
        assert_eq!(analyzer.closed_a3s.len(), 1);
    }

    #[test]
    fn test_cache_eviction() {
        let mut analyzer = A3PatternAnalyzer::new(4);
        for i in 0..6 {
            let a3 = A3Report {
                id: Uuid::new_v4(),
                title: format!("A3 {}", i),
                problem_statement: format!("Problem {}", i),
                waste_category: None,
                muda_type: None,
                countermeasures: vec![],
                kpis: vec![],
                closed_at: Utc::now(),
            };
            analyzer.add_closed_a3(a3);
        }
        // With max_history=4 and 6 insertions, 25% of 4 = 1 should be evicted,
        // so we expect 4 entries (the most recent 4)
        assert_eq!(analyzer.closed_a3s.len(), 4);
    }

    #[test]
    fn test_suggest_countermeasures() {
        let mut analyzer = A3PatternAnalyzer::new(100);

        let a3 = A3Report {
            id: Uuid::new_v4(),
            title: "Defect Reduction".to_string(),
            problem_statement: "High defect rate on line A".to_string(),
            waste_category: Some(LeanWasteCategory::Defects),
            muda_type: Some(MudaType::Correction),
            countermeasures: vec![
                Countermeasure {
                    id: Uuid::new_v4(),
                    description: "Implement poka-yoke".to_string(),
                    category: "Quality".to_string(),
                    expected_impact: "Reduce defects by 50%".to_string(),
                    effort: "Medium".to_string(),
                    owner: "QA Team".to_string(),
                    target_date: Utc::now(),
                },
            ],
            kpis: vec![
                KPIMetric {
                    name: "Defect Rate".to_string(),
                    current_value: 2.0,
                    target_value: 1.0,
                    baseline_value: 5.0,
                    unit: "%".to_string(),
                    trend: KPITrend::Improving,
                    measured_at: Utc::now(),
                },
            ],
            closed_at: Utc::now(),
        };
        analyzer.add_closed_a3(a3);

        let suggestions = analyzer.suggest_countermeasures("Quality");
        assert!(!suggestions.is_empty());
    }

    // -- SocraticMentor Tests ------------------------------------------------

    #[test]
    fn test_generate_prompts() {
        let mut mentor = SocraticMentor::new(1000);
        let prompts = mentor.generate_prompts(
            "We have too many defects on the assembly line",
            MentorPersona::CriticalThinker,
            A3Phase::RootCauseAnalysis,
        );
        assert!(!prompts.is_empty());
        // Should return prompts for Assumption, Evidence, and Exploration types
        assert!(prompts.len() >= 2);
    }

    #[test]
    fn test_mentor_session_management() {
        let mut mentor = SocraticMentor::new(1000);
        mentor.start_session("session-1", "a3-123");
        mentor.generate_prompts(
            "Test content",
            MentorPersona::LeanCoach,
            A3Phase::ProblemDefinition,
        );
        let stats = mentor.end_session("session-1");
        assert!(stats.contains_key("session_duration_minutes"));
    }

    #[test]
    fn test_identify_aspect() {
        let mentor = SocraticMentor::new(1000);
        assert_eq!(mentor.identify_aspect("defect on line"), "Quality Issue");
        assert_eq!(mentor.identify_aspect("process improvement"), "Process Related");
        assert_eq!(mentor.identify_aspect("general topic"), "General");
    }

    // -- FiveWhysAssistant Tests ---------------------------------------------

    #[test]
    fn test_classify_waste() {
        let assistant = FiveWhysAssistant::new(5000);
        assert_eq!(
            assistant.classify_waste("We have defects in production"),
            Some(LeanWasteCategory::Defects)
        );
        assert_eq!(
            assistant.classify_waste("Long waiting times between operations"),
            Some(LeanWasteCategory::Waiting)
        );
        assert_eq!(
            assistant.classify_waste("No relevant keywords here"),
            None
        );
    }

    #[test]
    fn test_classify_muda() {
        let assistant = FiveWhysAssistant::new(5000);
        assert_eq!(
            assistant.classify_muda_type("Need to fix this rework issue"),
            Some(MudaType::Correction)
        );
        assert_eq!(
            assistant.classify_muda_type("Operators waiting for materials"),
            Some(MudaType::WaitTime)
        );
    }

    #[test]
    fn test_analyze_problem() {
        let mut assistant = FiveWhysAssistant::new(5000);
        let results = assistant.analyze_problem(
            "Operators lack proper training on the new standard work procedure"
        );
        assert!(!results.is_empty());
        // Should match "training" pattern → "Insufficient Training"
        assert!(results.iter().any(|r| r.cause.contains("Training")));
    }

    #[test]
    fn test_evidence_needs() {
        let assistant = FiveWhysAssistant::new(5000);
        let needs = assistant.get_evidence_needs("standard work instruction");
        assert!(!needs.is_empty());
        assert!(needs[0].contains("standard"));
    }

    #[test]
    fn test_historical_cause_eviction() {
        let mut assistant = FiveWhysAssistant::new(10);
        assistant.max_historical_causes = 4;

        for i in 0..6 {
            assistant.add_historical_cause(
                &format!("Problem {}", i),
                &format!("Cause {}", i),
            );
        }
        // After 6 insertions with max 4, oldest 25% (1) should be evicted, so 3 remain
        assert!(assistant.historical_causes.len() <= 4);
    }

    // -- SenseiReasoningEngine Integration Tests ------------------------------

    #[test]
    fn test_reasoning_engine_full_workflow() {
        let mut engine = SenseiReasoningEngine::new();

        // 1. Register a closed A3
        let a3 = A3Report {
            id: Uuid::new_v4(),
            title: "Reduce Setup Time".to_string(),
            problem_statement: "Long changeover times on press line".to_string(),
            waste_category: Some(LeanWasteCategory::Waiting),
            muda_type: Some(MudaType::WaitTime),
            countermeasures: vec![Countermeasure {
                id: Uuid::new_v4(),
                description: "Implement SMED".to_string(),
                category: "Setup Reduction".to_string(),
                expected_impact: "Reduce setup by 50%".to_string(),
                effort: "High".to_string(),
                owner: "Production".to_string(),
                target_date: Utc::now(),
            }],
            kpis: vec![KPIMetric {
                name: "Setup Time".to_string(),
                current_value: 15.0,
                target_value: 10.0,
                baseline_value: 30.0,
                unit: "min".to_string(),
                trend: KPITrend::Improving,
                measured_at: Utc::now(),
            }],
            closed_at: Utc::now(),
        };
        engine.register_closed_a3(a3);

        // 2. Generate Socratic prompts (session-scoped)
        engine.start_mentoring_session("test-session", "a3-001");
        let prompts = engine.generate_socratic_prompts(
            "test-session",
            "Setup time is too long",
            MentorPersona::ProcessImprover,
            A3Phase::CurrentState,
        );
        assert!(!prompts.is_empty());

        // 3. Analyze root cause
        let causes = engine.analyze_root_cause(
            "Operators spend too much time searching for tools during changeover"
        );
        assert!(!causes.is_empty());

        // 4. Classify waste
        let waste = engine.classify_waste("Long waiting times during setup");
        assert_eq!(waste, Some(LeanWasteCategory::Waiting));

        // 5. End the session — stats must reflect the prompts generated.
        let stats = engine.end_mentoring_session("test-session");
        assert!(stats.contains_key("session_duration_minutes"));
        assert_eq!(
            stats.get("prompts_generated").unwrap().as_u64().unwrap(),
            prompts.len() as u64,
            "session stats must count the prompts generated in this session"
        );
    }

    #[test]
    fn test_session_prompts_are_keyed_by_session_id() {
        let mut mentor = SocraticMentor::new(1000);
        mentor.start_session("session-a", "a3-a");
        mentor.start_session("session-b", "a3-b");

        mentor.generate_prompts_for_session(
            "session-a",
            "defect rate rising",
            MentorPersona::ProcessImprover,
            A3Phase::ProblemDefinition,
        );
        mentor.generate_prompts_for_session(
            "session-a",
            "defect rate rising more",
            MentorPersona::ProcessImprover,
            A3Phase::CurrentState,
        );
        mentor.generate_prompts_for_session(
            "session-b",
            "cost overruns",
            MentorPersona::Challenger,
            A3Phase::ProblemDefinition,
        );

        // Histories must be isolated per session.
        assert!(!mentor.get_session_history("session-a").is_empty());
        assert!(!mentor.get_session_history("session-b").is_empty());

        let stats = mentor.end_session("session-a");
        assert!(
            stats.get("prompts_generated").unwrap().as_u64().unwrap() > 0,
            "end_session must report the prompts recorded for session-a"
        );
    }
}
