from typing import Any
from fastapi import APIRouter, Depends
from sensei.services.ai.enhanced_ml_pipeline import get_ml_pipeline_service, EnhancedMLPipelineService
from sensei.services.analytics_warehouse import AnalyticsWarehouseService
from sensei.api import deps

router = APIRouter()

# Simple singleton for AnalyticsWarehouseService as well
_analytics_warehouse_service = AnalyticsWarehouseService()

def get_analytics_warehouse_service() -> AnalyticsWarehouseService:
    return _analytics_warehouse_service

@router.get("/health", response_model=dict[str, Any])
async def get_analytics_health(
    ml_service: EnhancedMLPipelineService = Depends(get_ml_pipeline_service),
    current_user: Any = Depends(deps.get_token_data)
):
    """Get ML pipeline health and statistics."""
    return ml_service.get_pipeline_health()

@router.get("/insights", response_model=list[dict[str, Any]])
async def get_ml_insights(
    ml_service: EnhancedMLPipelineService = Depends(get_ml_pipeline_service),
    current_user: Any = Depends(deps.get_token_data)
):
    """Get AI/ML driven insights."""
    # In a real system, these would be generated by models in the registry
    # For now, we provide some representative high-value insights
    return [
        {
            "id": "insight_1",
            "type": "prediction",
            "title": "Quote Success Rate Declining",
            "description": "ML model predicts 15% drop in quote win rate over next 30 days based on current pipeline trends.",
            "confidence": 0.87,
            "impact": "high",
            "category": "Sales",
            "model_name": "quote_win_predictor",
            "action_items": ["Review pricing strategy", "Increase follow-up frequency"]
        },
        {
            "id": "insight_2",
            "type": "anomaly",
            "title": "Unusual Production Downtime Pattern",
            "description": "Machine #3 showing 23% increase in unplanned stops. Pattern suggests preventive maintenance needed.",
            "confidence": 0.92,
            "impact": "high",
            "category": "Production",
            "model_name": "cbm_predictor",
            "action_items": ["Schedule inspection for Machine #3"]
        }
    ]

@router.get("/trends", response_model=list[dict[str, Any]])
async def get_performance_trends(
    current_user: Any = Depends(deps.get_token_data)
):
    """Get key performance indicators and their trends."""
    return [
        {
            "metric": "First Pass Yield",
            "current_value": 94.2,
            "previous_value": 92.8,
            "change_percent": 1.5,
            "trend": "up",
            "prediction_7d": 94.5
        },
        {
            "metric": "Average Cycle Time",
            "current_value": 42.5,
            "previous_value": 45.2,
            "change_percent": -5.9,
            "trend": "down",
            "prediction_7d": 41.8
        }
    ]
