from typing import Any, Annotated, TypeAlias
from fastapi import APIRouter, Depends
from sensei.services.ai.enhanced_ml_pipeline import get_ml_pipeline_service, EnhancedMLPipelineService
from sensei.services.ops.analytics_warehouse import AnalyticsWarehouseService, FactType
from sensei.services.core.role_insights_config import filter_insights_for_role
from sensei.api import deps
from sensei.core.pii import mask_analytics_data

router = APIRouter()

# Role requirements
AllowAnalytics: TypeAlias = deps.require_role("admin", "ceo", "gm", "exec", "ops", "finance", "quality")  # type: ignore[valid-type]
AllowAdminAnalytics: TypeAlias = deps.require_role("admin", "ceo", "gm")  # type: ignore[valid-type]

# Simple singleton for AnalyticsWarehouseService as well
_analytics_warehouse_service = AnalyticsWarehouseService()

def get_analytics_warehouse_service() -> AnalyticsWarehouseService:
    return _analytics_warehouse_service

@router.get("/health", response_model=dict[str, Any])
async def get_analytics_health(
    _: AllowAnalytics,
    ml_service: EnhancedMLPipelineService = Depends(get_ml_pipeline_service),
    current_user: Any = Depends(deps.get_token_data)
):
    """Get ML pipeline health and statistics."""
    return ml_service.get_pipeline_health()

@router.get("/insights", response_model=list[dict[str, Any]])
async def get_ml_insights(
    _: AllowAnalytics,
    ml_service: EnhancedMLPipelineService = Depends(get_ml_pipeline_service),
    token_data: deps.TokenData = Depends(deps.get_token_data)
):
    """Get AI/ML driven insights filtered by user role."""
    # In a real system, these would be generated by models in the registry
    # For now, we provide some representative high-value insights
    all_insights = [
        {
            "id": "insight_1",
            "type": "prediction",
            "title": "Quote Success Rate Declining",
            "description": "ML model predicts 15% drop in quote win rate over next 30 days based on current pipeline trends.",
            "confidence": 0.87,
            "impact": "high",
            "category": "PIPELINE_HEALTH",  # InsightCategory for proper filtering
            "model_name": "quote_win_predictor",
            "action_items": ["Review pricing strategy", "Increase follow-up frequency"]
        },
        {
            "id": "insight_2",
            "type": "anomaly",
            "title": "Unusual Production Downtime Pattern",
            "description": "Machine #3 showing 23% increase in unplanned stops. Pattern suggests preventive maintenance needed.",
            "confidence": 0.92,
            "impact": "high",
            "category": "PRODUCTION_EFFICIENCY",  # InsightCategory for proper filtering
            "model_name": "cbm_predictor",
            "action_items": ["Schedule inspection for Machine #3"]
        },
        {
            "id": "insight_3",
            "type": "forecast",
            "title": "Cash Flow Projection",
            "description": "Based on current AR/AP patterns, cash flow expected to tighten in next 45 days.",
            "confidence": 0.85,
            "impact": "high",
            "category": "CASH_FLOW_FORECAST",  # Financial insight - restricted
            "model_name": "cash_flow_predictor",
            "action_items": ["Review payment terms", "Accelerate collections"]
        },
        {
            "id": "insight_4",
            "type": "quality",
            "title": "Quality Trend Alert",
            "description": "SPC analysis shows process trending toward upper control limit on Line 2.",
            "confidence": 0.89,
            "impact": "medium",
            "category": "SPC_ALERTS",  # Quality insight
            "model_name": "spc_monitor",
            "action_items": ["Review Line 2 process parameters"]
        },
        {
            "id": "insight_5",
            "type": "maintenance",
            "title": "Predictive Maintenance Alert",
            "description": "Bearing degradation detected on CNC Mill #7. Estimated 2-3 weeks to failure.",
            "confidence": 0.91,
            "impact": "high",
            "category": "EQUIPMENT_ALERTS",  # Maintenance insight
            "model_name": "cbm_predictor",
            "action_items": ["Schedule bearing replacement", "Order replacement parts"]
        },
        {
            "id": "insight_6",
            "type": "strategic",
            "title": "Market Opportunity Detected",
            "description": "Competitor pricing analysis suggests opportunity in aerospace sector.",
            "confidence": 0.78,
            "impact": "high",
            "category": "COMPETITIVE_INTEL",  # Executive insight - restricted
            "model_name": "market_analyzer",
            "action_items": ["Review aerospace capability", "Prepare marketing materials"]
        }
    ]
    
    # INTEGRATED: Filter insights based on user's roles
    filtered_insights = filter_insights_for_role(all_insights, token_data.roles)
    
    return await mask_analytics_data(filtered_insights, token_data.roles)

@router.get("/trends", response_model=list[dict[str, Any]])
async def get_performance_trends(
    _: AllowAnalytics,
    db: deps.DBSession,
    warehouse: AnalyticsWarehouseService = Depends(get_analytics_warehouse_service),
    token_data: deps.TokenData = Depends(deps.get_token_data)
):
    """Get key performance indicators and their trends."""
    # Attempt to fetch real data from warehouse
    records = await warehouse.get_exported_records(
        db=db,
        actor_roles=token_data.roles,
        fact_type=FactType.QUALITY_METRIC
    )
    
    if records:
        # Transform warehouse records to trend format
        trends = []
        for r in records[:5]: # Take last 5
            trends.append({
                "metric": r.data.get("metric_name", "Unknown"),
                "current_value": r.data.get("value", 0),
                "previous_value": r.data.get("previous_value", 0),
                "change_percent": r.data.get("change_percent", 0),
                "trend": "up" if r.data.get("change_percent", 0) > 0 else "down",
                "prediction_7d": r.data.get("predicted_value", 0)
            })
        return await mask_analytics_data(trends, token_data.roles)

    # Fallback to demo data if warehouse is empty
    demo_trends = [
        {
            "metric": "First Pass Yield",
            "current_value": 94.2,
            "previous_value": 92.8,
            "change_percent": 1.5,
            "trend": "up",
            "prediction_7d": 94.5
        },
        {
            "metric": "Average Cycle Time",
            "current_value": 42.5,
            "previous_value": 45.2,
            "change_percent": -5.9,
            "trend": "down",
            "prediction_7d": 41.8
        }
    ]
    return await mask_analytics_data(demo_trends, token_data.roles)
