from typing import Any, Annotated
from fastapi import APIRouter, Depends
from sensei.services.ai.enhanced_ml_pipeline import get_ml_pipeline_service, EnhancedMLPipelineService
from sensei.services.ops.analytics_warehouse import AnalyticsWarehouseService, FactType
from sensei.api import deps
from sensei.core.pii import mask_analytics_data

router = APIRouter()

# Role requirements
AllowAnalytics = deps.require_role("admin", "ceo", "gm", "exec", "ops", "finance", "quality")
AllowAdminAnalytics = deps.require_role("admin", "ceo", "gm")

# Simple singleton for AnalyticsWarehouseService as well
_analytics_warehouse_service = AnalyticsWarehouseService()

def get_analytics_warehouse_service() -> AnalyticsWarehouseService:
    return _analytics_warehouse_service

@router.get("/health", response_model=dict[str, Any])
async def get_analytics_health(
    _: AllowAnalytics,
    ml_service: EnhancedMLPipelineService = Depends(get_ml_pipeline_service),
    current_user: Any = Depends(deps.get_token_data)
):
    """Get ML pipeline health and statistics."""
    return ml_service.get_pipeline_health()

@router.get("/insights", response_model=list[dict[str, Any]])
async def get_ml_insights(
    _: AllowAnalytics,
    ml_service: EnhancedMLPipelineService = Depends(get_ml_pipeline_service),
    token_data: deps.TokenData = Depends(deps.get_token_data)
):
    """Get AI/ML driven insights."""
    # In a real system, these would be generated by models in the registry
    # For now, we provide some representative high-value insights
    insights = [
        {
            "id": "insight_1",
            "type": "prediction",
            "title": "Quote Success Rate Declining",
            "description": "ML model predicts 15% drop in quote win rate over next 30 days based on current pipeline trends.",
            "confidence": 0.87,
            "impact": "high",
            "category": "Sales",
            "model_name": "quote_win_predictor",
            "action_items": ["Review pricing strategy", "Increase follow-up frequency"]
        },
        {
            "id": "insight_2",
            "type": "anomaly",
            "title": "Unusual Production Downtime Pattern",
            "description": "Machine #3 showing 23% increase in unplanned stops. Pattern suggests preventive maintenance needed.",
            "confidence": 0.92,
            "impact": "high",
            "category": "Production",
            "model_name": "cbm_predictor",
            "action_items": ["Schedule inspection for Machine #3"]
        }
    ]
    return mask_analytics_data(insights, token_data.roles)

@router.get("/trends", response_model=list[dict[str, Any]])
async def get_performance_trends(
    _: AllowAnalytics,
    db: deps.DBSession,
    warehouse: AnalyticsWarehouseService = Depends(get_analytics_warehouse_service),
    token_data: deps.TokenData = Depends(deps.get_token_data)
):
    """Get key performance indicators and their trends."""
    # Attempt to fetch real data from warehouse
    records = await warehouse.get_exported_records(
        db=db,
        actor_roles=token_data.roles,
        fact_type=FactType.QUALITY_METRIC
    )
    
    if records:
        # Transform warehouse records to trend format
        trends = []
        for r in records[:5]: # Take last 5
            trends.append({
                "metric": r.data.get("metric_name", "Unknown"),
                "current_value": r.data.get("value", 0),
                "previous_value": r.data.get("previous_value", 0),
                "change_percent": r.data.get("change_percent", 0),
                "trend": "up" if r.data.get("change_percent", 0) > 0 else "down",
                "prediction_7d": r.data.get("predicted_value", 0)
            })
        return mask_analytics_data(trends, token_data.roles)

    # Fallback to demo data if warehouse is empty
    demo_trends = [
        {
            "metric": "First Pass Yield",
            "current_value": 94.2,
            "previous_value": 92.8,
            "change_percent": 1.5,
            "trend": "up",
            "prediction_7d": 94.5
        },
        {
            "metric": "Average Cycle Time",
            "current_value": 42.5,
            "previous_value": 45.2,
            "change_percent": -5.9,
            "trend": "down",
            "prediction_7d": 41.8
        }
    ]
    return mask_analytics_data(demo_trends, token_data.roles)
