import json
import os

# Path to the French locale file
FR_FILE_PATH = 'frontend/src/locales/fr.json'

# Dictionary of English -> French translations
# Focused on ERP, Management, Manufacturing, and common UI terms
TRANSLATIONS = {
    # Common Actions & Buttons
    "Save": "Enregistrer",
    "Cancel": "Annuler",
    "Delete": "Supprimer",
    "Edit": "Modifier",
    "Create": "Créer",
    "Add": "Ajouter",
    "Update": "Mettre à jour",
    "View": "Voir",
    "Search": "Rechercher",
    "Filter": "Filtrer",
    "Sort": "Trier",
    "Export": "Exporter",
    "Import": "Importer",
    "Download": "Télécharger",
    "Upload": "Téléverser",
    "Submit": "Soumettre",
    "Confirm": "Confirmer",
    "Back": "Retour",
    "Next": "Suivant",
    "Previous": "Précédent",
    "Close": "Fermer",
    "Open": "Ouvrir",
    "Refresh": "Actualiser",
    "Reset": "Réinitialiser",
    "Apply": "Appliquer",
    "Clear": "Effacer",
    "Copy": "Copier",
    "Paste": "Coller",
    "Print": "Imprimer",
    "Send": "Envoyer",
    "Share": "Partager",
    "Done": "Terminé",
    "Finish": "Finir",
    "Continue": "Continuer",
    "Login": "Connexion",
    "Logout": "Déconnexion",
    "Sign In": "Se connecter",
    "Sign Out": "Se déconnecter",
    "Register": "S'inscrire",
    "Subscribe": "S'abonner",
    "Unsubscribe": "Se désabonner",
    
    # Common Statuses
    "Pending": "En attente",
    "In Progress": "En cours",
    "Completed": "Terminé",
    "Finished": "Fini",
    "Done": "Fait",
    "Draft": "Brouillon",
    "Active": "Actif",
    "Inactive": "Inactif",
    "Enabled": "Activé",
    "Disabled": "Désactivé",
    "Open": "Ouvert",
    "Closed": "Fermé",
    "Archived": "Archivé",
    "Deleted": "Supprimé",
    "Success": "Succès",
    "Error": "Erreur",
    "Warning": "Avertissement",
    "Info": "Info",
    "Failed": "Échoué",
    "Paid": "Payé",
    "Unpaid": "Impayé",
    "Overdue": "En retard",
    "Refunded": "Remboursé",
    "Cancelled": "Annulé",
    "Shipped": "Expédié",
    "Delivered": "Livré",
    "Returned": "Retourné",
    "Processing": "Traitement",
    "Review": "Revue",
    "Approved": "Approuvé",
    "Rejected": "Rejeté",
    "On Hold": "En attente",
    "Scheduled": "Planifié",
    "Picked": "Préparé",
    "Packed": "Emballé",
    
    # Navigation & modules
    "Dashboard": "Tableau de bord",
    "Home": "Accueil",
    "Settings": "Paramètres",
    "Profile": "Profil",
    "Account": "Compte",
    "Notifications": "Notifications",
    "Messages": "Messages",
    "Calendar": "Calendrier",
    "Tasks": "Tâches",
    "Projects": "Projets",
    "Reports": "Rapports",
    "Analytics": "Analytique",
    "Documents": "Documents",
    "Files": "Fichiers",
    "Users": "Utilisateurs",
    "Roles": "Rôles",
    "Permissions": "Permissions",
    "Teams": "Équipes",
    "Departments": "Départements",
    "Inventory": "Inventaire",
    "Stock": "Stock",
    "Products": "Produits",
    "Services": "Services",
    "Orders": "Commandes",
    "Invoices": "Factures",
    "Quotes": "Devis",
    "Customers": "Clients",
    "Suppliers": "Fournisseurs",
    "Vendors": "Vendeurs",
    "Leads": "Pistes",
    "Opportunities": "Opportunités",
    "Sales": "Ventes",
    "Marketing": "Marketing",
    "Finance": "Finance",
    "Accounting": "Comptabilité",
    "HR": "RH",
    "Human Resources": "Ressources Humaines",
    "Production": "Production",
    "Manufacturing": "Fabrication",
    "Quality": "Qualité",
    "Maintenance": "Maintenance",
    "Logistics": "Logistique",
    "Support": "Support",
    "Help": "Aide",
    "FAQ": "FAQ",
    "About": "À propos",
    "Contact": "Contact",
    "Privacy": "Confidentialité",
    "Terms": "Conditions",
    "Menu": "Menu",
    "Pipeline": "Pipeline",
    "Obeya": "Obeya",
    "Andon": "Andon",
    "Exceptions": "Exceptions",
    "Work Orders": "Ordres de travail",

    # Common Fields & Nouns
    "Name": "Nom",
    "First Name": "Prénom",
    "Last Name": "Nom de famille",
    "Title": "Titre",
    "Description": "Description",
    "Type": "Type",
    "Category": "Catégorie",
    "Status": "Statut",
    "Date": "Date",
    "Time": "Heure",
    "Duration": "Durée",
    "Start Date": "Date de début",
    "End Date": "Date de fin",
    "Created At": "Créé le",
    "Updated At": "Mis à jour le",
    "User": "Utilisateur",
    "Email": "Email",
    "Phone": "Téléphone",
    "Address": "Adresse",
    "City": "Ville",
    "State": "État",
    "Country": "Pays",
    "Zip Code": "Code postal",
    "Postal Code": "Code postal",
    "Currency": "Devise",
    "Language": "Langue",
    "Timezone": "Fuseau horaire",
    "Theme": "Thème",
    "Password": "Mot de passe",
    "New Password": "Nouveau mot de passe",
    "Confirm Password": "Confirmer le mot de passe",
    "ID": "ID",
    "Code": "Code",
    "Reference": "Référence",
    "Price": "Prix",
    "Cost": "Coût",
    "Quantity": "Quantité",
    "Total": "Total",
    "Subtotal": "Sous-total",
    "Tax": "Taxe",
    "Discount": "Remise",
    "Amount": "Montant",
    "Value": "Valeur",
    "Balance": "Solde",
    "Credit": "Crédit",
    "Debit": "Débit",
    "Source": "Source",
    "Target": "Cible",
    "Destination": "Destination",
    "Origin": "Origine",
    "Priority": "Priorité",
    "Severity": "Sévérité",
    "Label": "Étiquette",
    "Tag": "Tag",
    "Notes": "Notes",
    "Comment": "Commentaire",
    "Message": "Message",
    "Subject": "Sujet",
    "Body": "Corps",
    "Attachment": "Pièce jointe",
    "Image": "Image",
    "Avatar": "Avatar",
    "Logo": "Logo",
    "Color": "Couleur",
    "Size": "Taille",
    "Weight": "Poids",
    "Dimensions": "Dimensions",
    "Width": "Largeur",
    "Height": "Hauteur",
    "Length": "Longueur",
    "Volume": "Volume",
    "Area": "Surface",
    "Speed": "Vitesse",
    "Distance": "Distance",
    "Location": "Emplacement",
    "Warehouse": "Entrepôt",
    "Bin": "Casier",
    "Shelf": "Étagère",
    "Row": "Rangée",
    "Column": "Colonne",
    "Section": "Section",
    "Zone": "Zone",
    "Method": "Méthode",
    "Protocol": "Protocole",
    "Version": "Version",
    "Reviewer": "Relecteur",
    "Assignee": "Assigné à",
    "Owner": "Propriétaire",
    "Creator": "Créateur",
    "Manager": "Manager",
    "Employee": "Employé",
    "Role": "Rôle",
    "Admin": "Admin",
    "Administrator": "Administrateur",
    "Guest": "Invité",
    "Member": "Membre",
    "Partner": "Partenaire",
    "Client": "Client",
    "Prospect": "Prospect",
    "Supplier": "Fournisseur",
    "Vendor": "Vendeur",
    "Manufacturer": "Fabricant",
    "Distributor": "Distributeur",
    "Retailer": "Détaillant",
    "Wholesaler": "Grossiste",
    "Competitor": "Concurrent",
    "Market": "Marché",
    "Industry": "Industrie",
    "Sector": "Secteur",
    "Revenue": "Revenu",
    "Profit": "Profit",
    "Margin": "Marge",
    "Budget": "Budget",
    "Forecast": "Prévision",
    "Goal": "Objectif",
    "Objective": "Objectif",
    "Target": "Cible",
    "Strategy": "Stratégie",
    "Plan": "Plan",
    "Tactic": "Tactique",
    "Action": "Action",
    "Result": "Résultat",
    "Outcome": "Résultat",
    "Impact": "Impact",
    "Benefit": "Bénéfice",
    "Risk": "Risque",
    "Issue": "Problème",
    "Problem": "Problème",
    "Solution": "Solution",
    "Fix": "Correctif",
    "Workaround": "Contournement",
    "Bug": "Bug",
    "Defect": "Défaut",
    "Feature": "Fonctionnalité",
    "Requirement": "Exigence",
    "Specification": "Spécification",
    "Design": "Design",
    "Architecture": "Architecture",
    "Infrastructure": "Infrastructure",
    "System": "Système",
    "Application": "Application",
    "Software": "Logiciel",
    "Hardware": "Matériel",
    "Network": "Réseau",
    "Database": "Base de données",
    "Server": "Serveur",
    "Client": "Client",
    "Browser": "Navigateur",
    "Device": "Appareil",
    "Mobile": "Mobile",
    "Desktop": "Bureau",
    "Tablet": "Tablette",
    "Web": "Web",
    "Cloud": "Cloud",
    "API": "API",
    "SDK": "SDK",
    "Library": "Bibliothèque",
    "Framework": "Framework",
    "Platform": "Plateforme",
    "Tool": "Outil",
    "Utility": "Utilitaire",
    "Service": "Service",
    "Process": "Processus",
    "Workflow": "Flux de travail",
    "Job": "Tâche",
    "Task": "Tâche",
    "Event": "Événement",
    "Trigger": "Déclencheur",
    "Condition": "Condition",
    "Action": "Action",
    "Operation": "Opération",
    "Function": "Fonction",
    "Method": "Méthode",
    "Variable": "Variable",
    "Constant": "Constante",
    "Parameter": "Paramètre",
    "Argument": "Argument",
    "Input": "Entrée",
    "Output": "Sortie",
    "Data": "Données",
    "Information": "Information",
    "Knowledge": "Connaissance",
    "Intelligence": "Intelligence",
    "Insight": "Aperçu",
    "Analysis": "Analyse",
    "Prediction": "Prédiction",
    "Recommendation": "Recommandation",
    "Suggestion": "Suggestion",
    "Feedback": "Retour",
    "Review": "Revue",
    "Rating": "Note",
    "Score": "Score",
    "Rank": "Rang",
    "Level": "Niveau",
    "Tier": "Niveau",
    "Grade": "Note",
    "Class": "Classe",
    "Category": "Catégorie",
    "Group": "Groupe",
    "Set": "Ensemble",
    "List": "Liste",
    "Collection": "Collection",
    "Array": "Tableau",
    "Dictionary": "Dictionnaire",
    "Map": "Carte",
    "Tree": "Arbre",
    "Graph": "Graphe",
    "Node": "Nœud",
    "Edge": "Arête",
    "Vertex": "Sommet",
    "Parent": "Parent",
    "Child": "Enfant",
    "Sibling": "Frère/Sœur",
    "Ancestor": "Ancêtre",
    "Descendant": "Descendant",
    "Root": "Racine",
    "Leaf": "Feuille",
    "Branch": "Branche",
    "Trunk": "Tronc",
    "Stem": "Tige",
    "Seed": "Graine",
    "Fruit": "Fruit",
    "Flower": "Fleur",
    
    # Specific System/Layout Terms
    "SYSTEM_INITIALIZATION...": "INITIALISATION_SYSTEME...",
    "PROTOCOL: SENSEI_OS_V3 // BOOT_SEQUENCE": "PROTOCOLE : SENSEI_OS_V3 // SEQUENCE_DEMARRAGE",
    "STATION: {station}": "POSTE : {station}",
    "OS_VER: {version}": "VER_OS : {version}",
    "INTEGRITY: {state}": "INTEGRITE : {state}",
    "LATENCY: {latency}": "LATENCE : {latency}",
    "Something went wrong. Please refresh or try again.": "Une erreur est survenue. Veuillez actualiser ou réessayer.",
    "Settings Synchronized": "Paramètres synchronisés",
    "Target {title} parameters updated in registry.": "Paramètres cibles {title} mis à jour dans le registre.",
    "SYNCHRONIZING...": "SYNCHRONISATION...",
    "SAVE_CONFIGURATION": "ENREGISTRER_CONFIGURATION",
    "SMTP_RELAY: SYNCHRONIZED": "RELAIS_SMTP : SYNCHRONISE",
    "Host: mail.sensei-infra.com // Port: 587 (TLS)": "Hôte : mail.sensei-infra.com // Port : 587 (TLS)",
    "Live operational stream synchronized": "Flux opérationnel en direct synchronisé",
    "Intelligence Module 04": "Module Intelligence 04",
    "(GMT+0) Casablanca": "(GMT+0) Casablanca",
    "(GMT+1) Paris": "(GMT+1) Paris",
    "(GMT-5) New York": "(GMT-5) New York",
    "(GMT-8) Los Angeles": "(GMT-8) Los Angeles",
    "Sensei Manufacturing Solutions": "Sensei Manufacturing Solutions",
    "MA-123456789": "MA-123456789",
    "no-reply@sensei-manuf.com": "no-reply@sensei-manuf.com",
    
    # Missing common keys from missing_fr_strict.json
    "X-Ray": "Rayons X",
    "Variance": "Variance",
    "SLA: {date}": "SLA : {date}",
    "Received": "Reçu",
    "Private": "Privé",
    "Public": "Public",
    "Expert": "Expert",
    "Introduction": "Introduction",
    "Urgent": "Urgent",
    "Suggestions ({count})": "Suggestions ({count})",
    "Insight": "Aperçu",
    "Action": "Action",
    "14px base": "Base 14px",
    "18px base": "Base 18px",
    "Compact": "Compact",
    "Permissions": "Permissions",
    "Webhooks": "Webhooks",
    "minute": "minute",
    "Page": "Page",
    "Quota": "Quota",
    "Documentation": "Documentation",
    "Aggregation Pulse": "Pulsation d'agrégation",
    "Escalate Anomaly": "Escalader l'anomalie",
    "Execution Velocity": "Vélocité d'exécution",
    "Export Spec": "Spec d'export",
    "Gate Verified": "Porte vérifiée",
    "Initiate Execution": "Initier l'exécution",
    "Scrap Deviation": "Déviation rebut",
    "Suspend Protocol": "Suspendre le protocole",
    "History": "Historique",
    "Operations": "Opérations",
    "Target Magnitude": "Magnitude cible",
    "Unknown Product": "Produit inconnu",
    "View History": "Voir l'historique",
    "Retrieving Bill of Materials protocol nodes...": "Récupération des nœuds du protocole de nomenclature...",
    "Temporal Schedule": "Calendrier temporel"
}

def load_json(filepath):
    if not os.path.exists(filepath):
        print(f"File not found: {filepath}")
        return None
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(filepath, data):
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved {filepath}")

def apply_translations(data, context="root"):
    updated_count = 0
    
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, str):
                # Check for direct match
                if value in TRANSLATIONS:
                    # Check if actually saving a change
                    if value != TRANSLATIONS[value]:
                        data[key] = TRANSLATIONS[value]
                        # prevent spamming output
                        # print(f"Updated {context}.{key}: '{value}' -> '{TRANSLATIONS[value]}'")
                        updated_count += 1
                # Check for case-insensitive match if exact match fail? 
                # Be careful with case-insensitive for things like "Sales" vs "sales"
                elif value.strip() in TRANSLATIONS:
                     cleaned = value.strip()
                     if value != TRANSLATIONS[cleaned]:
                        data[key] = TRANSLATIONS[cleaned]
                        updated_count += 1
            elif isinstance(value, (dict, list)):
                updated_count += apply_translations(value, f"{context}.{key}")
                
    elif isinstance(data, list):
        for i, item in enumerate(data):
            updated_count += apply_translations(item, f"{context}[{i}]")
            
    return updated_count

def main():
    print(f"Loading {FR_FILE_PATH}...")
    fr_data = load_json(FR_FILE_PATH)
    
    if not fr_data:
        return

    print("Applying translations...")
    count = apply_translations(fr_data)
    
    print(f"Total keys updated: {count}")
    
    save_json(FR_FILE_PATH, fr_data)
    print("Cleanup complete.")

if __name__ == "__main__":
    main()
