
import json
import os

def set_nested_value(d, path, value):
    keys = path.split('.')
    current = d
    for i, k in enumerate(keys[:-1]):
        if k not in current:
             current[k] = {}
             current = current[k]
        else:
            current = current[k]
            if not isinstance(current, dict):
                # If we encounter a non-dict where we expect a dict (e.g. key conflict), 
                # we might have to overwrite or stop. simpler to overwrite or ignore.
                # Here we will try to preserve structure if possible but for a cleanup script usually overwrite is what we want if structure is broken.
                # But let's be careful.
                pass
    
    last_key = keys[-1]
    current[last_key] = value
    return True

def main():
    missing_file = 'scripts/missing_fr_strict.json'
    target_file = 'frontend/src/locales/fr.json'
    
    if not os.path.exists(missing_file):
        print(f"Error: {missing_file} not found.")
        return

    # Load keys to fix
    with open(missing_file, 'r', encoding='utf-8') as f:
        missing_data = json.load(f)
        
    # Translations map
    translations = {
        # Common
        "common.source": "Source",
        "common.date": "Date",
        "common.description": "Description",
        "common.type": "Type",
        "common.total": "Total",
        "common.expert": "Expert",
        "common.version": "Version",
        "common.public": "Public",
        
        # Navigation
        "navigation.pipeline": "Pipeline",
        "navigation.production": "Production",
        "navigation.obeya": "Obeya",
        "navigation.exceptions": "Exceptions",
        "navigation.andon": "Andon",
        "navigation.maintenance": "Maintenance",
        "navigation.finance": "Finance",
        "navigation.notifications": "Notifications",
        "navigation.menu": "Menu",
        
        # Email Drafting
        "emailDrafting.purpose.introduction": "Introduction",
        "emailDrafting.tone.urgent": "Urgent",
        "emailDrafting.suggestions.title": "Suggestions ({count})",
        "emailDrafting.defaults.companyName": "Sensei",
        
        # Settings
        "settings.profile.avatar": "Avatar",
        "settings.profile.timezones.africaCasablanca": "(GMT+0) Casablanca",
        "settings.profile.timezones.europeParis": "(GMT+1) Paris",
        "settings.profile.timezones.americaNewYork": "(GMT-5) New York",
        "settings.profile.timezones.americaLosAngeles": "(GMT-8) Los Angeles",
        "settings.profile.departments.production": "Production",
        "settings.profile.departments.finance": "Finance",
        "settings.notifications.title": "Notifications",
        "settings.roleInsights.audit.headers.action": "Action",
        "settings.roleInsights.roles.finance.name": "Finance",
        "settings.roleInsights.roles.maintenance.name": "Maintenance",
        "settings.appearance.compact": "Compact",
        "settings.team.roles.admin": "Admin",
        "settings.team.roles.manager": "Manager",
        "settings.team.departments.production": "Production",
        "settings.permissions": "Permissions",
        "settings.webhooks": "Webhooks",
        "settings.company.defaults.legalEntityIdentity": "Sensei Manufacturing Solutions",
        "settings.company.defaults.taxIdVat": "MA-123456789",
        "settings.email.defaults.relayReplyTo": "no-reply@sensei-manuf.com",
        
        # Time & Tables
        "time.minute": "minute",
        "tables.page": "Page",
        "notifications.title": "Notifications",
        
        # Modules
        "modules.sales.pipeline": "Pipeline",
        "modules.sales.quota": "Quota",
        "modules.production.title": "Production",
        "modules.production.detail.documentation": "Documentation",
        "modules.production.detail.station": "Station",
        "modules.quality.inspections": "Inspections",
        "modules.quality.ncr.detail.tabs.disposition": "Disposition",
        "modules.quality.certifications": "Certifications",
        "modules.quality.audit": "Audit",
        "modules.inventory.stock": "Stock",
        "modules.maintenance.title": "Maintenance",
        "modules.maintenance.mttr": "MTTR",
        "modules.maintenance.mtbf": "MTBF",
        "modules.hr.performance": "Performance",
        "modules.finance.title": "Finance",
        "modules.finance.budgets": "Budgets",
        "modules.products.new.placeholders.unitCost": "0,00",
        
        # Pages
        "pages.analytics.mlInsights.impact": "Impact",
        "pages.analytics.models.intelligence": "Intelligence",
        "pages.analytics.statusOptimal": "OPTIMAL",
        "pages.auditor.tabs.audits": "Audits",
        "pages.auditor.optimal": "Optimal",
        "pages.executive.tabs.finance": "Finance",
        "pages.executive.tabs.sqdcp": "SQDCP",
        "pages.executive.tabs.senseiAi": "SENSEI_AI",
        "pages.executive.station": "Station",
        "pages.finance.tabs.budgets": "Budgets",
        "pages.finance.ledger.code": "Code",
        "pages.finance.ledger.type": "Type",
        "pages.finance.tax.code": "Code",
        "pages.finance.tax.type": "Type",
        "pages.finance.kpi.alpha": "Alpha",
        "pages.finance.kpi.delta": "Delta",
        "pages.finance.kpi.opex": "Opex",
        "pages.finance.station": "Station",
        "pages.hr.sections.performance": "Performance",
        "pages.hr.tabs.performance": "Performance",
        "pages.hr.placeholders.portfolioUrl": "https://...",
        "pages.it.sections.infrastructure": "Infrastructure",
        "pages.it.sections.tickets": "Tickets",
        "pages.it.tabs.incidents": "Incidents",
        "pages.today.severity.info": "Info",
        "pages.today.handover.station": "Station {id}",
        "pages.today.handover.note": "Note",
        "pages.today.handover.notes": "Notes",
        "pages.tasks.status.backlog": "Backlog",
        "pages.pipeline.views.kanban": "Kanban",
        "pages.pipeline.new.labels.detailedContext": "Description",
        "pages.pipeline.new.labels.specification": "Description",
        "pages.pipeline.new.labels.protocolNotes": "Notes",
        "pages.pipeline.new.priority.urgent": "Urgent",
        "pages.customers.status.prospect": "Prospect",
        "pages.customers.detail.contacts": "Contacts",
        "pages.customers.detail.notes": "Notes",
        "pages.customers.filters.prospect": "Prospect",
        "pages.customers.new.contact": "Contact",
        "pages.customers.new.contacts": "Contacts",
        "pages.quotes.detail.table.description": "Description",
        "pages.quotes.detail.total": "Total",
        "pages.quotes.new.total": "Total",
        "pages.quotes.table.version": "Version",
        "pages.sales.totalRfqs": "Total des RFQ",
        "pages.production.views.kanban": "Kanban",
        "pages.production.views.gantt": "Gantt",
        "pages.quality.tabs.inspections": "Inspections",
        "pages.quality.tabs.capas": "CAPAs",
        "pages.quality.status.disposition": "Disposition",
        "pages.quality.status.capa": "CAPA",
        "pages.quality.table.inspection": "Inspection",
        "pages.quality.msa.notes": "Notes",
        "pages.quality.capability.notes": "Notes",
        "pages.maintenance.tabs.budget": "Budget",
        "pages.maintenance.tabs.loto": "Loto",
        "pages.maintenance.table.budget": "Budget",
        "pages.training.tabs.certifications": "Certifications",
        "pages.training.certifications.title": "Certifications",
        "pages.training.programs.table.dates": "Dates",
        "pages.training.records.table.score": "Score",
        "pages.supplyChain.scenarios.probability": "Prob",
        "pages.settings.links.notifications": "Notifications",
        "pages.settings.profile.sections.avatar": "Avatar",
        "pages.obeya.tabs.actions": "Actions",
        "pages.obeya.tabs.exceptions": "Exceptions",
        "pages.obeya.sections.hoshinKanri": "Hoshin Kanri",
        "pages.projectManagement.detail.backlog": "Backlog",
        "pages.projectManagement.detail.sprints": "Sprints",
        "pages.projectManagement.detail.wiki": "Wiki",
        "pages.projectManagement.types.standard": "Standard",
        "pages.projectManagement.types.scrum": "Scrum",
        "pages.projectManagement.types.kanban": "Kanban",
        "pages.projectManagement.types.kaizen": "Kaizen",
        "pages.projectManagement.types.maintenance": "Maintenance",
        "pages.admin.title": "Administration",
        "pages.obeyaNew.description": "Description",
        
        # A3
        "a3.new.basicInformation.description": "Description",
        "a3.sections.background.description": "Description",
        "a3.sections.countermeasures.description": "Description",
        "a3.sections.currentCondition.description": "Description",
        "a3.sections.goal.description": "Description",
        "a3.sections.implementation.description": "Description",
        "a3.sections.rootCause.description": "Description",
        "a3.stats.emailDrafting.aria.toneGroup": "Sélectionner le ton",
        "a3.stats.emailDrafting.aria.selectLanguage": "Sélectionner la langue",
        "a3.stats.emailDrafting.aria.recipientEmail": "Email du destinataire",
        "a3.stats.emailDrafting.aria.recipientName": "Nom du destinataire",
        "a3.stats.emailDrafting.aria.addKeyPoint": "Ajouter un point clé",
        "a3.stats.emailDrafting.aria.keyPointsList": "Liste des points clés",
        "a3.stats.emailDrafting.aria.removeKeyPoint": "Supprimer : {point}",
        "a3.stats.emailDrafting.aria.copyToClipboard": "Copier dans le presse-papiers",
        "a3.stats.emailDrafting.aria.editSubject": "Modifier l'objet",
        "a3.stats.emailDrafting.aria.close": "Fermer",
        "a3.stats.emailDrafting.aria.draftsList": "Brouillons d'emails",
        "a3.stats.emailDrafting.placeholders.selectPurpose": "Sélectionner l'objectif...",
        "a3.stats.emailDrafting.placeholders.recipientEmail": "destinataire@exemple.com",
        "a3.stats.emailDrafting.placeholders.recipientNameOptional": "Nom (facultatif)",
        "a3.stats.emailDrafting.placeholders.keyPoint": "Ajouter un point clé",
        "a3.stats.emailDrafting.placeholders.senderName": "ex : Alex Morgan",
        "a3.stats.emailDrafting.placeholders.senderEmail": "ex : alex@sensei.com",
        "a3.stats.emailDrafting.placeholders.senderTitle": "ex : Responsable de Compte",
        "a3.stats.emailDrafting.placeholders.companyName": "ex : Sensei SAS",
        "a3.stats.emailDrafting.placeholders.threadEntityType": "Sélectionner l'entité du fil...",
        "a3.stats.emailDrafting.placeholders.threadEntityId": "Saisir l'ID de l'entité...",
        "a3.stats.emailDrafting.placeholders.referenceNumber": "ex : RFQ-2024-001",
        "a3.stats.emailDrafting.placeholders.subjectHint": "ex : Mise à jour des prix pour T2",
        "a3.stats.emailDrafting.purpose.missingInfoRequest": "Demande d'informations manquantes",
        "a3.stats.emailDrafting.purpose.quoteFollowup": "Suivi de devis",
        "a3.stats.emailDrafting.purpose.quoteSubmission": "Soumission de devis",
        "a3.stats.emailDrafting.purpose.supplierInquiry": "Demande fournisseur",
        "a3.stats.emailDrafting.purpose.meetingRequest": "Demande de réunion",
        "a3.stats.emailDrafting.purpose.meetingConfirmation": "Confirmation de réunion",
        "a3.stats.emailDrafting.purpose.meetingReschedule": "Reprogrammation de réunion",
        "a3.stats.emailDrafting.purpose.issueNotification": "Notification de problème",
        "a3.stats.emailDrafting.purpose.statusUpdate": "Mise à jour du statut",
        "a3.stats.emailDrafting.purpose.thankYou": "Merci",
        "a3.stats.emailDrafting.purpose.introduction": "Introduction",
        "a3.stats.emailDrafting.purpose.escalation": "Escalade",
        "a3.stats.emailDrafting.purpose.apology": "Excuses",
        "a3.stats.emailDrafting.purpose.custom": "Email personnalisé",
        "a3.stats.emailDrafting.tone.formal": "Formel",
        "a3.stats.emailDrafting.tone.professional": "Professionnel",
        "a3.stats.emailDrafting.tone.friendly": "Amical",
        "a3.stats.emailDrafting.tone.urgent": "Urgent",
        "a3.stats.emailDrafting.tone.apologetic": "D'excuse",
        "a3.stats.emailDrafting.tone.appreciative": "Appréciatif",
        "a3.stats.emailDrafting.tone.concise": "Concis",
        "a3.stats.emailDrafting.language.english": "Anglais",
        "a3.stats.emailDrafting.language.french": "Français",
        "a3.stats.emailDrafting.language.german": "Allemand",
        "a3.stats.emailDrafting.language.spanish": "Espagnol",
        "a3.stats.emailDrafting.language.italian": "Italien",
        "a3.stats.emailDrafting.language.portuguese": "Portugais",
        "a3.stats.emailDrafting.language.japanese": "Japonais",
        "a3.stats.emailDrafting.language.chinese": "Chinois",
        "a3.stats.emailDrafting.language.korean": "Coréen",
        "a3.stats.emailDrafting.language.arabic": "Arabe",
        "a3.stats.emailDrafting.actions.add": "Ajouter",
        "a3.stats.emailDrafting.actions.apply": "Appliquer",
        "a3.stats.emailDrafting.actions.edit": "Modifier",
        "a3.stats.emailDrafting.actions.generating": "En cours de génération...",
        "a3.stats.emailDrafting.actions.generateDraft": "Générer un brouillon",
        "a3.stats.emailDrafting.actions.regenerate": "Regénérer",
        "a3.stats.emailDrafting.actions.send": "Envoyer",
        "a3.stats.emailDrafting.preview.title": "Aperçu du brouillon",
        "a3.stats.emailDrafting.preview.subjectLabel": "Objet",
        "a3.stats.emailDrafting.preview.confidence": "Confiance : {score}",
        "a3.stats.emailDrafting.preview.generatedIn": "Généré en {time}",
        "a3.stats.emailDrafting.compliance.none": "Aucun problème de conformité détecté",
        "a3.stats.emailDrafting.compliance.title": "Problèmes de conformité ({count})",
        "a3.stats.emailDrafting.suggestions.title": "Suggestions ({count})",
        "a3.stats.emailDrafting.alternatives.title": "Objets alternatifs :",
        "a3.stats.emailDrafting.thread.entityType.rfq": "Demande de prix (RFQ)",
        "a3.stats.emailDrafting.thread.entityType.quote": "Devis",
        "a3.stats.emailDrafting.thread.entityType.workOrder": "Ordre de travail",
        "a3.stats.emailDrafting.thread.entityType.opportunity": "Opportunité",
        "a3.stats.emailDrafting.thread.entityType.nonConformance": "Non-conformité",
        "a3.stats.emailDrafting.thread.entityType.shipment": "Expédition",
        "a3.stats.emailDrafting.thread.entityType.invoice": "Facture",
        "a3.stats.emailDrafting.thread.loadFailed": "Échec du chargement de l'historique du fil",
        "a3.stats.emailDrafting.thread.helper": "Connectez ce brouillon à un fil pour conserver le fil de données.",
        "a3.stats.emailDrafting.thread.loading": "Chargement de l'historique du fil...",
        "a3.stats.emailDrafting.thread.traceTitle": "Historique du fil",
        "a3.stats.emailDrafting.thread.traceStats": "Historique : {nodes} nœuds / {edges} arêtes",
        "a3.stats.emailDrafting.thread.reasoningId": "ID de raisonnement : {id}",
        "a3.stats.emailDrafting.defaults.senderName": "Opérateur Sensei",
        "a3.stats.emailDrafting.defaults.senderEmail": "operateur@sensei.com",
        "a3.stats.emailDrafting.defaults.companyName": "Sensei",
        "a3.stats.emailDrafting.sections.recipient": "Destinataire",
        "a3.stats.emailDrafting.sections.purpose": "Objectif",
        "a3.stats.emailDrafting.sections.sender": "Expéditeur",
        "a3.stats.emailDrafting.sections.threadContext": "Contexte du fil",
        "a3.stats.emailDrafting.sections.language": "Langue",
        "a3.stats.emailDrafting.sections.keyPoints": "Points clés",
        "a3.stats.emailDrafting.fields.senderName": "Nom de l'expéditeur",
        "a3.stats.emailDrafting.fields.senderEmail": "Email de l'expéditeur",
        "a3.stats.emailDrafting.fields.senderTitle": "Titre de l'expéditeur",
        "a3.stats.emailDrafting.fields.companyName": "Nom de l'entreprise",
        "a3.stats.emailDrafting.fields.threadEntityType": "Type d'entité du fil",
        "a3.stats.emailDrafting.fields.threadEntityId": "ID d'entité du fil",
        "a3.stats.emailDrafting.fields.referenceNumberOptional": "Numéro de référence (facultatif)",
        "a3.stats.emailDrafting.fields.subjectHintOptional": "Indice d'objet (facultatif)",
        "a3.stats.emailDrafting.status.generating": "En cours de génération...",
        "a3.stats.emailDrafting.status.ready": "Prêt pour examen",
        "a3.stats.emailDrafting.status.reviewed": "Examiné",
        "a3.stats.emailDrafting.status.approved": "Approuvé",
        "a3.stats.emailDrafting.status.sent": "Envoyé",
        "a3.stats.emailDrafting.status.discarded": "Rejeté",
        "a3.stats.emailDrafting.status.failed": "Échec",
        "a3.stats.emailDrafting.notifications.copied": "Copié dans le presse-papiers !",
        "a3.stats.emailDrafting.empty.title": "Pas encore de brouillon",
        "a3.stats.emailDrafting.empty.description": "Créez un brouillon pour voir l'aperçu et les vérifications de conformité.",
        "a3.stats.emailDrafting.empty.list": "Pas encore de brouillons",
        "a3.stats.emailDrafting.validation.emailRequired": "L'email est obligatoire",
        "a3.stats.emailDrafting.validation.emailInvalid": "Format d'email invalide",
        "a3.table.biometricSync": "Synchronisation biométrique",
        "a3.table.biometricSyncDesc": "Utiliser Face ID ou le chiffrement par empreinte digitale pour déverrouiller",
        "a3.table.description": "Gérer la synchronisation mobile et les niveaux d'autorisation biométrique",
        "a3.table.offlineIntelligence": "Intelligence hors ligne",
        "a3.table.offlineIntelligenceDesc": "Modèles prédictifs embarqués pour les environnements à faible latence",
        "a3.table.telemetryPush": "Signaux push de télémétrie",
        "a3.table.telemetryPushDesc": "Recevoir des alertes organisationnelles en temps réel",
        "a3.table.title": "Nœud opérationnel mobile",
        
        # Production
        "production.title": "Production",
        "production.workOrders.addWorkOrder": "Créer un ordre de travail",
        "production.workOrders.woNumber": "N° OT",
        "production.workOrders.product": "Produit",
        "production.workOrders.planned": "Prévu",
        "production.workOrders.released": "Lancé",
        "production.workOrders.dueDate": "Date d'échéance",
        "production.scheduling.title": "Planification",
        "production.scheduling.gantt": "Diagramme de Gantt",
        "production.tabs.scheduling": "Planification",
        
        # Quality
        "quality.inspections.title": "Inspections",
        "quality.inspections.addInspection": "Nouvelle inspection",
        "quality.inspections.workOrder": "Ordre de travail",
        "quality.inspections.product": "Produit",
        "quality.inspections.type": "Type",
        "quality.inspections.date": "Date d'inspection",
        "quality.inspections.passed": "Accepté",
        "quality.inspections.quantityInspected": "Qté inspectée",
        "quality.inspections.quantityPassed": "Qté acceptée",
        "quality.inspections.quantityFailed": "Qté rejetée",
        "quality.inspections.searchPlaceholder": "Rechercher des inspections...",
        "quality.ncrs.title": "Rapports de non-conformité",
        "quality.ncrs.addNCR": "Créer une RNC",
        "quality.ncrs.critical": "Critique",
        "quality.ncrs.major": "Majeur",
        "quality.ncrs.minor": "Mineur",
        "quality.ncrs.rootCause": "Cause racine",
        "quality.ncrs.containmentAction": "Action de confinement",
        "quality.capas.title": "CAPA",
        "quality.capas.addCAPA": "Créer une CAPA",
        "quality.capas.correctiveAction": "Action corrective",
        "quality.capas.preventiveAction": "Action préventive",
        "quality.capas.effectiveness": "Efficacité",
        "quality.msa.title": "Études MSA",
        "quality.msa.gageRR": "Gage R&R",
        "quality.msa.compute": "Calculer GRR",
        "quality.msa.repeatability": "Répétabilité",
        "quality.msa.reproducibility": "Reproductibilité",
        "quality.capability.title": "Capacité du processus",
        "quality.capability.compute": "Calculer Cp/Cpk",
        "quality.tabs.inspections": "Inspections",
        "quality.tabs.ncrs": "RNC",
        "quality.tabs.capas": "CAPA",
        "quality.tabs.capability": "Capacité",
        "quality.tabs.complaints": "Plaintes",
        "quality.tabs.surveys": "Enquêtes",
        "quality.tabs.selfInspection": "Auto-inspection",
        "quality.tabs.labTesting": "Tests en laboratoire",
        "quality.tabs.aql": "Échantillonnage AQL",
        "quality.tabs.traceability": "Traçabilité",
        "quality.tabs.changePoint": "Point de changement",
        "quality.grr.analysisResults": "Résultats de l'analyse GRR",
        "quality.grr.gauge": "Jauge : {name}",
        "quality.grr.totalGageRR": "Total Gage R&R",
        "quality.grr.excellent": "Excellent",
        "quality.grr.acceptable": "Acceptable",
        "quality.grr.unacceptable": "Inacceptable",
        "quality.grr.msgExcellent": "Le système de mesure est acceptable",
        "quality.grr.msgAcceptable": "Peut être acceptable selon l'importance de l'application",
        "quality.grr.msgUnacceptable": "Le système de mesure doit être amélioré",
        "quality.grr.variationBreakdown": "Répartition de la variation",
        "quality.grr.variationTooltip": "Montre la contribution de chaque source à la variation totale. Un GRR (EV+AV) plus faible signifie un meilleur système de mesure.",
        "quality.grr.equipmentVariation": "Variation de l'équipement (EV) : {value}%",
        "quality.grr.repeatability": "Répétabilité",
        "quality.grr.appraiserVariation": "Variation de l'opérateur (AV) : {value}%",
        "quality.grr.reproducibility": "Reproductibilité",
        "quality.grr.partVariationPct": "Variation des pièces (PV) : {value}%",
        "quality.grr.actualPartVariation": "Variation réelle pièce à pièce",
        "quality.grr.legendEV": "EV (Répétabilité)",
        "quality.grr.legendAV": "AV (Reproductibilité)",
        "quality.grr.legendPV": "PV (Variation des pièces)",
        "quality.grr.repeatabilityEV": "Répétabilité (EV)",
        "quality.grr.reproducibilityAV": "Reproductibilité (AV)",
        "quality.grr.partVariation": "Variation des pièces (PV)",
        "quality.grr.totalVariation": "Variation totale (TV)",
        "quality.grr.ndcTitle": "Nombre de catégories distinctes (NDC)",
        "quality.grr.ndcAcceptable": "≥ 5 (Acceptable)",
        "quality.grr.ndcNeedsImprovement": "< 5 (Nécessite une amélioration)",
        "quality.grr.ndcDescription": "Le NDC représente le nombre de catégories de pièces distinctes que le système de mesure peut distinguer de manière fiable.",
        "quality.grr.aiagGuidelines": "Directives AIAG MSA :",
        "quality.grr.aiagExcellent": "< 10% GRR : Le système de mesure est acceptable",
        "quality.grr.aiagAcceptable": "10-30% GRR : Peut être acceptable selon l'importance de l'application",
        "quality.grr.aiagUnacceptable": "> 30% GRR : Le système de mesure doit être amélioré",
        
        # Training
        "training.title": "Formation",
        "training.certifications.title": "Certifications",
        "training.certifications.name": "Nom de la certification",
        "training.certifications.enrolled": "Inscrit",
        "training.certifications.expired": "Expiré",
        "training.certifications.expiryDate": "Date d'expiration",
        "training.programs.title": "Programmes de formation",
        "training.programs.addProgram": "Ajouter un programme",
        "training.programs.name": "Nom du programme",
        "training.programs.participants": "Participants",
        "training.records.title": "Dossiers de formation",
        "training.records.course": "Cours",
        "training.records.completedDate": "Date de fin",
        "training.records.score": "Score",
        "training.tabs.certifications": "Certifications",
        
        # Components
        "components.factoryFloor.machineStatus.productionIssue": "Problème de production",
        "components.factoryFloor.machineStatus.qualityAlert": "Alerte qualité",
        "components.factoryFloor.machineStatus.safetyAlert": "Alerte sécurité",
        "components.factoryFloor.machineStatus.maintenanceRequired": "Maintenance requise",
        "components.factoryFloor.processing": "Traitement en cours...",
        "components.factoryFloor.commandReceived": "Commande reçue",
        "components.factoryFloor.errorOccurred": "Une erreur est survenue",
        "components.factoryFloor.voiceDisabled": "Commandes vocales désactivées",
        "components.errorState.connectionError": "Erreur de connexion",
        "components.errorState.connectionErrorDesc": "Impossible de joindre le serveur. Veuillez vérifier votre connexion.",
        "components.errorState.serverError": "Erreur serveur",
        "components.errorState.serverErrorDesc": "Quelque chose s'est mal passé de notre côté.",
        "components.errorState.noData": "Aucune donnée",
        "components.errorState.noDataDesc": "Aucun enregistrement trouvé.",
        "components.errorState.accessDenied": "Accès refusé",
        "components.errorState.accessDeniedDesc": "Vous n'avez pas la permission d'accéder à cette ressource.",
        "components.errorState.notFound": "Non trouvé",
        "components.errorState.notFoundDesc": "La ressource demandée est introuvable.",
        "components.errorState.errorDesc": "Une erreur inattendue est survenue.",
        "components.errorState.tryAgain": "Réessayer",
        "components.pageGuard.accessRestricted": "Accès restreint",
        "components.pageGuard.noPermission": "Vous n'avez pas la permission d'accéder à cette page.",
        "components.pageGuard.returnToDashboard": "Retour au tableau de bord",
        "components.comingSoon.defaultMessage": "Fonctionnalité en cours de développement, disponible bientôt.",
        "components.comingSoon.goBack": "Retour",
        "components.table.noData": "Aucune donnée",
        "components.table.rowsPerPage": "Lignes par page :",
        "components.commandPalette.noCommandsFound": "Aucune commande trouvée",
        "components.commandPalette.tryDifferentSearch": "Essayez un autre terme de recherche",
        "components.commandPalette.toToggle": "pour basculer",
        "components.scanner.scanComplete": "Scan terminé",
        "components.scanner.cameraNotActive": "Caméra non active",
        "components.scanner.switchCamera": "Changer de caméra",
        "components.scanner.captureFrame": "Capturer l'image",
        "components.scanner.stopScanner": "Arrêter le scanner",
        "components.andon.unknownWorkCenter": "Poste de travail inconnu",
        "components.andon.noActiveAlerts": "Aucune alerte active",
        "components.andon.toggleFullscreen": "Plein écran",
        "components.andon.ackBy": "Ack par {name}",
        "components.andon.triggeredBy": "Déclenché par {name}",
        "components.andon.allSystemsNormal": "Systèmes nominaux",
        "components.kanban.unknownCustomer": "Client inconnu",
        "components.kanban.pipelineValue": "Valeur du pipeline : ",
        "components.kanban.kanbanView": "Vue Kanban",
        "components.kanban.listView": "Vue liste",
        "components.kanban.calendarView": "Vue calendrier",
        "components.quickActions.confirmAction": "Confirmer l'action",
        "components.correction.submissionFailed": "Échec de la correction",
        "components.correction.rejectionFailed": "Échec du rejet",
        "components.sync.removeOperation": "Supprimer l'opération",
        "components.pdfPreview.immutableVersion": "Version immuable",
        "components.pdfPreview.pdfPreview": "Aperçu PDF",
        "components.pdfPreview.versionHistory": "Historique des versions",
        "components.pdfPreview.metadata": "Métadonnées",
        "components.pdfPreview.closeEscape": "Fermer (Échap)",
        "components.pdfPreview.previousPage": "Page précédente",
        "components.pdfPreview.nextPage": "Page suivante",
        "components.pdfPreview.zoomOut": "Zoom arrière",
        "components.pdfPreview.zoomIn": "Zoom avant",
        "components.pdfPreview.rotate": "Faire pivoter",
        "components.pdfPreview.fullscreen": "Plein écran",
        "components.pdfPreview.currentlyViewing": "Visualisation de",
        "components.pdfPreview.loadingPdf": "Chargement du PDF...",
        "components.pdfPreview.documentInfo": "Infos document",
        "components.pdfPreview.createdBy": "Créé par",
        "components.security.noPermission": "Vous n'avez pas la permission de voir ces données",
        "components.security.allActions": "Toutes les actions",
        "components.spatialUi.factoryFloorMap": "Plan de l'usine",
        "components.spatialUi.closePanel": "Fermer le panneau",
        "components.spatialUi.closePathView": "Fermer la vue du chemin",
        "components.spatialUi.zoomOut": "Zoom arrière",
        "components.spatialUi.zoomIn": "Zoom avant",
        "components.spatialUi.resetView": "Réinitialiser la vue",
        "components.spatialUi.selectCellDetails": "Sélectionner une cellule pour les détails",
        "components.spatialUi.currentJob": "Travail actuel :",
        "components.spatialUi.changeStatus": "Changer le statut :",
        "components.spatialUi.orderPath": "Chemin de commande :",
        "components.spatialUi.processTime": "Temps de traitement",
        "components.spatialUi.wasteRatio": "Ratio de gaspillage",
        "components.spatialUi.pathSteps": "Étapes du chemin :",
        "components.spatialUi.warRoom.kpi": "Indicateurs clés de performance",
        "components.spatialUi.warRoom.salesPipeline": "Pipeline des ventes",
        "components.spatialUi.warRoom.productionStatus": "Statut de production",
        "components.spatialUi.warRoom.qualityMetrics": "Métriques de qualité",
        "components.spatialUi.warRoom.activeAlerts": "Alertes actives",
        "components.spatialUi.warRoom.todaysTimeline": "Chronologie du jour",
        "components.session.notifications": "Notifications",
        "components.session.dismissNotification": "Ignorer",
        "components.onboarding.productTour": "Visite du produit",
        "components.onboarding.closeTour": "Fermer la visite",
        "components.onboarding.helpPanel": "Panneau d'aide",
        "components.onboarding.closeHelpPanel": "Fermer",
        "components.onboarding.dismissSuggestion": "Ignorer la suggestion",
        "components.onboarding.toggleAssistant": "Assistant Sensei",
        "components.onboarding.dismiss": "Ignorer",
        "components.onboarding.searchHelp": "Rechercher de l'aide",
        "components.error.somethingWentWrong": "Une erreur est survenue",
        "components.error.dismissError": "Ignorer l'erreur",
        "components.error.dismissBtn": "Ignorer",
        "components.error.readOnlyMode": "Mode lecture seule",
        "components.error.resolveConflicts": "Résoudre les conflits",
        "components.error.yourChanges": "Vos modifications",
        "components.error.serverVersion": "Version du serveur",
        "components.emptyState.noResultsFound": "Aucun résultat trouvé",
        "components.emptyState.noItemsYet": "Aucun élément pour le moment",
        "components.emptyState.noRfqsInQueue": "Aucun RFQ en attente",
        "components.emptyState.noQuotesCreated": "Aucun devis créé",
        "components.emptyState.noActiveJobs": "Aucun travail actif",
        "components.printExport.cancelExport": "Annuler l'exportation",
        "components.printExport.qrCode": "Code QR",
        "components.printExport.dataMatrix": "Data Matrix",
        "components.designSystem.openAuditPanel": "Panneau d'audit Design System",
        "components.designSystem.auditPanelTitle": "Panneau d'audit Design System",
        "components.designSystem.closeAuditPanel": "Fermer le panneau",
        "components.designSystem.horizontalScale": "Échelle horizontale",
        "components.designSystem.verticalScale": "Échelle verticale",
        "components.designSystem.fontSizes": "Tailles de police",
        "components.designSystem.fontWeights": "Poids de police",
        "components.designSystem.designSystemAudit": "Audit du Design System",
        "components.ganttChart.noTasks": "Aucune tâche à visualiser",
        "components.ganttChart.taskName": "Nom de la tâche",
        "components.dataVisualization.noData": "Aucune donnée",
        "components.timeline.noActivity": "Aucune activité",
        "components.virtualTable.noData": "Aucune donnée disponible",
        "components.sidebar.senseiHome": "Accueil Sensei OS",
        "components.sidebar.toggleDarkMode": "Mode sombre",
        "components.sidebar.administration": "Administration",
        "components.mobileNav.navigation": "Navigation mobile",
        "components.mobileNav.openMenu": "Ouvrir le menu",

        # HR
        "hr.employees.title": "Employés",
        "hr.employees.addEmployee": "Ajouter un employé",
        "hr.employees.editEmployee": "Modifier l'employé",
        "hr.employees.email": "Email",
        "hr.employees.department": "Département",
        "hr.employees.position": "Poste",
        "hr.employees.onLeave": "En congé",
        "hr.employees.hireDate": "Date d'embauche",
        "hr.employees.searchPlaceholder": "Rechercher des employés...",
        "hr.employees.noEmployees": "Aucun employé trouvé",
        "hr.employees.createSuccess": "Employé créé avec succès",
        "hr.employees.updateSuccess": "Employé mis à jour avec succès",
        "hr.employees.deleteSuccess": "Employé supprimé avec succès",
        "hr.employees.deleteConfirm": "Supprimer cet employé ?",
        "hr.employees.requiredField": "Ce champ est obligatoire",
        "hr.employees.invalidEmail": "Adresse e-mail valide requise",
        "hr.jobOpenings.title": "Offres d'emploi",
        "hr.jobOpenings.addOpening": "Ajouter une offre",
        "hr.jobOpenings.jobTitle": "Intitulé du poste",
        "hr.jobOpenings.department": "Département",
        "hr.jobOpenings.type": "Type d'emploi",
        "hr.jobOpenings.filled": "Pourvu",
        "hr.jobOpenings.postedDate": "Date de publication",
        "hr.jobOpenings.closingDate": "Date de clôture",
        "hr.jobOpenings.applications": "Candidatures",
        "hr.jobOpenings.noOpenings": "Aucune offre d'emploi",
        "hr.leaveRequests.title": "Demandes de congé",
        "hr.leaveRequests.addRequest": "Nouvelle demande de congé",
        "hr.leaveRequests.leaveType": "Type de congé",
        "hr.leaveRequests.reason": "Motif",
        "hr.leaveRequests.noRequests": "Aucune demande de congé",
        "hr.leaveRequests.approve": "Approuver",
        "hr.leaveRequests.reject": "Rejeter",
        "hr.applicationsPipeline.title": "Pipeline des candidatures",
        "hr.applicationsPipeline.applied": "Candidature reçue",
        "hr.applicationsPipeline.screening": "Sélection",
        "hr.applicationsPipeline.interview": "Entretien",
        "hr.applicationsPipeline.offered": "Offre faite",
        "hr.applicationsPipeline.hired": "Embauché",
        "hr.tabs.employees": "Employés",
        "hr.tabs.jobOpenings": "Offres d'emploi",
        "hr.tabs.leaveRequests": "Demandes de congé",
        "hr.tabs.applicationsPipeline": "Pipeline des candidatures",
        "hr.toasts.employeeCreated": "Employé créé avec succès",
        "hr.toasts.employeeUpdated": "Employé mis à jour",
        "hr.toasts.leaveApproved": "Demande de congé approuvée",
        "hr.toasts.leaveRejected": "Demande de congé rejetée",
        "hr.toasts.openingCreated": "Offre d'emploi créée",

        # Maintenance
        "maintenance.title": "Maintenance",
        "maintenance.assets.title": "Actifs",
        "maintenance.assets.addAsset": "Ajouter un actif",
        "maintenance.assets.name": "Nom de l'actif",
        "maintenance.assets.serialNumber": "Numéro de série",
        "maintenance.assets.operational": "Opérationnel",
        "maintenance.assets.needsRepair": "Nécessite réparation",
        "maintenance.assets.outOfService": "Hors service",
        "maintenance.assets.searchPlaceholder": "Rechercher des actifs...",
        "maintenance.workOrders.addWorkOrder": "Créer un ordre de travail",
        "maintenance.workOrders.dueDate": "Date d'échéance",
        "maintenance.preventiveMaintenance.title": "Maintenance préventive",
        "maintenance.preventiveMaintenance.schedule": "Calendrier",
        "maintenance.preventiveMaintenance.frequency": "Fréquence",
        "maintenance.preventiveMaintenance.lastCompleted": "Dernier achèvement",
        "maintenance.preventiveMaintenance.nextDue": "Prochaine échéance",
        "maintenance.tabs.assets": "Actifs",
        "maintenance.tabs.pmSchedules": "Calendriers MP",
        "maintenance.tabs.tools": "Outils",
        "maintenance.tabs.warranties": "Garanties",
        "maintenance.tabs.loto": "LOTO",
        "maintenance.tabs.fieldReturns": "Retours terrain",
        "maintenance.tabs.budgets": "Budgets",
        
        # Executive
        "executive.title": "Tableau de bord exécutif",
        "executive.kpis": "Indicateurs clés de performance",
        "executive.northStar": "Étoile du Nord",
        "executive.riskDashboard": "Tableau de bord des risques",
        "executive.strategicDirectives.title": "Directives stratégiques",
        "executive.strategicDirectives.addDirective": "Ajouter une directive",
        "executive.strategicDirectives.progress": "Progrès",
        "executive.nl2sql.title": "Requête en langage naturel",
        "executive.nl2sql.placeholder": "Posez une question sur vos données...",
        "executive.nl2sql.execute": "Exécuter la requête",
        
        # Products (Originally Arabic garbage in missing list, fixed to French)
        "products.allStock": "Tout le stock",
        "products.detail.addComponent": "Ajouter un composant",
        "products.detail.adjustDialog.apply": "Appliquer",
        "products.detail.adjustDialog.title": "Titre",
        "products.detail.adjustInventory": "Ajuster l'inventaire",
        "products.detail.analyzeIntel": "Analyser les renseignements",
        "products.detail.authorize": "Autoriser",
        "products.detail.backToProducts": "Retour aux produits",
        "products.detail.billOfMaterials": "Nomenclature (BOM)",
        "products.detail.bomDescription": "Description de la nomenclature",
        "products.detail.cloneNode": "Cloner le nœud",
        "products.detail.contextualIntelligence": "Intelligence contextuelle",
        "products.detail.deauthorize": "Révoquer",
        "products.detail.fiscalParameters": "Paramètres fiscaux",
        "products.detail.magnitudePulse": "Impulsion de magnitude",
        "products.detail.nodeSpecifications": "Spécifications du nœud",
        "products.detail.nodeTelemetry": "Télémesure du nœud",
        "products.detail.notFound": "Non trouvé",
        "products.detail.refineMasterData": "Affiner les données de base",
        "products.detail.stats.fiscalMargin": "Marge fiscale",
        "products.detail.stats.marketValuation": "Valorisation du marché",
        "products.detail.stats.nodeMagnitude": "Magnitude du nœud",
        "products.detail.stats.totalCycles": "Cycles totaux",
        "products.detail.stats.winProbability": "Probabilité de gain",
        "products.detail.temporalVelocity": "Vélocité temporelle",
        "products.detail.viewAllCycles": "Voir tous les cycles",
        "products.detail.viewLogs": "Voir les journaux",
        "products.edit.basicInformation": "Informations de base",
        "products.edit.category": "Catégorie",
        "products.edit.description": "Description",
        "products.edit.leadTime": "Délai de livraison",
        "products.edit.partNumber": "Numéro de pièce",
        "products.edit.productName": "Nom du produit",
        "products.edit.productUpdated": "Produit mis à jour",
        "products.edit.reorderPoint": "Point de commande",
        "products.edit.saveChanges": "Enregistrer les modifications",
        "products.edit.status": "Statut",
        "products.edit.statusInventory": "Statut de l'inventaire",
        "products.edit.title": "Titre",
        "products.edit.unitOfMeasure": "Unité de mesure",
        "products.edit.updateFailed": "Échec de la mise à jour",
        "products.emptyState.description": "Description",
        "products.emptyState.title": "Titre",
        "products.exportIntel": "Exporter les renseignements",
        "products.import": "Importer",
        "products.initializeNode": "Initialiser le nœud",
        "products.lowStock": "Stock faible",
        "products.new.basicIdentification": "Identification de base",
        "products.new.detailedContext": "Contexte détaillé",
        "products.new.establishNode": "Établir le nœud",
        "products.new.failedToEstablish": "Échec de l'établissement",
        "products.new.nodeSynchronized": "Nœud synchronisé",
        "products.new.partNodeIdentity": "Identité du nœud de pièce",
        "products.new.providePartAndName": "Veuillez fournir la pièce et le nom",
        "products.new.requiredParams": "Paramètres requis",
        "products.new.strategicName": "Nom stratégique",
        "products.new.subtitle": "Sous-titre",
        "products.new.supplyDynamics": "Dynamique d'approvisionnement",
        "products.new.syncFailed": "Échec de la synchronisation",
        "products.new.taxonomyCategory": "Catégorie de taxonomie",
        "products.new.temporalLead": "Délai temporel",
        "products.new.title": "Titre",
        "products.new.unitProtocol": "Protocole unitaire",
        "products.outOfStock": "Rupture de stock",
        "products.stats.activeInventoryNodes": "Nœuds d'inventaire actifs",
        "products.stats.aggregatedRevenue": "Revenus agrégés",
        "products.stats.meanMarginKPI": "KPI de marge moyenne",
        "products.stats.stockAbnormalities": "Anomalies de stock",
        "products.status.discontinued": "Abandonné",
        "products.stockLevel": "Niveau de stock",
        "products.table.inventory": "Inventaire",
        "products.table.leadTime": "Délai",
        "products.table.listPrice": "Prix catalogue",
        "products.table.margin": "Marge",
        "products.table.product": "Produit",
        "products.table.standardCost": "Coût standard",
        "products.table.totalSold": "Total vendu",
        "products.viewAnalytics": "Voir l'analyse",
        "products.viewBom": "Voir la nomenclature",
        
        # RTL Placeholders (Fixing Arabic)
        "rtl.inputPlaceholder": "Tapez ici...",
        "rtl.searchPlaceholder": "Cherchez ici...",
        "rtl.selectPlaceholder": "Sélectionnez...",
        
        # Tour
        "tour.closeTour": "Fermer la visite",
        "tour.productTour": "Visite du produit",
        "tour.stepOf": "{current} sur {total}"
    }

    # Load existing French locales
    if os.path.exists(target_file):
        with open(target_file, 'r', encoding='utf-8') as f:
            try:
                fr_data = json.load(f)
            except json.JSONDecodeError:
                print(f"Error: Could not decode {target_file}")
                return
    else:
        fr_data = {}

    updated_count = 0
    
    # 1. Apply known translations from our hardcoded map
    for key, value in translations.items():
        if set_nested_value(fr_data, key, value):
            updated_count += 1
            
    # 2. Check if there are keys in missing_fr_strict that we MISSED in our hardcoded map
    # If so, we can try to infer or fallback, but for now we'll just log them or leave them
    # as the user asked for a comprehensive dictionary.
    
    missed_keys = []
    for key in missing_data.keys():
        if key not in translations:
            missed_keys.append(key)
            
    if missed_keys:
        print(f"Warning: {len(missed_keys)} keys were in missing list but not in our dictionary.")
        # Optional: Print first few to debug
        for k in missed_keys[:5]:
            print(f" - {k}")

    # Write back to file
    with open(target_file, 'w', encoding='utf-8') as f:
        json.dump(fr_data, f, indent=2, ensure_ascii=False)
        
    print(f"Successfully updated {target_file} with {updated_count} translations.")

if __name__ == "__main__":
    main()
